---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Microsoft-JZJ.
--- DateTime: 2023/9/1 14:00
---

local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local CfgMgr = GameTableDefine.ConfigMgr
local InstanceDataManager = GameTableDefine.InstanceDataManager
local InstanceModel = GameTableDefine.InstanceModel
local InstanceAIBlackBoard = GameTableDefine.InstanceAIBlackBoard
local UIView = require("Framework.UI.View") -- 当工具类使用
local Random = CS.UnityEngine.Random
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")

local WALK_SPEED = 5.5
local RUN_SPEED = 15

---@class InstanceWorkerRunToWorkSeat:AIStateBase
---@field m_owner InstanceWorkerClass
local InstanceWorkerRunToWorkSeat = Class("InstanceWorkerRunToWorkSeat",AIStateBase)

function InstanceWorkerRunToWorkSeat:ctor()
    self.m_timerID = nil
    self.m_speed = nil
end

function InstanceWorkerRunToWorkSeat:OnEnter(...)
    local actor = select(1, ...)
    local actorData = actor.data
    local stateMachine = actor.m_stateMachine
    
    local speed = RUN_SPEED + Random.Range(-1.1, 1.1)

    if not actorData.workPosTr or actorData.workPosTr:IsNull() then
        actorData.furGO = InstanceModel:GetSceneRoomFurnitureGo(actorData.roomId ,actorData.furIndex)
        actorData.workPosTr = UIView:GetTrans(actorData.furGO, "workPos") --工位点
        actorData.workFaceTr = UIView:GetTrans(actorData.furGO, "face") --工位点朝向
        actorData.actPosTr = UIView:GetTrans(actorData.roomGO, "actionPos/actionPos_" .. actorData.furIndex) or actorData.workPosTr --工位点
        actorData.actFaceTr = UIView:GetTrans(actorData.roomGO, "actionPos/actionPos_" .. actorData.furIndex .. "/face") or UIView:GetTrans(actorData.furGO, "face") --工位点
        
    end
    --寻路到workSet
    actor:CalculatePath(
            actorData.workPosTr.position,
            true,
            speed,
            Random.Range(1.1, 4.1),
            function()
                actor:TryTransState(
                        function()
                            stateMachine:ChangeState(ActorDefine.State.InstanceWorkerWaklToWorkPos)
                        end
                )
            end
    )
    -- 播放动画
    actor:SetAnimator(PERSON_ACTION.RUN)
    -- 显示气泡
    actor:SetTheDisplayOfBubbles()

end

function InstanceWorkerRunToWorkSeat:OnExit()

end

return InstanceWorkerRunToWorkSeat