---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Microsoft-JZJ.
--- DateTime: 2023/9/1 13:57
---

local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local CfgMgr = GameTableDefine.ConfigMgr
local InstanceDataManager = GameTableDefine.InstanceDataManager
local InstanceModel = GameTableDefine.InstanceModel
local InstanceAIBlackBoard = GameTableDefine.InstanceAIBlackBoard
local UIView = require("Framework.UI.View") -- 当工具类使用
local Random = CS.UnityEngine.Random
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper



---@class InstanceWorkerEat:AIStateBase
---@field m_owner InstanceWorkerClass
local InstanceWorkerEat = Class("InstanceWorkerEat",AIStateBase)
local _actor = nil

function InstanceWorkerEat:ctor()
    
end

function InstanceWorkerEat:OnEnter(...)
    local actor = select(1, ...)
    _actor = actor
    local roomID = select(2, ...)
    local eatPosGO = select(3, ...)
    local eatRoomID = select(4, ...)
    local eatFurIndex = select(5, ...)
    local eatIndex = select(6, ...)
    
    local stateMachine = actor.m_stateMachine
    local colliderRespTable = InstanceAIBlackBoard:GetInstanceColliderTransTable(roomID)
    if not colliderRespTable then
        return
    end
    if not eatPosGO or eatPosGO:IsNull() then
        local furGO = InstanceModel:GetFurGameObject(eatRoomID, eatFurIndex)
        local workPosName = "workPos_"..eatIndex
        eatPosGO = UIView:GetTrans(furGO, workPosName)
    end
    local headStr = eatPosGO.transform.parent.parent.gameObject:GetInstanceID()..eatPosGO.name
    local furPosTable = colliderRespTable[headStr]
    local anim = furPosTable.anim
    --local needSetting = furPosTable.setting
    --local pos = furPosTable.pos
    --local furnGo = furPosTable.furnGo
    --local posGo = furPosTable.posGo

    local face = UIView:GetTrans(eatPosGO.gameObject, "face")
    -- 设置位置和旋转
    actor.gameObject.transform.position = eatPosGO.transform.position
    UnityHelper.RotateTowards(actor.gameObject.transform, Vector3(face.position.x, eatPosGO.transform.position.y, face.position.z))
    --播放动画
    actor:SetAnimator(anim[1])
    -- 显示气泡
    actor:SetTheDisplayOfBubbles("eat",roomID)
end

function InstanceWorkerEat:OnExit()
    print("=========== 退出吃饭", self.m_owner.instanceID)
    InstanceAIBlackBoard:UnbindActorWithSeat(self.m_owner)
end

function InstanceWorkerEat:OnDestroy()
    print("=========== 退出吃饭", self.m_owner.instanceID)
    InstanceAIBlackBoard:UnbindActorWithSeat(self.m_owner)
end

return InstanceWorkerEat