---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Microsoft-GXY.
--- DateTime: 2024/10/30 18:43
---
-- 创建一个队列类
---@class Queue
Queue = {}

-- 初始化队列
function Queue:new()
    local queue = { first = 0, last = -1 }
    setmetatable(queue, self)
    self.__index = self
    return queue
end

-- 入队操作
function Queue:enqueue(value)
    local last = self.last + 1
    self[last] = value
    self.last = last
end

-- 出队操作
function Queue:dequeue()
    if self.first > self.last then
        error("Queue is empty")
    end
    local first = self.first
    local value = self[first]
    self[first] = nil
    self.first = first + 1
    return value
end

-- 检查队列是否为空
function Queue:is_empty()
    return self.first > self.last
end

-- 获取队列的大小
function Queue:size()
    return self.last - self.first + 1
end

-- 示例用法
--local q = Queue:new()
--
--q:enqueue(1)
--q:enqueue(2)
--q:enqueue(3)
--
--print(q:dequeue()) -- 输出 1
--print(q:dequeue()) -- 输出 2
--
--print(q:is_empty()) -- 输出 false
--print(q:size())     -- 输出 1
--
--print(q:dequeue())  -- 输出 3
--print(q:is_empty()) -- 输出 true
--print(q:size())     -- 输出 0
