---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Microsoft-GXY.
--- DateTime: 2025/1/13 15:49:12
---
local Class = require("Framework.Lua.Class")
local ActorBase = require("CodeRefactoring.Actor.ActorBase")
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local FloatUI = GameTableDefine.FloatUI
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local PersonStateMachine = require("CodeRefactoring.AI.StateMachines.PersonStateMachine")
local Animator = CS.UnityEngine.Animator
local Vector3 = CS.UnityEngine.Vector3  ---@type UnityEngine.Vector3
local AnimationUtil = CS.Common.Utils.AnimationUtil
local ColliderResponse = require("GamePlay.Floors.Actors.ColliderResponse")
local CycleNightClubAIBlackBoard = GameTableDefine.CycleNightClubAIBlackBoard
local UnityHelper = CS.Common.Utils.UnityHelper

---@class CycleNightClubClient:ActorBase
---@field super ActorBase
local CycleNightClubClient = Class("CycleNightClubClient", ActorBase)

local ClientIndex = 1

function CycleNightClubClient:ctor()
    self.super.ctor(self)
    self.initialized = false
    self.m_type = ActorDefine.ActorType.CycleNightClubClient
    self.m_go = nil ---@type UnityEngine.GameObject
    self.m_animator = nil ---@type UnityEngine.Animator
    self.m_nextEmployeePlayTime = 0
    self.m_data = nil ---赋值后能再次使用
    self.view = nil ---@type FloatUIView
end

function CycleNightClubClient:Init(id, go, actorData)
    self.m_animator = go:GetComponent(typeof(Animator))
    self.m_go = go
    self.data = actorData
    self.m_data = actorData
    self.m_luaBehavior = UnityHelper.GetOrAddLuaBehavior(self.m_go)
    self.m_luaBehavior:SetOnDestroyEvent(handler(self,self.OnDestroy))
    
    --优化Animator性能
    if not self.m_animator:IsNull() and not self.m_animator.applyRootMotion then
        self.m_animator.cullingMode = CS.UnityEngine.AnimatorCullingMode.CullUpdateTransforms
    end
    --检测斜坡
    local path = self.m_path
    if not path then
        path = UnityHelper.AddAStartComp(go)
        self.m_path = path
    end
    path.checkSlope = true

    --创建行为状态机
    if not self.m_stateMachine then
        self.m_stateMachine = PersonStateMachine.create() ---@type PersonStateMachine
        self.m_stateMachine:SetOwner(self)
    end

    self.super.Init(self, id, go, actorData, self.m_stateMachine)
    self.data.type = "CycleNightClubClient"
    self.initialized = true
    self.m_go.transform.localScale = Vector3(1, 1, 1)

    if self.data.isPreload then
        local playData = CycleNightClubAIBlackBoard:GetSparePlayPos(self)
        self.m_stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleNightClubClientGotoPlay, playData)
    else
        self.m_stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleNightClubClientComeByBus, self)
    end

    self:SetDoorTrigger()
    --print("创建 CycleNightClubClient actorId = "..id..",ClientIndex = "..ClientIndex)
    go.name = ClientIndex..go.name
    ClientIndex = ClientIndex + 1
    self:InitFloatUIView()
end

function CycleNightClubClient:InitFloatUIView()
    FloatUI:SetObjectCrossCamera(self, nil,nil,0)
end

--region 气泡显示

---设置当前可以显示的气泡
function CycleNightClubClient:ShowBubble(bubbleName)

    self.m_bubbleName = bubbleName

    if not self.m_employeeBubbleTimer then
        local currentModel = CycleInstanceDataManager:GetCurrentModel()
        local cdData = currentModel.config_global.cy4_bubble_costume_cd
        local randomLeft = cdData[1] or 15
        local randomRight = cdData[2] or 30

        self.m_employeeBubbleTimer = GameTimer:CreateNewTimer(1,function()
            local now = currentModel:GetCachedTimeInSecond()
            if now >= self.m_nextEmployeePlayTime then
                self.m_nextEmployeePlayTime = now + math.random(randomLeft,randomRight)

                if self.m_bubbleName then
                    local view = self.view
                    if view then
                        if view:IsValid() then
                            view:Invoke("ShowCycleNightClubClientBubble",self.m_bubbleName)
                        else
                            FloatUI:FreeFloatUIView(self)
                        end
                    end
                end
            end
        end,true)
    end
end

---将Actor标记为WASTE,这样Table可以重复利用,相当于放入对象池
function CycleNightClubClient:Destroy()
    self:RecycleGO()
    self:OnDestroy()
end

function CycleNightClubClient:RemoveFloatUIView()
    FloatUI:RemoveObjectCrossCamera(self)
end

function CycleNightClubClient:OnDestroy()
    self:RemoveFloatUIView()
    if self.m_stateMachine then
        self.m_stateMachine:OnDestroy()
    end
    self.m_luaBehavior:ClearOnDestroyEvent()
    self.m_luaBehavior = nil
    self.m_go = nil
    self.gameObject = nil
    self.initialized = false
    self.m_animator = nil
    if self.m_path then
        self.m_path.m_targetReachedAction = nil
        self.m_path = nil
    end
    self.m_isPooling = true
end

function CycleNightClubClient:RecycleGO()
    local scene = CycleInstanceDataManager:GetCurrentModel():GetScene() ---@type CycleNightClubScene
    if scene then
        scene:RecycleActorGOToPool(self.m_go,self.data.prefabName)
    end
end

--endregion

--region 初始化 abandon
---设置与门交互的Trigger
function CycleNightClubClient:SetDoorTrigger()
    local animName = {"DoorOpenAnim", "ToiletDoor_open"}
    local animIndex = 1
    local enterFunc = function(responseGo, activatorGo, outRoom)
        local coll = responseGo:GetComponent("ColliderResponse")
        local anim = coll:GetDoorAnim()
        if not anim or coll:GetTriggerCount() > 1 then
            return
        end

        local lastAni = 1
        local currAni = AnimationUtil.GetAnimationState(anim, animName[lastAni])
        if not currAni then
            lastAni = 2
            currAni = AnimationUtil.GetAnimationState(anim, animName[lastAni])
        end
        local needAni = outRoom == true and "_revert" or ""

        if anim.isPlaying then
            return
        end

        AnimationUtil.Play(anim, animName[lastAni] .. needAni, function()
            AnimationUtil.GotoAndStop(anim, animName[lastAni] .. needAni, "KEY_FRAME_CLOSE_POINT")--放完停在末尾,让isPlay为true
        end)

        GameTableDefine.FloorMode:MakeDoorTimer(responseGo, function()--几秒后没人自动关闭
            if coll and not CS.UnityEngine.Object.ReferenceEquals( coll, nil ) and coll:GetTriggerCount() == 0 and anim then
                AnimationUtil.Play(anim, animName[lastAni] .. needAni, nil, -1, "KEY_FRAME_SECOND")
                return true
            elseif not anim then
                return 1--切换场景的时候没了...或者其他原因导致的错误
            end

            return false
        end)
    end
    ColliderResponse:SetActivatorTriggerEventOnEnter(ColliderResponse.TYPE_OPEN_DOOR, self.m_go, enterFunc)
end

--endregion

return CycleNightClubClient
