---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2023/8/28 14:31
---
local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
---@class AIStateToilet:AIStateBase
local AIStateToilet = Class("AIStateToilet",AIStateBase)
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")

function AIStateToilet:ctor()
end

function AIStateToilet:OnEnter()
    self.super:OnEnter()
    local action = PERSON_ACTION.IDLE
    local keyFrames = {{}}
    keyFrames[1].key = "ANIM_IDLE_END"
    keyFrames[1].func = function() self.owner:Event(self.owner.EVENT_IDLE_END) end
    self.owner.aiStateMachine:SetAnimator(action, keyFrames)
end

function AIStateToilet:OnExit()
    self.super:OnExit()
end

return AIStateToilet