---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/6/7 10:17
---

local Class = require("Framework.Lua.Class")
---@class Elevator
local Elevator = Class("Elevator")
local UnityHelper = CS.Common.Utils.UnityHelper
local ElevatorManager = GameTableDefine.ElevatorManager

function Elevator:ctor()
    self.m_targetTransform = {} ---@type UnityEngine.GameObject[]
    self.m_luaBehavior = nil ---@type Framework.Lua.LuaBehavior
    self.m_colliderComponent = nil ---@type ColliderResponse
    self.m_go = nil ---@type UnityEngine.GameObject
end

---@param component ColliderResponse
function Elevator:Init(component)
    self.m_colliderComponent = component
    self.m_go = component.gameObject
    self.m_luaBehavior = UnityHelper.GetOrAddLuaBehavior(self.m_go) ---@type Framework.Lua.LuaBehavior
    self.m_luaBehavior:SetOnDestroyEvent(handler(self,self.OnDestroy))

    local len = component.m_floors.Length
    for i = 0, len-1 do
        table.insert(self.m_targetTransform,component.m_floors[i])
    end

    ElevatorManager:AddEntity(self)
end

function Elevator:OnDestroy()
    ElevatorManager:RemoveEntity(self)
    self.m_luaBehavior:ClearOnDestroyEvent()
    self.m_luaBehavior = nil
    self.m_colliderComponent = nil
    self.m_targetTransform = {}
end
return Elevator