---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2023/10/10 10:48
---

local Class = require("Framework.Lua.Class")
local PersonBase = require("CodeRefactoring.Actor.Actors.PersonBase")
---@class EventInstanceNew:PersonBase
---@field super PersonBase
local EventInstanceNew = Class("EventInstanceNew",PersonBase)

local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local Vector3 = CS.UnityEngine.Vector3

EventInstanceNew.EVENT_LEAVE_SCENE = 1001

function EventInstanceNew:ctor(...)
    self:getSuper(EventInstanceNew).ctor(self,...)
    self.m_tempGo = nil
    self.m_eventId = nil
    self.m_facePos = nil
    self.m_type = ActorDefine.ActorType.EventInstance
end

function EventInstanceNew:Init(rootGo, tempGo, position, targetPosition,facePos, eventId)
    self.m_tempGo = tempGo
    self.m_eventId = eventId
    self.m_facePos = facePos
    self:getSuper(EventInstanceNew).Init(self,rootGo, nil, position, targetPosition)
end

function EventInstanceNew:OnLoadGOSuccess()
    self:getSuper(EventInstanceNew).OnLoadGOSuccess(self)

    self.m_go.transform.localScale = Vector3(3,3,3)

    self.m_stateMachine:ChangeState(ActorDefine.State.EventInstanceIdle)
end

return EventInstanceNew