---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2023/8/29 11:24
---
local Class = require("Framework.Lua.Class")
local PersonBase = require("CodeRefactoring.Actor.Actors.PersonBase")
---@class SimpleMoverNew:PersonBase
---@field super PersonBase
local SimpleMoverNew = Class("SimpleMoverNew",PersonBase)
local UnityHelper = CS.Common.Utils.UnityHelper

local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local ConfigMgr = GameTableDefine.ConfigMgr
local Vector3 = CS.UnityEngine.Vector3
local FloorMode = GameTableDefine.FloorMode

function SimpleMoverNew:ctor()
    self:getSuper(SimpleMoverNew).ctor(self)
    self.m_moveSpeed = 0
    self.m_sizeScale = 1
    self.m_waitTime = 0
    self.m_type = ActorDefine.ActorType.SimpleMover
end

function SimpleMoverNew:Init(rootGo, skinPath, initPos, moveSpeed, size, personID)
    self.m_moveSpeed = moveSpeed or ConfigMgr.config_global.Batman_walkspeed
    self.m_sizeScale = size or 1

    if not initPos then
        initPos = FloorMode:GetScene():GetOnePlace()
    end
    local hitPos,findResult = UnityHelper.SamplePositionByNavMesh(initPos,9,1)
    self:getSuper(SimpleMoverNew).Init(self,rootGo, skinPath, hitPos, nil, personID)
end

function SimpleMoverNew:OnLoadGOSuccess()
    self:getSuper(SimpleMoverNew).OnLoadGOSuccess(self)
    self.m_stateMachine:ChangeState(ActorDefine.State.SimpleMoverSaunterState)
    self.m_go.transform.localScale = Vector3(self.m_sizeScale,self.m_sizeScale,self.m_sizeScale)
end

return SimpleMoverNew