---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2023/9/7 16:40
---

local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
---@class EmployeeGoToToiletState:AIStateBase
---@field m_owner CompanyEmployeeNew
---走或跑去交互房间
local EmployeeGoToToiletState = Class("EmployeeGoToToiletState",AIStateBase)

local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local CfgMgr = GameTableDefine.ConfigMgr

function EmployeeGoToToiletState:ctor()
    self.m_targetInteraction = nil
    self.m_defaultStopDis = nil
end

function EmployeeGoToToiletState:OnEnter()
    local isRun = self.m_owner:HasFlag(ActorDefine.Flag.FLAG_EMPLOYEE_ON_TOILET) and true or false
    self.m_targetInteraction = self.m_owner:GetCurrentInteractionEntity()
    if self.m_targetInteraction then
        local destination = self.m_targetInteraction:GetQueueStartPos()
        self:MoveToInteraction(isRun,destination)
    else
        self.m_owner.m_stateMachine:ChangeState(ActorDefine.State.EmployeeGoToWorkState)
    end
    self.m_owner:CheckFloatState()
end

function EmployeeGoToToiletState:MoveToInteraction(isRun,destination)
    local speed = isRun and CfgMgr.config_global.character_run_v or CfgMgr.config_global.character_walk_v
    self.m_owner:RandomElevatorMoveTo(destination,nil,function()
        self.m_targetInteraction:AddQueuePath(self.m_owner)
    end,speed,nil,5.0)
    self.m_defaultStopDis = self.m_owner.m_path.endReachedDistance
    --self.m_owner.m_path.endReachedDistance = 5.0
end

function EmployeeGoToToiletState:OnExit()
    self.m_owner:StopMove()
    self.m_targetInteraction = nil
    if self.m_defaultStopDis then --还原到达距离
        self.m_owner.m_path.endReachedDistance = self.m_defaultStopDis
        self.m_defaultStopDis = nil
    end
end

function EmployeeGoToToiletState:OnDestroy()
    self.m_targetInteraction = nil
end

function EmployeeGoToToiletState:Event(msg, params)
end

return EmployeeGoToToiletState