---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/10/16 10:50
---

local Class = require("Framework.Lua.Class")
local UIView = require("Framework.UI.View")

---@class FirstPurchaseUIView:UIBaseView
local FirstPurchaseUIView = Class("FirstPurchaseUIView", UIView)

local FirstPurchaseUI = GameTableDefine.FirstPurchaseUI
local GameTimeManager = GameTimeManager
local ShopUI = GameTableDefine.ShopUI

function FirstPurchaseUIView:ctor()
    self.m_timerText = nil ---@type UnityEngine.UI.TMPLocalization
end

function FirstPurchaseUIView:OnEnter()

    FirstPurchaseUI:EnsureResetDoubleDiamond()

    local gotoBtn = self:GetComp("RootPanel/ShopContent/GotoBtn","Button")
    self:SetButtonClickHandler(gotoBtn,function()
        --TODO 跳转商城
        ShopUI:OpenAndTurnPageDiamond(1000)
        self:DestroyModeUIObject()
    end)

    local quitBtn = self:GetComp("RootPanel/ShopContent/quitBtn","Button")
    self:SetButtonClickHandler(quitBtn,function()
        self:DestroyModeUIObject()
    end)

    self.m_timerText = self:GetComp("RootPanel/ShopContent/timer/num","TMPLocalization")

    self:CreateTimer(1000,function()
        local endTime = FirstPurchaseUI:GetEndTime()
        local limitTime = math.max(0,endTime - GameTimeManager:GetCurrentServerTime())
        self.m_timerText.text = GameTimeManager:FormatTimeLength(limitTime)
        if limitTime <= 0 then
            self:DestroyModeUIObject()
        end
    end,true, true)
end

function FirstPurchaseUIView:OnExit(view)
    self.super:OnExit(self)
end

return FirstPurchaseUIView