---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/4/7 10:23
---

---@class StoryLineUI
local StoryLineUI = GameTableDefine.StoryLineUI

local GameUIManager = GameTableDefine.GameUIManager
local StoryLineUIView = require("GamePlay.Common.UI.StoryLineUIView")

function StoryLineUI:ctor()
    self.m_view = nil ---@type StoryLineUIView
end

function StoryLineUI:GetView()
    self.m_view = GameUIManager:SafeOpenUI(ENUM_GAME_UITYPE.Story_Line_UI, self.m_view, StoryLineUIView, self, self.CloseView)
    return self.m_view
end

function StoryLineUI:ShowStoryLineUI(passID,stageID)
    self:GetView():Invoke("Init",passID,stageID)
end

--function StoryLineUI:RefreshHint()
--    if self.m_view then
--        self.m_view:RefreshHint()
--    end
--end

function StoryLineUI:CloseView()
    GameUIManager:CloseUI(ENUM_GAME_UITYPE.Story_Line_UI)
    self.m_view = nil

    collectgarbage("collect")
end

return StoryLineUI