---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2023/10/10 10:53
---

local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
---@class EventInstanceWaiting:AIStateBase
---@field m_owner EventInstanceNew
local EventInstanceWaiting = Class("EventInstanceWaiting",AIStateBase)

local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")
local GameStateManager = GameStateManager
local InstanceMainViewUI = GameTableDefine.InstanceMainViewUI
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager

function EventInstanceWaiting:ctor()
    self.m_speed = nil
end

function EventInstanceWaiting:OnEnter()
    self.m_owner:SetAnimator(PERSON_ACTION.IDLE)

    self.m_owner:InitFloatUIView(self.m_owner.m_eventId)

    if GameStateManager:IsInstanceState() then
        InstanceMainViewUI:SetEventIAAActive(true)
    elseif GameStateManager:IsCycleInstanceState() then
        CycleInstanceDataManager:GetCycleInstanceMainViewUI():SetEventIAAActive(true)
    end
end

function EventInstanceWaiting:OnExit()
    self.m_owner:RemoveFloatUIView()
end

return EventInstanceWaiting