---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2023/8/30 15:25
---

local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
---@class EventBatmanWaiting:AIStateBase
---@field m_owner EventBatmanNew
local EventBatmanWaiting = Class("EventBatmanWaiting",AIStateBase)

local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local MainUI = GameTableDefine.MainUI
local FloorMode = GameTableDefine.FloorMode
local Event003UI = GameTableDefine.Event003UI
local EventManager = require("Framework.Event.Manager")

function EventBatmanWaiting:ctor()
    self.m_speed = nil
end

function EventBatmanWaiting:OnEnter()
    self.m_owner:SetAnimator(PERSON_ACTION.IDLE)

    self.m_owner:InitFloatUIView(self.m_owner.m_eventId)
    MainUI:SetEventBatmanHint(true)

    FloorMode:GetScene():SetButtonClickHandler(self.m_owner.m_go, function()
        Event003UI:ShowPanel()
    end)
end

function EventBatmanWaiting:Event(msg,params)
    --来的路上要结束
    if msg == self.m_owner.EVENT_LEAVE_SCENE then
        MainUI:SetEventBatmanHint(false)
        self.m_owner.m_stateMachine:ChangeState(ActorDefine.State.EventBatmanLeaving)
    elseif msg == self.m_owner.EVENT_CAST_SPELL then
        MainUI:SetEventBatmanHint(false)
        local keyFrames = {{},{}}
        keyFrames[1].key = "ANIM_CAST_SPELL_END"
        keyFrames[1].func = function()
            self.m_owner.m_stateMachine:ChangeState(ActorDefine.State.EventBatmanLeaving)
        end

        keyFrames[2].key = "ANIM_CAST_SPELL_KEY"
        keyFrames[2].func = function()
            EventManager:DispatchEvent("DAY_COME")
            MainUI:PlaySkipNight()
        end
        self.m_owner:SetAnimator(PERSON_ACTION.DANCE, keyFrames)
    end
end

function EventBatmanWaiting:OnExit()
    self.m_owner:RemoveFloatUIView()
    local scene = FloorMode:GetScene()
    if scene then
        FloorMode:GetScene():SetButtonClickHandler(self.m_owner.m_go, nil)
    end
end

return EventBatmanWaiting