---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2023/8/30 15:12
---

local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
---@class EventBatmanComing:AIStateBase
---@field m_owner EventBatmanNew
local EventBatmanComing = Class("EventBatmanComing",AIStateBase)

local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local MainUI = GameTableDefine.MainUI

function EventBatmanComing:ctor()
    self.m_speed = nil
end

function EventBatmanComing:OnEnter()
    self:DoMove()
end

---@private
---移动到目标点
function EventBatmanComing:DoMove()
    local destination = self.m_owner.m_targetPosition
    self.m_owner:MoveTo(destination,nil,function()
        self.m_owner.m_stateMachine:ChangeState(ActorDefine.State.EventBatmanWaiting)
    end)
end

function EventBatmanComing:OnExit()
    self.m_owner:StopMove()
end

function EventBatmanComing:Event(msg,params)
    --来的路上要结束
    if msg == self.m_owner.EVENT_LEAVE_SCENE then
        MainUI:SetEventBatmanHint(false)
        self.m_owner.m_stateMachine:ChangeState(ActorDefine.State.EventBatmanLeaving)
    end
end

return EventBatmanComing