-- this file is generated by program, never modify it!!!

local M = {
    version = 1713337912,
    [1000] = { msgname = "msg_c2s_req_login_addr", handler = "msg_c2s_req_login_addr", ackname = "msg_s2c_req_login_addr" },
    [1001] = { msgname = "msg_c2s_req_login", handler = "msg_c2s_req_login", ackname = "msg_s2c_req_login" },
    [1002] = { msgname = "msg_c2s_req_logout", handler = "msg_c2s_req_logout", ackname = "msg_s2c_ack_logout" },
    [1050] = { msgname = "nil", handler = "msg_c2s_req_mail_info", ackname = "msg_s2c_ack_mail_info" },
    [1051] = { msgname = "msg_c2s_req_mail_read", handler = "msg_c2s_req_mail_read", ackname = "msg_s2c_ack_mail_read" },
    [1052] = { msgname = "msg_c2s_req_mail_delete", handler = "msg_c2s_req_mail_delete", ackname = "msg_s2c_ack_mail_delete" },
    [1053] = { msgname = "msg_c2s_req_mail_take", handler = "msg_c2s_req_mail_take", ackname = "msg_s2c_ack_mail_take" },
    [1061] = { msgname = "msg_c2s_req_report_rank", handler = "msg_c2s_req_report_rank", ackname = "msg_s2c_ack_report_rank" },
    [1062] = { msgname = "msg_c2s_req_get_report_rank", handler = "msg_c2s_req_get_report_rank", ackname = "msg_s2c_ack_get_report_rank" },
    [1063] = { msgname = "msg_c2s_req_cheat_tag", handler = "msg_c2s_req_cheat_tag", ackname = "msg_s2c_ack_cheat_tag" },
}
return M