---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/6/24 18:22
---

---@class CycleNightClubSlotMachineUI
local CycleNightClubSlotMachineUI = GameTableDefine.CycleNightClubSlotMachineUI

local GameUIManager = GameTableDefine.GameUIManager
local ConfigMgr = GameTableDefine.ConfigMgr
local UnityRandom = CS.UnityEngine.Random
local ShopManager = GameTableDefine.ShopManager

---每一行有多少个格子
CycleNightClubSlotMachineUI.SlotCount = 3

CycleNightClubSlotMachineUI.SlotAudioConf = {
    [1] = "111",
    [2] = "222",
    [3] = "333",
    [4] = "444",
}

--CycleNightClubSlotMachineUI.RewardName = {
--    [1] = "红色",
--    [2] = "蓝色",
--    [3] = "绿色"
--}

---奖励类型
CycleNightClubSlotMachineUI.RewardType = {
    AAA = 1,
    BBB = 2,
    CCC = 3
}

---奖励出现个数对应的奖励倍率
CycleNightClubSlotMachineUI.RewardMagnificationByCount = {
    [1] = 0,
    [2] = 4,
    [3] = 12,
    [4] = 32,
}

--CycleNightClubSlotMachineUI.RewardList = {
--    [1] = CycleNightClubSlotMachineUI.RewardType.AAA,
--    [2] = CycleNightClubSlotMachineUI.RewardType.BBB,
--    [3] = CycleNightClubSlotMachineUI.RewardType.CCC
--}

CycleNightClubSlotMachineUI.RewardCount = 3

--- 1.技能书，2.英雄经验，3.货币，4.积分,5.钻石,6.蓝图
CycleNightClubSlotMachineUI.FlyIconConfig = {
    [1] = "RootPanel/reward1",
    [2] = "RootPanel/reward2",
    [3] = "RootPanel/reward3",
    [4] = "RootPanel/reward4",
    [5] = "RootPanel/reward5",
    [6] = "RootPanel/reward6",
}

CycleNightClubSlotMachineUI.CurRewards = {}
CycleNightClubSlotMachineUI.CurRewardsNotCombine = {} ---不合并的奖励


---[奖励倍率,硬币倍率]
CycleNightClubSlotMachineUI.SlotMagnificationConfig = {
    [1] = {1,1},
    [2] = {3,3},
    [3] = {10,7}
}

---@type ConfigSlotMachines
---@field id number
---@field shop_id number
---@field probability number
---@field icon string
---@field desc string
local ConfigSlotMachines = {}

---@type RewardConfig
---@field curWeight number
---@field config ConfigSlotMachines
local RewardConfig = {}

function CycleNightClubSlotMachineUI:ctor()
    self.m_initialized = false ---是否初始化
    self.m_totalWeight = 100 ---总权重
    self.m_slotConfigs = {} ---@type ConfigSlotMachines[][] -每格奖励配置的先列后行
    self.m_slotResult = {} ---本次拉霸机转动结果
    self.m_ConsolationPrizeCfg = nil ---安慰奖的ShopConfig
    self.m_maybeBigReward = false ---本次转动是否有可能出大奖,即前N-1个奖励是一样的
end

function CycleNightClubSlotMachineUI:GetView()
    self.m_view = GameUIManager:SafeOpenUI(ENUM_GAME_UITYPE.CYCLE_NIGHT_CLUB_SLOT_MACHINE, self.m_view, require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubSlotMachineUIView"), self, self.CloseView)
    return self.m_view
end

function CycleNightClubSlotMachineUI:OpenView()
    self:Init()
    self:GetView():Invoke("Init")
end

function CycleNightClubSlotMachineUI:CloseView()
    GameUIManager:CloseUI(ENUM_GAME_UITYPE.CYCLE_NIGHT_CLUB_SLOT_MACHINE)
    self.m_view = nil
    collectgarbage("collect")
    --local guideID = GameTableDefine.CycleInstanceDataManager:GetCurrentModel():GetGuideID()
    --if guideID == 14036 then
    --    GameTableDefine.CycleInstanceDataManager:GetCurrentModel():SetGuideID(14037)
    --    GameTableDefine.GuideManager.currStep = 14037
    --    GameTableDefine.GuideManager:ConditionToStart()
    --end
end

function CycleNightClubSlotMachineUI:SetConfigsToSlot(level)
    level = level or 1
    self.m_totalWeight = 100
    self.m_slotConfigs = {}
    
    self.m_slotMachineConfigs = ConfigMgr.config_slot_machines[GameTableDefine.CycleInstanceDataManager:GetCurrentModel().instance_id][level]
    self.m_slotMachineRewardsConfig = ConfigMgr.config_slot_machines_rewards[GameTableDefine.CycleInstanceDataManager:GetCurrentModel().instance_id][level]
    
    CycleNightClubSlotMachineUI.SlotCount = #self.m_slotMachineConfigs[1].compose
    CycleNightClubSlotMachineUI.RewardCount = #self.m_slotMachineConfigs

    for i = 1, CycleNightClubSlotMachineUI.SlotCount do
        self.m_slotConfigs[i] = {}
    end

    for k, slotMachineConfig in pairs(self.m_slotMachineConfigs) do
        --将配置放入对应拉霸机的孔位
        for slotIndex,rewardIndex in ipairs(slotMachineConfig.compose) do
            self.m_slotConfigs[slotIndex][rewardIndex] = slotMachineConfig
        end

        --安慰奖
        local shopCfg = ShopManager:GetCfg(slotMachineConfig.shop_id)
        if shopCfg.type == 31 then
            self.m_ConsolationPrizeCfg = shopCfg
        end
    end
end

---初始化配置
function CycleNightClubSlotMachineUI:Init()
    self:SetConfigsToSlot(GameTableDefine.CycleInstanceDataManager:GetCurrentModel():GetSlotMachineLevel())
    if not self.m_initialized then
        --硬币倍率
        CycleNightClubSlotMachineUI.SlotMagnificationConfig[3][2] = math.floor(CycleNightClubSlotMachineUI.SlotMagnificationConfig[3][1] * (1-0.01 * ConfigMgr.config_global.ten_fold_discount))
        self.m_initialized = true
    end
end

---获取对应位置的图标
function CycleNightClubSlotMachineUI:GetSlotSpriteName(slotIndex,itemIndex)
    local slotConfig = self.m_slotConfigs[slotIndex][itemIndex]
    return slotConfig.icon
end

---获取一个Slot对应的结果 index
---@return number 结果在slot中的index
function CycleNightClubSlotMachineUI:GetRandomResultType(slotIndex, type)
    --local randomValue = UnityRandom.Range(0,self.m_totalWeight)
    --local configID ---@type number
    ----TODO 改获取结果流程
    --for i =1,#self.m_slotMachineRewardsConfig.rewards do
    --    if self.m_rewardConfigs[i].curWeight>=randomValue then
    --        configID = self.m_rewardConfigs[i].config.id
    --        break
    --    end
    --end
    local rewardIndexInSlot = nil
    local slotConfigList = self.m_slotConfigs[slotIndex]
    for indexInSlot,v in ipairs(slotConfigList) do
        if v.type == type then
            rewardIndexInSlot = indexInSlot
        end
    end
    return rewardIndexInSlot
    --等概率随机一个结果
    --return CycleNightClubSlotMachineUI.RewardList[math.random(1, #CycleNightClubSlotMachineUI.RewardList)]
end

---拉动遥感，提前算出奖励，再通过UI表现让玩家获得
function CycleNightClubSlotMachineUI:Push()
    local slotResult = {}
    local guideID = GameTableDefine.GuideManager.currStep
    if guideID == 16207 then
        slotResult[1] = 3
        slotResult[2] = 1
        slotResult[3] = 3
        --GameTableDefine.CycleInstanceDataManager:GetCurrentModel():SetGuideID(14031)
    else
        -- 获取拉霸机结果
        local rollResult = {}
        local resultCfg, resultNum = nil, nil
        local randomValue = UnityRandom.Range(0, self.m_totalWeight)
        if randomValue > self.m_slotMachineRewardsConfig.sum then
            -- 每个都不同的概率
        else
            for k,v in ipairs(self.m_slotMachineRewardsConfig.rewards) do
                local isBreaK = false
                for rangeIndex, range in ipairs(v.range) do
                    if randomValue <= range then
                        resultCfg, resultNum = v, rangeIndex + 1
                        isBreaK = true
                        break
                    end
                end
                if isBreaK then
                    break
                end
            end
        end
        --根据概率计算结果得出奖励排布方式
        if resultCfg == nil then
            for k, v in pairs(self.m_slotMachineRewardsConfig.rewards) do
                rollResult[k] = v
            end
        else
            for i = 1, resultNum do
                table.insert(rollResult, resultCfg)
            end
            --填充剩下的格子
            if resultNum < CycleNightClubSlotMachineUI.SlotCount then
                local remaining = {} 
                for k, v in pairs(self.m_slotMachineRewardsConfig.rewards) do
                    if v.type ~= resultCfg.type then
                        remaining[#remaining + 1] = v
                    end
                end
                if CycleNightClubSlotMachineUI.SlotCount - resultNum == 1 then
                    local random = UnityRandom.Range(0, 1)
                    table.insert(rollResult, remaining[random < 0.5 and 1 or 2])
                else
                    table.insert(rollResult, remaining[1])
                    table.insert(rollResult, remaining[2])
                end
            end
        end
        --rollResult = { self.m_slotMachineRewardsConfig.rewards[1], self.m_slotMachineRewardsConfig.rewards[1], self.m_slotMachineRewardsConfig.rewards[3] }
        rollResult = Tools:ShuffleArray(rollResult)
        local debugResult = ""
        for i = 1, #rollResult do
            debugResult = debugResult .. "   " .. rollResult[i].price
        end
        printf(debugResult)
                
        for i = 1, CycleNightClubSlotMachineUI.SlotCount do
            local resultIndex = self:GetRandomResultType(i, rollResult[i].type)
            slotResult[i] = resultIndex
        end
    end

    local rewards = {}
    local rewardsNotCombine = {}
    for i = 1, CycleNightClubSlotMachineUI.SlotCount do
        local inSlotIndex = slotResult[i]
        local rewardIndex = self.m_slotConfigs[i][inSlotIndex].type
        rewards[rewardIndex] = (rewards[rewardIndex] or 0) + 1
        rewardsNotCombine[i] = rewardIndex
    end
    self.m_slotResult = slotResult
    CycleNightClubSlotMachineUI.CurRewards = rewards
    CycleNightClubSlotMachineUI.CurRewardsNotCombine = rewardsNotCombine
    self.m_maybeBigReward = self:MaybeBigReward()

    --埋点
    local trackResult = ""
    for i = 1, CycleNightClubSlotMachineUI.SlotCount do
        local inSlotIndex = slotResult[i]
        local rewardType = self.m_slotConfigs[i][inSlotIndex].type or 0
        trackResult = trackResult..rewardType
    end
    local magIndex = GameTableDefine.CycleInstanceDataManager:GetCurrentModel():GetCurSlotMagnification()
    local coinRatio = CycleNightClubSlotMachineUI.SlotMagnificationConfig[magIndex][1] ---代币倍率
    GameTableDefine.CycleInstanceDataManager:GetCurrentModel():PushSlotNumAdd()
    GameTableDefine.CycleInstanceDataManager:GetCurrentModel():PushSlotRotioNum(coinRatio)
    GameSDKs:TrackForeign("cyinstance_slot", {rate = coinRatio, result = tonumber(trackResult)})

    return slotResult
end

---获取奖励
function CycleNightClubSlotMachineUI:GetRewards()
    --local rewardString = "最终奖励为"
    local finalRewardCount = 0
    local magIndex = GameTableDefine.CycleInstanceDataManager:GetCurrentModel():GetCurSlotMagnification()
    local coinRatio = CycleNightClubSlotMachineUI.SlotMagnificationConfig[magIndex][1] ---代币倍率
    --计算奖励
    for rewardID,rewardCount in pairs(CycleNightClubSlotMachineUI.CurRewards) do
        ---奖励倍率
        local rewardRatio = CycleNightClubSlotMachineUI.RewardMagnificationByCount[rewardCount] * coinRatio
        local slotMachinesConfig = nil ---@type ConfigSlotMachines
        for k, v in pairs(self.m_slotMachineConfigs) do
            if v.type == rewardID then
                slotMachinesConfig = v
                break
            end
        end
        --local name = GameTextLoader:ReadText(slotMachinesConfig.icon)
        if rewardRatio > 0 then
            finalRewardCount = finalRewardCount + 1
            --rewardString = rewardString.."奖励 类型:"..name .. ",数量:"..rewardRatio
            local shopID = slotMachinesConfig.shop_id
            ShopManager:Buy_LimitPackReward(shopID , nil,function()
                local value,typeName = ShopManager:GetValueByShopId(shopID)
                --if type(value) == "number" then
                --    value = value * rewardRatio
                --end
                local skillInfos
                local cfg = ShopManager:GetCfg(shopID)
                if typeName == "cycle_instance_cash" then
                    value = BigNumber:Multiply(value,rewardRatio)
                    GameTableDefine.CycleInstanceDataManager:GetCurrentModel():AddCurInstanceCoin(value)
                    GameTableDefine.CycleNightClubMainViewUI:Refresh()
                elseif typeName == "instanceHeroExp" then
                    value = BigNumber:Multiply(value,rewardRatio)
                    GameTableDefine.CycleInstanceDataManager:GetCurrentModel():ChangeCurHeroExpRes(value)
                    GameTableDefine.CycleNightClubMainViewUI:Refresh()
                elseif typeName == "instanceSkillBook" then
                    value = value * rewardRatio
                    skillInfos = GameTableDefine.CycleInstanceDataManager:GetCurrentModel():AddSkillPoints(value)
                elseif typeName == "cycle_instance_points" then
                    value = BigNumber:Multiply(value,rewardRatio)
                    GameTableDefine.CycleInstanceDataManager:GetCurrentModel():AddScore(value)
                elseif typeName == "cycle_instance_diamond" then
                    value = value * rewardRatio
                    GameTableDefine.ResourceManger:AddDiamond(value)
                elseif typeName == "cycle_instance_blueprint" then
                    value = math.floor(value * rewardRatio)
                    local bluePrintManager = GameTableDefine.CycleInstanceDataManager:GetCurrentModel():GetBluePrintManager()
                    bluePrintManager:ChangeUpgradeResCount(nil,value)
                    GameSDKs:TrackForeign("cy_bp_res", { source = "拉霸机", num = tonumber(value), type = 1 })
                end
                --flyIcon
                local flyIconPath = CycleNightClubSlotMachineUI.FlyIconConfig[rewardID]
                local showValue = ShopManager:SetValueToShow(value, cfg)
                if typeName == "instanceSkillBook" then
                    self.m_view:Invoke("PlayFlyIconSkill",flyIconPath,rewardCount==CycleNightClubSlotMachineUI.SlotCount,skillInfos)
                else
                    self.m_view:Invoke("PlayFlyIcon",flyIconPath,rewardCount==CycleNightClubSlotMachineUI.SlotCount,showValue)
                end
            end,false,rewardRatio)
        end
    end
    if finalRewardCount == 0 then
        --安慰奖
        local shopID = self.m_ConsolationPrizeCfg.id
        ShopManager:Buy(shopID , false,nil,function()
            local value,typeName = ShopManager:GetValueByShopId(shopID)
            if type(value) == "number" then
                value = value * coinRatio
            end
            local showValue = ShopManager:SetValueToShow(value, self.m_ConsolationPrizeCfg)
            if typeName == "cycle_instance_cash" then
                GameTableDefine.CycleInstanceDataManager:GetCurrentModel():AddCurInstanceCoin(value)
                GameTableDefine.CycleNightClubMainViewUI:Refresh()
            end
            --flyIcon
            local flyIconPath = CycleNightClubSlotMachineUI.FlyIconConfig[3]
            self.m_view:Invoke("PlayFlyIcon",flyIconPath,false,showValue)
        end)
    end
    --local slotResult = "转动结果为 :"
    --for i = 1, 3 do
    --    slotResult = slotResult..self.m_slotResult[i]
    --end
    --printf(slotResult)
    --printf(rewardString)
end

---升级条件
---@return boolean,number,number -是否能升级,升级所需前置建筑,升级消耗的货币
function CycleNightClubSlotMachineUI:GetUpgradeCondition()
    local level = GameTableDefine.CycleInstanceDataManager:GetCurrentModel():GetSlotMachineLevel()
    local nextLevel = level+1
    local nextLevelConfigs = ConfigMgr.config_slot_machines[GameTableDefine.CycleInstanceDataManager:GetCurrentModel().instance_id][nextLevel]
    if nextLevelConfigs then
        local roomID = nextLevelConfigs[1].building
        local cost = nextLevelConfigs[1].cost
        local haveCoin = GameTableDefine.CycleInstanceDataManager:GetCurrentModel():GetCurInstanceCoin()
        return BigNumber:CompareBig(haveCoin , cost),roomID,cost
    else
        return nil
    end
end

---拉霸机最大等级
---@return number
function CycleNightClubSlotMachineUI:GetMaxLevel()
    return #ConfigMgr.config_slot_machines[GameTableDefine.CycleInstanceDataManager:GetCurrentModel().instance_id]
end

---是否有可能是大奖,前N-1个奖励都一样时，就算可能是大奖的情况
function CycleNightClubSlotMachineUI:MaybeBigReward()
    local firstReward = CycleNightClubSlotMachineUI.CurRewardsNotCombine[1] or 0
    for i = 2, CycleNightClubSlotMachineUI.SlotCount-1 do
        if CycleNightClubSlotMachineUI.CurRewardsNotCombine[i] ~= firstReward then
            return false
        end
    end
    return true
end

---刷新小猪
function CycleNightClubSlotMachineUI:RefreshPiggyBank()
    if self.m_view then
        self.m_view:Invoke("RefreshPiggyBank")
    end
end

return CycleNightClubSlotMachineUI