---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/6/28 15:00
---

---@class CycleNightClubMainViewUI
local CycleNightClubMainViewUI = GameTableDefine.CycleNightClubMainViewUI

local GameUIManager = GameTableDefine.GameUIManager
local ConfigMgr = GameTableDefine.ConfigMgr
local EventManager = require("Framework.Event.Manager")

function CycleNightClubMainViewUI:GetView()
    self.m_view = GameUIManager:SafeOpenUI(ENUM_GAME_UITYPE.CYCLE_NIGHT_CLUB_MAIN_VIEW_UI, self.m_view, require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubMainViewUIView"), self, self.CloseView)
    return self.m_view
end

function CycleNightClubMainViewUI:CloseView()
    GameSDKs:TrackForeign("cy_instance_quit", { type = "返回主场景" })
    EventManager:DispatchEvent("BACK_TO_SCENE")
    GameTableDefine.CityMode:EnterDefaultBuiding()
    GameUIManager:CloseUI(ENUM_GAME_UITYPE.CYCLE_NIGHT_CLUB_MAIN_VIEW_UI)
    self.m_view = nil
    collectgarbage("collect")
end

function CycleNightClubMainViewUI:OpenUI()
    self:GetView()
end

function CycleNightClubMainViewUI:Refresh()
    if self.m_view then
        self.m_view:Invoke("Show")
    end
end

function CycleNightClubMainViewUI:Exit()
    if self.m_view then
        self.m_view:Invoke("DestroyModeUIObject")
    end
end


function CycleNightClubMainViewUI:CallNotify(notifyType,...)
    if self.m_view then
        local args = {...}
        self.m_view:Invoke("CallNotify",notifyType,...)
    end
end

function CycleNightClubMainViewUI:SetAchievementActive(active)
    if self.m_view then
        self.m_view:Invoke("SetAchievementActive",active)
    end
end

function CycleNightClubMainViewUI:SetEventActive(active)
    if self.m_view then
        self.m_view:Invoke("SetEventActive",active)
    end
end

function CycleNightClubMainViewUI:SetEventIAAActive(active)
    if self.m_view then
        self.m_view:Invoke("SetEventIAAActive",active)
    end
end

function CycleNightClubMainViewUI:SetPackActive(active)
    if self.m_view then
        self.m_view:Invoke("SetPackActive",active)
    end
end

--礼包刷新接口
function CycleNightClubMainViewUI:RefreshPackButton()
    if self.m_view and self.m_view.RefreshPackButton then
        self.m_view:RefreshPackButton()
    end
end

--刷新蓝图按钮状态
function CycleNightClubMainViewUI:RefreshBlueprintButton()
    if self.m_view and self.m_view.RefreshBlueprintButton then
        self.m_view:RefreshBlueprintButton()
    end
end

---播放里程碑分数奖励动画
function CycleNightClubMainViewUI:PlayMilestoneAnim()
    if self.m_view then
        self.m_view:PlayMilestoneAnim()
    end
end

---播放副本故事TimeLine时隐藏CycleMainUI
---@param isPlay boolean -等于true播放显示动画，等于false隐藏
function CycleNightClubMainViewUI:GuideTimeUIState(isPlay)
    self:GetView():Invoke("GuideTimeUIState", isPlay)
end

function CycleNightClubMainViewUI:PlayCloseGiftAnima()
    if self.m_view then
        self.m_view:PlayCloseGiftAnima()
    end    
end

---根据引导状态刷新界面入口
function CycleNightClubMainViewUI:RefreshUIEntryByGuideState()
    if self.m_view then
        self.m_view:RefreshUIEntryByGuideState()
    end
end

---刷新小猪
function CycleNightClubMainViewUI:RefreshPiggyBank()
    if self.m_view then
        self.m_view:Invoke("RefreshPiggyBank")
    end
end
