require("GameUtils.GameTimer")
require("GameUtils.GameTimeManager")

require("Framework.Event.EventDispatcher")
require("GameUtils.Tools")
require("GameBase.GameTableDefine")
require("Framework.UI.Manager")
require("Framework.UI.UIRedirect")
require("Framework.DataStructures.Queue")
require("Framework.DataStructures.Stack")

require("Network.GameNetwork")
require("Network.GameServerHttpClient")

require("GameBase.ConfigMgr")
require("Framework.UI.Manager")
require("GameState.GameStateManager")

require("GameUtils.GameTextLoader")
require("GameData.GameLanguage")

require("GameSound.SoundConst")
require("GameSound.SoundEngine")

require("GameData.LocalDataManager")
require("GameData.ActivityFileDataManager")
require("GameUtils.GfileSystemMgr")
require("GameUtils.GActivityFileSysMgr")

require("GameUtils.ExceptionHandler")
require("GameUtils.SDKs.GameSDKs")

require("GamePlay.Utils.CommonUtils")
require("GamePlay.Launch.Model")
require("GameUtils.OfflineManager")


require("GamePlay.City.CityMode")
require("GamePlay.Floors.FloorMode")
require("GamePlay.City.CountryMode")
require("GamePlay.Floors.CompanyMode")
require("GamePlay.Common.StarMode")
require("GamePlay.Buildings.BuildingPop")
require("GamePlay.Common.CashEarn")
require("GamePlay.Common.GameClockManager")
require("GamePlay.Common.LightManager")
require("GamePlay.Common.ActorEventManger")
require("GamePlay.Common.ChatEventManager")
require("GamePlay.Common.ValueManager")
require("GamePlay.Common.MeetingEventManager")
--require("GamePlay.Common.AZhenMessage")
require("GamePlay.Buildings.GreateBuildingMana")
require("GamePlay.Common.ActivityRankDataManager")
require("GamePlay.Common.TimeLimitedActivitiesManager")
require("GamePlay.Common.ActivityRemoteConfigManager")

require("GamePlay.Common.ResourceManger")
require("GamePlay.Floors.UI.HUD")
require("GamePlay.City.UI.UIDemo")
require("GamePlay.City.UI.CityMapUI")
require("GamePlay.City.UI.BossTalkUI")
require("GamePlay.City.UI.BossChooseUI")
require("GamePlay.City.UI.BenameUI")

require("GamePlay.Floors.UI.RoomBuildingUI")
require("GamePlay.Common.UI.MainUI")
require("GamePlay.Floors.UI.CompanysUI")
require("GamePlay.Common.UI.DiamondRewardUI")
require("GamePlay.Common.UI.DiamondShopUI")
require("GamePlay.Common.UI.TicketUseUI")
require("GamePlay.Common.UI.OfflineRewardUI")
require("GamePlay.Common.UI.CollectionUI")
require("GamePlay.Common.UI.CompanyMapInfoUI")
require("GamePlay.Common.UI.TipsUI")
require("GamePlay.Common.UI.Event001UI")
require("GamePlay.Common.UI.Event003UI")
require("GamePlay.Common.UI.Event004UI")
require("GamePlay.Common.UI.Event005UI")
require("GamePlay.Common.UI.Event006UI")
require("GamePlay.Common.UI.QuestUI")
require("GamePlay.Common.QuestManager")
require("GamePlay.Floors.UI.ContractUI")
require("GamePlay.Floors.UI.CompanyLvUpUI")
require("GamePlay.Floors.UI.RenewUI")
require("GamePlay.Floors.UI.HouseContractUI")
require("GamePlay.Floors.UI.ForbesRewardUI")

require("GamePlay.Floors.UI.RoomUnlockUI")
require("GamePlay.Floors.UI.UnlockingSkipUI")
require("GamePlay.Common.UI.FloatUI")
require("GamePlay.Common.UI.FlyIconsUI")
require("GamePlay.Common.UI.ChooseUI")
require("GamePlay.Common.UI.GuideUI")
require("GamePlay.Common.GuideManager")
require("GamePlay.Common.UI.SettingUI")
require("GamePlay.Common.UI.DoubleRewardUI")
require("GamePlay.Common.UI.GiftUI")
require("GamePlay.Common.UI.CutScreenUI")
require("GamePlay.Common.UI.EventMeetingUI")
require("GamePlay.Common.UI.CloudStorageUI")
require("GamePlay.Common.UI.RateUI")
require("GamePlay.Common.UI.RewardUI")
require("GamePlay.Common.UI.ChatEventUI")
require("GamePlay.Common.UI.SceneChatInfoUI")
require("GamePlay.Common.UI.TalkUI")
require("GamePlay.Common.UI.ConformUI")
require("GamePlay.Common.UI.ActivityRankUI")
require("GamePlay.Common.UI.ActivityRankRewardGetUI")
require("GamePlay.Common.UI.BoardUI")
require("GamePlay.Common.UI.SupplementOrderUI")

require("GamePlay.Phone.BuyCarManager")
require("GamePlay.Phone.UI.PhoneUI")
require("GamePlay.Phone.UI.ChatUI")
require("GamePlay.Phone.UI.BankUI")
require("GamePlay.Phone.UI.ChatInfoUI")
require("GamePlay.Phone.UI.ChatInfoUI2")
require("GamePlay.Phone.UI.BuyCarUI")
require("GamePlay.Phone.UI.BuyCarInfoUI")
require("GamePlay.Phone.UI.RankListUI")

-- require("GamePlay.Shop.IAP")
if GameConfig:IsWarriorVersion() then
require("GamePlay.Shop.WarriorIAP")
elseif GameConfig:IsLeyoHKVersion() then
require("GamePlay.Shop.LeyoHKIAP")
else
require("GamePlay.Shop.IAP")
end

require("GamePlay.Shop.Shop")
require("GamePlay.Shop.ShopUI")
require("GamePlay.Shop.IntroduceUI")
require("GamePlay.Shop.RouletteUI")
require("GamePlay.Shop.ShopManager")
require("GamePlay.Shop.ShopAfterPerson")
require("GamePlay.Floors.HouseMode")
require("GamePlay.Floors.PetMode")
require("GamePlay.Shop.GameCenterUI")

require("GamePlay.Shop.PurchaseSuccessUI")
require("GamePlay.Shop.DiamondFundUI")
require("GamePlay.Shop.AdFreeUI")
require("GamePlay.Factory.FactoryMode")
require("GamePlay.Factory.UI.WorkShopUnlockUI")
require("GamePlay.Factory.UI.WorkShopInfoUI")
require("GamePlay.Factory.UI.OrderUI")
require("GamePlay.Common.UI.StockFullUI")
require("GamePlay.Common.UI.OrderFinishUI")
require("GamePlay.Common.UI.PiggyBankUI")
require("GamePlay.Common.UI.PetListUI")
require("GamePlay.Common.UI.PetInteractUI")
require("GamePlay.Common.UI.ActivityUI")
require("GamePlay.Factory.UI.WorkshopItemUI")
require("GamePlay.City.UI.WorldListUI")
require("GamePlay.City.UI.ExchangeUI")
require("GamePlay.Common.UI.FragmentActivityUI")
require("GamePlay.Common.UI.CheatUI")
require("GamePlay.Common.UI.PersonInteractUI")
require("GamePlay.DressUp.DressUpDataManager")
require("GamePlay.Common.UI.LimitPackUI")
require("GamePlay.Common.UI.LimitChooseUI")

require("GamePlay.Common.AccumulatedChargeActivityDataManager")
require("GamePlay.Common.UI.AccumulatedChargeACUI")
require("GamePlay.QuestionSurvey.QuestionSurveyDataManager")
require("GamePlay.QuestionSurvey.UI.QuestionSurveyUI")
require("GamePlay.QuestionSurvey.UI.QuestionSurveyNewUI")
require("GamePlay.FootballClub.FootballClubModel")
require("GamePlay.FootballClub.UI.FCLevelupUI")
require("GamePlay.FootballClub.UI.FCStadiumUI")
require("GamePlay.FootballClub.UI.FCClubCenterUI")
require("GamePlay.FootballClub.UI.FCHealthCenterUI")
require("GamePlay.FootballClub.UI.FCTacticalCenterUI")
require("GamePlay.FootballClub.UI.FCTrainingGroundUI")
require("GamePlay.FootballClub.UI.FCRoomUnlockUI")
require("GamePlay.FootballClub.UI.FCLeagueRankUI")
require("GamePlay.FootballClub.UI.FootballClubLeagueRankDataManager")
require("GamePlay.FootballClub.UI.FCSettlementUI")
require("GamePlay.FootballClub.UI.FCTrainningRewardUI")
require("GamePlay.FootballClub.UI.FCLeagueUpUI")
require("GamePlay.Instance.InstanceDataManager")
require("GamePlay.Instance.UI.InstanceViewUI")
require("GamePlay.Instance.UI.InstanceMainViewUI")
require("GamePlay.Instance.UI.InstanceTimeUI")
require("GamePlay.Instance.UI.InstanceRewardUI")
require("GamePlay.Instance.UI.InstanceMilepostUI")
require("GamePlay.Instance.UI.InstanceBuildingUI")
require("GamePlay.Instance.InstanceModel")
require("GamePlay.Instance.UI.InstanceUnlockUI")
require("GamePlay.Instance.UI.InstanceShopUI")
require("GamePlay.Instance.UI.InstanceProcessUI")
require("GamePlay.Instance.UI.InstanceOfflineRewardUI")
require("GamePlay.Instance.UI.InstancePopUI")
require("GamePlay.Common.UI.FAQUI")
require("GamePlay.Common.UI.ShopInstantUI")
require("GamePlay.Instance.UI.InstanceAdUI")
require("GamePlay.PersonalDev.PersonalDevModel")
require("GamePlay.PersonalDev.UI.PersonalInfoUI")
require("GamePlay.PersonalDev.UI.PersonalAffairUI")
require("GamePlay.PersonalDev.UI.PersonalPromoteUI")
require("GamePlay.PersonalDev.UI.PersonalPromoteResultUI")
require("GamePlay.PersonalDev.UI.PersonalLvlUpUI")

require("CodeRefactoring.Actor.ActorManager")
require("CodeRefactoring.SpicalRoomManager")
require("CodeRefactoring.AI.InstanceAIBlackBoard")

require("GamePlay.Instance.UI.InstanceRewardUI2")
require("GamePlay.Instance.UI.InstanceRewardUI3")
require("GamePlay.Floors.PowerManager")
require("GamePlay.Instance.InstanceTaskManager")
require("GamePlay.Instance.InstanceFlyIconManager")
require("GamePlay.Common.UI.UIPopupManager")

require("GamePlay.Common.StoryLineManager")
require("GamePlay.Common.UI.StoryLineUI")
require("CodeRefactoring.Interactions.ElevatorManager")
require("GamePlay.Shop.BuyCar.BuyCarShopUI")
require("GamePlay.Common.UI.CommonRewardUI")

require("GamePlay.CycleInstance.CycleInstanceDataManager")
require("GameState.GameStateCycleInstance")

require("GamePlay.CycleInstance.Island.UI.SlotMachineUI")
require("GamePlay.CycleInstance.Island.UI.CycleInstanceSkillUI")
require("GamePlay.CycleInstance.Island.CycleIslandHeroManager")
require("GamePlay.CycleInstance.Island.UI.CycleIslandHeroUpgradeUI")
require("GamePlay.CycleInstance.Island.CycleIslandTaskManager")
require("GamePlay.CycleInstance.Island.UI.CycleIslandTaskUI")
require("GamePlay.CycleInstance.Island.UI.CycleIslandMainViewUI")
require("GamePlay.CycleInstance.Island.UI.CycleIslandTimeUI")
require("GamePlay.CycleInstance.Island.UI.CycleInstanceShopUI")
require("GamePlay.CycleInstance.Island.UI.CycleIslandViewUI")
require("GamePlay.CycleInstance.Island.UI.CycleInstanceMilepostUI")
require("GamePlay.CycleInstance.Island.UI.CycleIslandBuildingUI")
require("GamePlay.CycleInstance.Island.UI.CycleIslandSellUI")
require("GamePlay.CycleInstance.Island.UI.CycleInstanceRewardUI")
require("GamePlay.CycleInstance.Island.UI.CycleInstancePopUI")
require("GamePlay.CycleInstance.Island.AI.CycleInstanceAIBlackBoard")
require("GamePlay.CycleInstance.Island.UI.CycleIslandUnlockUI")
require("GameUtils.BigNumber")
require("GamePlay.CycleInstance.Island.UI.CycleIslandOfflineRewardUI")
require("GamePlay.CycleInstance.Island.UI.CycleInstanceAdUI")
require("GamePlay.Common.UI.ADChooseUI")

require("GamePlay.CycleInstance.Castle.UI.CycleCastleSkillUI")
require("GamePlay.CycleInstance.Castle.CycleCastleHeroManager")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleHeroUpgradeUI")
require("GamePlay.CycleInstance.Castle.CycleCastleTaskManager")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleTaskUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleMainViewUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleShopUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleViewUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleMilepostUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleBuildingUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleSellUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleRewardUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastlePopUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleUnlockUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleOfflineRewardUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleAdUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleSlotMachineUI")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleCutScreenUI")
require("GamePlay.CycleInstance.Castle.AI.CycleCastleAIBlackBoard")

require("GamePlay.CycleInstance.Castle.UI.CycleCastleRankUI")
require("GamePlay.CycleInstance.Castle.CycleCastleRankManager")
require("GamePlay.CycleInstance.Castle.UI.CycleCastleRankRewardUI")

require("GamePlay.CycleInstance.Toy.UI.CycleToySkillUI")
require("GamePlay.CycleInstance.Toy.CycleToyHeroManager")
require("GamePlay.CycleInstance.Toy.UI.CycleToyHeroUpgradeUI")
require("GamePlay.CycleInstance.Toy.CycleToyTaskManager")
require("GamePlay.CycleInstance.Toy.UI.CycleToyTaskUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyMainViewUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyShopUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyViewUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyMilepostUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyBuildingUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToySellUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyRewardUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyPopUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyUnlockUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyOfflineRewardUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyAdUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToySlotMachineUI")
require("GamePlay.CycleInstance.Toy.UI.CycleToyCutScreenUI")
require("GamePlay.CycleInstance.Toy.AI.CycleToyAIBlackBoard")
require("GamePlay.CycleInstance.Toy.UI.CycleToyBlueprintUI")
require("GamePlay.CycleInstance.Toy.CycleToyBluePrintManager")

require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubSkillUI")
require("GamePlay.CycleInstance.NightClub.CycleNightClubHeroManager")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubHeroUpgradeUI")
require("GamePlay.CycleInstance.NightClub.CycleNightClubTaskManager")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubTaskUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubMainViewUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubShopUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubViewUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubMilepostUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubBuildingUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubSellUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubRewardUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubPopUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubUnlockUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubOfflineRewardUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubAdUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubSlotMachineUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubCutScreenUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubBlueprintUI")
require("GamePlay.CycleInstance.NightClub.CycleNightClubBluePrintManager")

require("GamePlay.Common.UI.MonthCardUI")
require("GamePlay.Common.UI.FirstPurchaseUI")
require("GamePlay.Statistic.UI.StatisticUI")
require("GamePlay.Common.UI.SeasonPassUI")
require("GamePlay.Common.UI.SeasonPassPopupUI")
require("GamePlay.Deeplink.DeeplinkManager")
require("GamePlay.SeasonPass.SeasonPassManager")
require("GamePlay.SeasonPass.Minigame.CoinPusherManager")
require("GamePlay.SeasonPass.SeasonPassTaskManager")
require("GamePlay.Common.UI.SeasonPassPackUI")
require("GamePlay.CEOFeature.CEODataManager")
require("GamePlay.Common.UI.CEO.CEODeskUI")
require("GamePlay.Common.UI.CEO.CEOHiredUI")
require("GamePlay.Common.UI.CEO.CEOHiringUI")
require("GamePlay.Common.UI.CEO.CEOBoxPurchaseUI")
require("GamePlay.Common.UI.CEO.CEOChestPreviewUI")
require("GamePlay.Common.UI.CEO.CEOExcessConvertUI")
require("GamePlay.ClockOut.ClockOutDataManager")
require("GamePlay.Common.UI.ClockOut.ClockOutUI")
require("GamePlay.Common.UI.ClockOut.ClockOutPopupUI")

require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubSkillUI")
require("GamePlay.CycleInstance.NightClub.CycleNightClubHeroManager")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubHeroUpgradeUI")
require("GamePlay.CycleInstance.NightClub.CycleNightClubTaskManager")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubTaskUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubMainViewUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubShopUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubViewUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubMilepostUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubBuildingUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubSellUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubRewardUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubPopUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubUnlockUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubOfflineRewardUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubAdUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubSlotMachineUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubCutScreenUI")
require("GamePlay.CycleInstance.NightClub.AI.CycleNightClubAIBlackBoard")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubBlueprintUI")
require("GamePlay.CycleInstance.NightClub.CycleNightClubBluePrintManager")

require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubRankUI")
require("GamePlay.CycleInstance.NightClub.CycleNightClubRankManager")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubRankRewardUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubPiggyBankUI")
require("GamePlay.CycleInstance.NightClub.UI.CycleNightClubPiggyBankUIView")

function Update(dt)
    GameTimer:Update(dt)
    GameStateManager:Update(dt)
end

function OnPause()
    GameStateManager:OnPause()
end

function OnResume()
    GameStateManager:OnResume()
end