---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/7/1 14:13
---
local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local UIView = require("Framework.UI.View") -- 当工具类使用
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")

---@class CycleCastleWorkerWork:AIStateBase
---@field m_owner CycleCastleWorker
local CycleCastleWorkerWork = Class("CycleCastleWorkerWork",AIStateBase)

function CycleCastleWorkerWork:ctor()

end

function CycleCastleWorkerWork:OnEnter(...)
    local actor = self.m_owner
    local actorData = actor.data
    local stateMachine = actor.m_stateMachine
    -- 初始化在工作点
    if not actorData.workPosTr or actorData.workPosTr:IsNull() then
        actorData.furGO = CycleInstanceDataManager:GetCurrentModel():GetSceneRoomFurnitureGo(actorData.roomId ,1)
        actorData.workPosTr = UIView:GetTrans(actorData.furGO, "workPos_" .. actorData.furIndex) --工位点
        actorData.workFaceTr = UIView:GetTrans(actorData.workPosTr.gameObject, "face") --工位点朝向
        actorData.actPosTr = UIView:GetTrans(actorData.roomGO, "actionPos/actionPos_" .. actorData.furIndex) or actorData.workPosTr --工位点
        actorData.actFaceTr = UIView:GetTrans(actorData.roomGO, "actionPos/actionPos_" .. actorData.furIndex .. "/face") or actorData.workFaceTr --工位点

    end
    local face = actorData.actFaceTr
    
    actor.gameObject.transform.position = actorData.actPosTr.position
    UnityHelper.RotateTowards(actor.gameObject.transform, Vector3(face.position.x, actorData.actPosTr.position.y, face.position.z))

    -- 播放动画
    local furLevelCfg = CycleInstanceDataManager:GetCurrentModel():GetFurlevelConfigByRoomFurIndex(actorData.roomID, 1)
    actor:SetAnimator(PERSON_ACTION[furLevelCfg.action])
    -- 显示气泡
    actor:SetTheDisplayOfBubbles("product")

end

function CycleCastleWorkerWork:OnExit()

end

return CycleCastleWorkerWork