---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/6/27 15:11
---

---@class CycleIslandTaskUI
local CycleIslandTaskUI = GameTableDefine.CycleIslandTaskUI

local GameUIManager = GameTableDefine.GameUIManager
local ConfigMgr = GameTableDefine.ConfigMgr
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager

function CycleIslandTaskUI:GetView()
    self.m_view = GameUIManager:SafeOpenUI(ENUM_GAME_UITYPE.CYCLE_ISLAND_TASK_UI, self.m_view, require("GamePlay.CycleInstance.Island.UI.CycleIslandTaskUIView"), self, self.CloseView)
    return self.m_view
end

function CycleIslandTaskUI:CloseView()
    GameUIManager:CloseUI(ENUM_GAME_UITYPE.CYCLE_ISLAND_TASK_UI)
    self.m_view = nil
    collectgarbage("collect")
end

function CycleIslandTaskUI:OpenView()
    self:GetView()
    self.m_view:Invoke("Init")
end

---外界可调用关闭界面
function CycleIslandTaskUI:Exit()
    if self.m_view then
        self.m_view:Invoke("DestroyModeUIObject")
    end
end