---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/6/28 15:00
---

---@class CycleIslandMainViewUI
local CycleIslandMainViewUI = GameTableDefine.CycleIslandMainViewUI

local GameUIManager = GameTableDefine.GameUIManager
local ConfigMgr = GameTableDefine.ConfigMgr
local EventManager = require("Framework.Event.Manager")

function CycleIslandMainViewUI:GetView()
    self.m_view = GameUIManager:SafeOpenUI(ENUM_GAME_UITYPE.CYCLE_ISLAND_MAIN_VIEW_UI, self.m_view, require("GamePlay.CycleInstance.Island.UI.CycleIslandMainViewUIView"), self, self.CloseView)
    return self.m_view
end

function CycleIslandMainViewUI:CloseView()
    GameSDKs:TrackForeign("cy_instance_quit", { type = "返回主场景" })
    EventManager:DispatchEvent("BACK_TO_SCENE")
    GameTableDefine.CityMode:EnterDefaultBuiding()
    GameUIManager:CloseUI(ENUM_GAME_UITYPE.CYCLE_ISLAND_MAIN_VIEW_UI)
    self.m_view = nil
    collectgarbage("collect")
end

function CycleIslandMainViewUI:OpenUI()
    self:GetView()
end

function CycleIslandMainViewUI:Refresh()
    if self.m_view then
        self.m_view:Invoke("Show")
    end
end

function CycleIslandMainViewUI:Exit()
    if self.m_view then
        self.m_view:Invoke("DestroyModeUIObject")
    end
end


function CycleIslandMainViewUI:CallNotify(notifyType,...)
    if self.m_view then
        local args = {...}
        self.m_view:Invoke("CallNotify",notifyType,...)
    end
end

function CycleIslandMainViewUI:SetAchievementActive(active)
    if self.m_view then
        self.m_view:Invoke("SetAchievementActive",active)
    end
end

function CycleIslandMainViewUI:SetEventActive(active)
    if self.m_view then
        self.m_view:Invoke("SetEventActive",active)
    end
end

function CycleIslandMainViewUI:SetEventIAAActive(active)
    if self.m_view then
        self.m_view:Invoke("SetEventIAAActive",active)
    end
end

function CycleIslandMainViewUI:SetPackActive(active)
    if self.m_view then
        self.m_view:Invoke("SetPackActive",active)
    end
end

--礼包刷新接口
function CycleIslandMainViewUI:RefreshPackButton()
    if self.m_view and self.m_view.RefreshPackButton then
        self.m_view:RefreshPackButton()
    end
end

---播放里程碑分数奖励动画
function CycleIslandMainViewUI:PlayMilestoneAnim()
    if self.m_view then
        --self.m_view:PlayMilestoneAnim()
    end
end