---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by .
--- DateTime: 2024/10/28 17:27
---

-- 创建一个事件分发器
EventDispatcher = {}

local EventDispatcher = EventDispatcher

-- 存储事件和监听器的映射表
EventDispatcher.events = {}

-- 注册事件监听器
function EventDispatcher:RegEvent(eventName, listener)
    if not self.events[eventName] then
        self.events[eventName] = {}
    end
    table.insert(self.events[eventName], listener)
end

-- 移除事件监听器
function EventDispatcher:UnRegEvent(eventName, listener)
    if self.events[eventName] then
        for i, registeredListener in ipairs(self.events[eventName]) do
            if registeredListener == listener then
                table.remove(self.events[eventName], i)
                break
            end
        end
    end
end

-- 分发事件
function EventDispatcher:TriggerEvent(eventName, ...)
    if self.events[eventName] then
        -- 倒序遍历监听者列表
        for i = #self.events[eventName], 1, -1 do
            local listener = self.events[eventName][i]
            listener(...)
        end
    end
end

-- 返回事件分发器
return EventDispatcher