---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2023/8/31 17:20
---

local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
---@class EventDiamonderWaiting:AIStateBase
---@field m_owner EventDiamonderNew
local EventDiamonderWaiting = Class("EventDiamonderWaiting",AIStateBase)

local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local MainUI = GameTableDefine.MainUI
local FloorMode = GameTableDefine.FloorMode
local Event004UI = GameTableDefine.Event004UI
local EventManager = require("Framework.Event.Manager")

function EventDiamonderWaiting:ctor()
    self.m_speed = nil
end

function EventDiamonderWaiting:OnEnter()
    self.m_owner:SetAnimator(PERSON_ACTION.DANCE)

    self.m_owner:InitFloatUIView(self.m_owner.m_eventId)
    MainUI:SetEventSponsorHint(true, self.m_owner.m_eventId)
    EventManager:DispatchEvent("EventDiamonder_come",self.m_owner.m_go)

    FloorMode:GetScene():SetButtonClickHandler(self.m_owner.m_go, function()
        Event004UI:ShowPanel()
    end)
end

function EventDiamonderWaiting:Event(msg,params)
    --来的路上要结束
    if msg == self.m_owner.EVENT_LEAVE_SCENE then
        MainUI:SetEventSponsorHint(false,  self.m_owner.m_eventId)
        EventManager:DispatchEvent("EventDiamonder_leave")

        self.m_owner.m_stateMachine:ChangeState(ActorDefine.State.EventDiamonderLeaving)
    end
end

function EventDiamonderWaiting:OnExit()
    self.m_owner:RemoveFloatUIView()
    FloorMode:GetScene():SetButtonClickHandler(self.m_owner.m_go, nil)
end

return EventDiamonderWaiting