---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2023/9/12 9:56
---

local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
---@class EventChatterWaiting:AIStateBase
---@field m_owner EventChatterNew
local EventChatterWaiting = Class("EventChatterWaiting",AIStateBase)

local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")

function EventChatterWaiting:ctor()
    self.m_speed = nil
end

function EventChatterWaiting:OnEnter()
    self.m_owner:SetAnimator(PERSON_ACTION.IDLE)

    self.m_owner:InitChatUIView(self.m_owner.m_conditionId)
end

function EventChatterWaiting:Event(msg,params)
    --来的路上要结束
    if msg == self.m_owner.EVENT_LEAVE_SCENE then
        self.m_owner:AddFlag(ActorDefine.Flag.FLAG_LEAVE_SCENE)
        self.m_owner.m_stateMachine:ChangeState(ActorDefine.State.EventChatterLeaving)
    end
end

function EventChatterWaiting:OnExit()
    self.m_owner:RemoveFloatUIView()
end

return EventChatterWaiting