SoundConst = {
    MUSIC_BG_BUIDLING_OUT            = "Assets/Res/Audio/bgm_mainscene.mp3",
    MUSIC_BG_BUIDLING_IN             = "Assets/Res/Audio/bgm_mainscene.mp3",

    ROOM1_SFX                        = "Assets/Res/Audio/room1_sfx.ogg",
    ROOM2_SFX                        = "Assets/Res/Audio/room2_sfx.ogg",
    ROOM3_SFX                        = "Assets/Res/Audio/room3_sfx.ogg",
    ROOM4_SFX                        = "Assets/Res/Audio/room4_sfx.ogg",
    ROOM5_SFX                        = "Assets/Res/Audio/room5_sfx.ogg",
    ROOM6_SFX                        = "Assets/Res/Audio/room6_sfx.ogg",
    ROOM7_SFX                        = "Assets/Res/Audio/room7_sfx.ogg",
    ROOM8_SFX                        = "Assets/Res/Audio/room8_sfx.ogg",
    ROOM9_SFX                        = "Assets/Res/Audio/room9_sfx.ogg",
    ROOM10_SFX                       = "Assets/Res/Audio/room10_sfx.ogg",

    FACTORY1_SFX                     ="Assets/Res/Audio/workshop1_sfx.ogg",
    FACTORY2_SFX                     ="Assets/Res/Audio/workshop2_sfx.ogg",
    FACTORY3_SFX                     ="Assets/Res/Audio/workshop3_sfx.ogg",
    FACTORY4_SFX                     ="Assets/Res/Audio/workshop4_sfx.ogg",

    BUY_SFX                          = "Assets/Res/Audio/SFX_buy.ogg",
    BUTTON_CLICK_SFX                 = "Assets/Res/Audio/SFX_click.ogg",
    BUTTONEX_CLICK_SFX                 = "Assets/Res/Audio/btnex_click.ogg",
    CASH_EARN                        = "Assets/Res/Audio/SFX_income.ogg",

    MainScene_BGM                      = "Assets/Res/Audio/bgm_mainscene.mp3",
    Carshop_BGM                        = "Assets/Res/Audio/bgm_carshop.mp3",
    House_BGM                          = "Assets/Res/Audio/bgm_house.mp3",
    Factory_BGM                        = "Assets/Res/Audio/bgm_factory.mp3",

    Citymap_BGM                        = "Assets/Res/Audio/bgm_CityMap.mp3",
    Christmas_BGM                      = "Assets/Res/Audio/christmas.mp3",

    WHEEL_SHING                        = "Assets/Res/Audio/wheel_burst_sfx.wav",
    WHEEL_ROTATE                       = "Assets/Res/Audio/wheel_spin_sfx.wav",
    WHEEL_SHING_ROTATE                 = "Assets/Res/Audio/wheel_spin_sfx.wav",

    bgm_instance_1                       = "Assets/Res/Audio/bgm_instance_1.mp3",
    bgm_instance_2                       = "Assets/Res/Audio/bgm_instance_2.mp3",
    bgm_instance_3                       = "Assets/Res/Audio/bgm_instance_3.mp3",
    bgm_instance_5                       = "Assets/Res/Audio/bgm_instance_5.mp3",
    bgm_instance_6                       = "Assets/Res/Audio/bgm_instance_6.mp3",
    bgm_instance_7_1                     = "Assets/Res/Audio/bgm_instance_7_1.mp3",
    bgm_instance_7_2                     = "Assets/Res/Audio/bgm_instance_7_2.mp3",
    bgm_instance_7_3                     = "Assets/Res/Audio/bgm_instance_7_3.mp3",
    slot_bgm_instance_5                  = "Assets/Res/Audio/slot_bgm_instance_5.mp3",
    instance_3_slot_bgm                  = "Assets/Res/Audio/instance_3_slot_bgm.ogg",
    instance_4_slot_bgm                  = "Assets/Res/Audio/instance_4_slot_bgm.ogg",


    instance_1_Sawmill_sfx              = "Assets/Res/Audio/instance_1_Sawmill_sfx.ogg",
    instance_1_LumberMill_sfx           = "Assets/Res/Audio/instance_1_LumberMill_sfx.ogg",
    instance_1_WoodWorkshop_sfx         = "Assets/Res/Audio/instance_1_WoodWorkshop_sfx.ogg",
    instance_1_Quarry_sfx               = "Assets/Res/Audio/instance_1_Quarry_sfx.ogg",
    instance_1_StoneMill_sfx            = "Assets/Res/Audio/instance_1_StoneMill_sfx.ogg",
    instance_1_StoneWorkshop_sfx        = "Assets/Res/Audio/instance_1_StoneWorkshop_sfx.ogg",
    instance_1_Dormitory_sfx            = "Assets/Res/Audio/instance_1_Dormitory_sfx.ogg",
    instance_1_Canteen_sfx              = "Assets/Res/Audio/instance_1_Canteen_sfx.ogg",
    instance_1_Port_sfx                 = "Assets/Res/Audio/instance_1_Port_sfx.ogg",

    instance_2_PlantRoom_sfx            ="Assets/Res/Audio/instance_2_PlantRoom_sfx.ogg",
    instance_2_Workshop_sfx             ="Assets/Res/Audio/instance_2_Workshop_sfx.ogg",
    instance_2_CandyRoom_sfx            ="Assets/Res/Audio/instance_2_CandyRoom_sfx.ogg",
    instance_2_Clinic_sfx               ="Assets/Res/Audio/instance_2_Clinic_sfx.ogg",
    instance_2_Laboratory_sfx           ="Assets/Res/Audio/instance_2_Laboratory_sfx.ogg",
    instance_2_AlchemyRoom_sfx          ="Assets/Res/Audio/instance_2_AlchemyRoom_sfx.ogg",
    instance_2_Cemetery_sfx             ="Assets/Res/Audio/instance_2_Cemetery_sfx.ogg",
    instance_2_DinningRoom_sfx          ="Assets/Res/Audio/instance_2_DinningRoom_sfx.ogg",
    instance_2_Stable_sfx               ="Assets/Res/Audio/instance_2_Stable_sfx.ogg",

    instance_3_BeastPen_sfx            ="Assets/Res/Audio/instance_3_BeastPen_sfx.ogg",
    instance_3_CarvingHouse_sfx        ="Assets/Res/Audio/instance_3_CarvingHouse_sfx.ogg",
    instance_3_Chaiwu_sfx              ="Assets/Res/Audio/instance_3_Chaiwu_sfx.ogg",
    instance_3_ChristmasTreeHouse_sfx  ="Assets/Res/Audio/instance_3_ChristmasTreeHouse_sfx.ogg",
    instance_3_CrystalBallRoom_sfx     ="Assets/Res/Audio/instance_3_CrystalBallRoom_sfx.ogg",
    instance_3_DinningRoom_sfx         ="Assets/Res/Audio/instance_3_DinningRoom_sfx.ogg",
    instance_3_Dormitory_sfx           ="Assets/Res/Audio/instance_3_Dormitory_sfx.ogg",
    instance_3_GiftHouse_sfx           ="Assets/Res/Audio/instance_3_GiftHouse_sfx.ogg",
    instance_3_Stable_sfx              ="Assets/Res/Audio/instance_3_TailorHouse_sfx.ogg",
    instance_3_TailorHouse_sfx         ="Assets/Res/Audio/instance_3_TailorHouse_sfx.ogg",

    instance_2_Wolf1_sfx            ="Assets/Res/Audio/instance_2_Wolf1_sfx.ogg",
    instance_2_Wolf2_sfx            ="Assets/Res/Audio/instance_2_Wolf2_sfx.ogg",
    instance_2_Wolf3_sfx            ="Assets/Res/Audio/instance_2_Wolf3_sfx.ogg",
    instance_2_Mundo1_sfx            ="Assets/Res/Audio/instance_2_Mundo1_sfx.ogg",
    instance_2_Mundo2_sfx            ="Assets/Res/Audio/instance_2_Mundo2_sfx.ogg",
    instance_2_Mundo3_sfx            ="Assets/Res/Audio/instance_2_Mundo3_sfx.ogg",
    instance_2_Witch1_sfx            ="Assets/Res/Audio/instance_2_Witch1_sfx.ogg",
    instance_2_Witch2_sfx            ="Assets/Res/Audio/instance_2_Witch2_sfx.ogg",
    instance_2_Witch3_sfx            ="Assets/Res/Audio/instance_2_Witch3_sfx.ogg",
    instance_2_Ghost1_sfx            ="Assets/Res/Audio/instance_2_Ghost1_sfx.ogg",
    instance_2_Ghost2_sfx            ="Assets/Res/Audio/instance_2_Ghost2_sfx.ogg",
    instance_2_Ghost3_sfx            ="Assets/Res/Audio/instance_2_Ghost3_sfx.ogg",
    instance_5_Canteen_sfx            ="Assets/Res/Audio/instance_5_Canteen_sfx.ogg",

    instance_3_Barbie_sfx           ="Assets/Res/Audio/instance_3_Barbie_sfx.ogg",
    instance_3_Bear_sfx           ="Assets/Res/Audio/instance_3_Bear_sfx.ogg",
    instance_3_Car_sfx           ="Assets/Res/Audio/instance_3_Car_sfx.ogg",
    instance_3_Gamebox_sfx           ="Assets/Res/Audio/instance_3_Gamebox_sfx.ogg",
    instance_3_Godzilla_sfx           ="Assets/Res/Audio/instance_3_Godzilla_sfx.ogg",
    instance_3_Gun_sfx           ="Assets/Res/Audio/instance_3_Gun_sfx.ogg",
    instance_3_Plane_sfx           ="Assets/Res/Audio/instance_3_Plane_sfx.ogg",
    instance_3_Starwar_sfx           ="Assets/Res/Audio/instance_3_Starwar_sfx.ogg",
    instance_3_Train_sfx           ="Assets/Res/Audio/instance_3_Train_sfx.ogg",
    SFX_Toy_Upgrade           ="Assets/Res/Audio/SFX_Toy_Upgrade.ogg",
    instance_3_Build_sfx           ="Assets/Res/Audio/instance_3_Build_sfx.ogg",
    SFX_income           ="Assets/Res/Audio/SFX_income.ogg",

    instance_4_Booth_sfx           ="Assets/Res/Audio/instance_4_Booth_sfx.ogg",
    instance_4_DanceFloor_sfx           ="Assets/Res/Audio/instance_4_DanceFloor_sfx.ogg",
    instance_4_DJMixer_sfx           ="Assets/Res/Audio/instance_4_DJMixer_sfx.ogg",
    instance_4_SmokeRoom_sfx           ="Assets/Res/Audio/instance_4_SmokeRoom_sfx.ogg",
    instance_4_HookahRoom_sfx           ="Assets/Res/Audio/instance_4_HookahRoom_sfx.ogg",
    instance_4_DiceRoom_sfx           ="Assets/Res/Audio/instance_4_DiceRoom_sfx.ogg",
    instance_4_PokerRoom_sfx           ="Assets/Res/Audio/instance_4_PokerRoom_sfx.ogg",
    instance_4_RouletteRoom_sfx           ="Assets/Res/Audio/instance_4_RouletteRoom_sfx.ogg",
    instance_4_GirlieRoom_sfx           ="Assets/Res/Audio/instance_4_GirlieRoom_sfx.ogg",

    FOOTBALL_BGM                       = "Assets/Res/Audio/bgm_fc.mp3",
    FOOTBALL_IN_GAME                   = "Assets/Res/Audio/bgm_fc_match.mp3",
    
    SEASONPASS_TUIBIJI_TUIBI            = "Assets/Res/Audio/sfx_pass_tuibi.ogg"
}

-- 房间音效
SoundConst.ROOM_SFX = {
    [1] = SoundConst.ROOM1_SFX,
    [2] = SoundConst.ROOM2_SFX,
    [3] = SoundConst.ROOM3_SFX,
    [4] = SoundConst.ROOM4_SFX,
    [5] = SoundConst.ROOM5_SFX,
    [6] = SoundConst.ROOM6_SFX,
    [7] = SoundConst.ROOM7_SFX,
    [8] = SoundConst.ROOM8_SFX,
    [9] = SoundConst.ROOM9_SFX,
    [10] = SoundConst.ROOM10_SFX,
}


