local config_equipment = {
	[1] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_1_DESC",
		["icon"] = "icon_equipment_001",
		["id"] = 1,
		["name"] = "TXT_EQUIPMENT_1_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_001",
		["sex"] = 3,
		["shopId"] = 1107,
		["type"] = 1,
	}
	,
	[2] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_2_DESC",
		["icon"] = "icon_equipment_002",
		["id"] = 2,
		["name"] = "TXT_EQUIPMENT_2_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_002",
		["sex"] = 3,
		["shopId"] = 1108,
		["type"] = 1,
	}
	,
	[3] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_3_DESC",
		["icon"] = "icon_equipment_003",
		["id"] = 3,
		["name"] = "TXT_EQUIPMENT_3_NAME",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_001",
		["sex"] = 3,
		["shopId"] = 1109,
		["type"] = 1,
	}
	,
	[4] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_4_DESC",
		["icon"] = "icon_equipment_004",
		["id"] = 4,
		["name"] = "TXT_EQUIPMENT_4_NAME",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_002",
		["sex"] = 3,
		["shopId"] = 1110,
		["type"] = 1,
	}
	,
	[5] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_5_DESC",
		["icon"] = "icon_equipment_005",
		["id"] = 5,
		["name"] = "TXT_EQUIPMENT_5_NAME",
		["part"] = 0,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["prefab"] = "Costume_001",
		["sex"] = 3,
		["shopId"] = 1111,
		["type"] = 3,
	}
	,
	[6] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_6_DESC",
		["icon"] = "icon_equipment_006",
		["id"] = 6,
		["name"] = "TXT_EQUIPMENT_6_NAME",
		["part"] = 0,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["prefab"] = "Costume_002",
		["sex"] = 3,
		["shopId"] = 1112,
		["type"] = 3,
	}
	,
	[7] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_7_DESC",
		["icon"] = "icon_equipment_007",
		["id"] = 7,
		["name"] = "TXT_EQUIPMENT_7_NAME",
		["part"] = 0,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["prefab"] = "Costume_003",
		["sex"] = 3,
		["shopId"] = 1113,
		["type"] = 3,
	}
	,
	[8] = {
		["default"] = 2,
		["id"] = 8,
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_Baoan_F",
		["sex"] = 3,
		["type"] = 3,
	}
	,
	[9] = {
		["default"] = 2,
		["id"] = 9,
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_Baoan_M",
		["sex"] = 3,
		["type"] = 3,
	}
	,
	[10] = {
		["default"] = 2,
		["id"] = 10,
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_Ghost_M",
		["sex"] = 3,
		["type"] = 3,
	}
	,
	[11] = {
		["default"] = 2,
		["id"] = 11,
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_Ghost_F",
		["sex"] = 3,
		["type"] = 3,
	}
	,
	[12] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_8_DESC",
		["icon"] = "icon_equipment_008",
		["id"] = 12,
		["name"] = "TXT_EQUIPMENT_8_NAME",
		["part"] = 0,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["prefab"] = "Costume_004",
		["sex"] = 1,
		["shopId"] = 1116,
		["type"] = 3,
	}
	,
	[13] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_9_DESC",
		["icon"] = "icon_equipment_009",
		["id"] = 13,
		["name"] = "TXT_EQUIPMENT_9_NAME",
		["part"] = 0,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["prefab"] = "Costume_005",
		["sex"] = 2,
		["shopId"] = 1117,
		["type"] = 3,
	}
	,
	[14] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_10_DESC",
		["icon"] = "icon_equipment_010",
		["id"] = 14,
		["name"] = "TXT_EQUIPMENT_10_NAME",
		["part"] = 0,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["prefab"] = "Costume_006",
		["sex"] = 3,
		["shopId"] = 1118,
		["type"] = 3,
	}
	,
	[15] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_11_DESC",
		["icon"] = "icon_equipment_011",
		["id"] = 15,
		["name"] = "TXT_EQUIPMENT_11_NAME",
		["part"] = 0,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["prefab"] = "Costume_007",
		["sex"] = 1,
		["shopId"] = 1119,
		["type"] = 3,
	}
	,
	[16] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_12_DESC",
		["icon"] = "icon_equipment_012",
		["id"] = 16,
		["name"] = "TXT_EQUIPMENT_12_NAME",
		["part"] = 0,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["prefab"] = "Costume_008",
		["sex"] = 2,
		["shopId"] = 1120,
		["type"] = 3,
	}
	,
	[17] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_13_DESC",
		["icon"] = "icon_equipment_013",
		["id"] = 17,
		["name"] = "TXT_EQUIPMENT_13_NAME",
		["part"] = 0,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["prefab"] = "Costume_009",
		["sex"] = 3,
		["shopId"] = 1121,
		["type"] = 3,
	}
	,
	[18] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_14_DESC",
		["icon"] = "icon_equipment_014",
		["id"] = 18,
		["name"] = "TXT_EQUIPMENT_14_NAME",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_003",
		["sex"] = 3,
		["shopId"] = 1122,
		["type"] = 1,
	}
	,
	[19] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_15_DESC",
		["icon"] = "icon_equipment_015",
		["id"] = 19,
		["name"] = "TXT_EQUIPMENT_15_NAME",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_004",
		["sex"] = 3,
		["shopId"] = 1123,
		["type"] = 1,
	}
	,
	[20] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_16_DESC",
		["icon"] = "icon_equipment_016",
		["id"] = 20,
		["name"] = "TXT_EQUIPMENT_16_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_003",
		["sex"] = 3,
		["shopId"] = 1124,
		["type"] = 1,
	}
	,
	[21] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_17_DESC",
		["icon"] = "icon_equipment_017",
		["id"] = 21,
		["name"] = "TXT_EQUIPMENT_17_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_004",
		["sex"] = 3,
		["shopId"] = 1125,
		["type"] = 1,
	}
	,
	[22] = {
		["default"] = 2,
		["id"] = 22,
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Eros_wings",
		["sex"] = 3,
		["type"] = 3,
	}
	,
	[23] = {
		["default"] = 2,
		["id"] = 23,
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Eros_crown",
		["sex"] = 3,
		["type"] = 3,
	}
	,
	[24] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_19_DESC",
		["icon"] = "icon_equipment_019",
		["id"] = 24,
		["name"] = "TXT_EQUIPMENT_19_NAME",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_005",
		["sex"] = 3,
		["shopId"] = 1147,
		["type"] = 1,
	}
	,
	[25] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_18_DESC",
		["icon"] = "icon_equipment_018",
		["id"] = 25,
		["name"] = "TXT_EQUIPMENT_18_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_005",
		["sex"] = 3,
		["shopId"] = 1148,
		["type"] = 1,
	}
	,
	[26] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_20_DESC",
		["icon"] = "icon_equipment_020",
		["id"] = 26,
		["name"] = "TXT_EQUIPMENT_20_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_006",
		["sex"] = 3,
		["shopId"] = 1152,
		["type"] = 1,
	}
	,
	[27] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_21_DESC",
		["icon"] = "icon_equipment_021",
		["id"] = 27,
		["name"] = "TXT_EQUIPMENT_21_NAME",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_006",
		["sex"] = 3,
		["shopId"] = 1153,
		["type"] = 1,
	}
	,
	[28] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_22_DESC",
		["icon"] = "icon_equipment_022",
		["id"] = 28,
		["name"] = "TXT_EQUIPMENT_22_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_007",
		["sex"] = 3,
		["shopId"] = 1163,
		["type"] = 1,
	}
	,
	[29] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_23_DESC",
		["icon"] = "icon_equipment_023",
		["id"] = 29,
		["name"] = "TXT_EQUIPMENT_23_NAME",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_007",
		["sex"] = 3,
		["shopId"] = 1164,
		["type"] = 1,
	}
	,
	[41] = {
		["default"] = 1,
		["desc"] = "TXT_INSTANCE_Equipment_1_DESC",
		["icon"] = "icon_equipment_035",
		["id"] = 41,
		["name"] = "TXT_INSTANCE_Equipment_1",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_008",
		["sex"] = 3,
		["shopId"] = 1233,
		["type"] = 1,
	}
	,
	[42] = {
		["default"] = 1,
		["desc"] = "TXT_INSTANCE_Equipment_2_DESC",
		["icon"] = "icon_equipment_036",
		["id"] = 42,
		["name"] = "TXT_INSTANCE_Equipment_2",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_009",
		["sex"] = 3,
		["shopId"] = 1234,
		["type"] = 1,
	}
	,
	[43] = {
		["default"] = 1,
		["desc"] = "TXT_INSTANCE_Equipment_3_DESC",
		["icon"] = "icon_equipment_037",
		["id"] = 43,
		["name"] = "TXT_INSTANCE_Equipment_3",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_008",
		["sex"] = 3,
		["shopId"] = 1235,
		["type"] = 1,
	}
	,
	[44] = {
		["default"] = 1,
		["desc"] = "TXT_INSTANCE_Equipment_4_DESC",
		["icon"] = "icon_equipment_038",
		["id"] = 44,
		["name"] = "TXT_INSTANCE_Equipment_4",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_009",
		["sex"] = 3,
		["shopId"] = 1236,
		["type"] = 1,
	}
	,
	[45] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_39_DESC",
		["icon"] = "icon_equipment_039",
		["id"] = 45,
		["name"] = "TXT_EQUIPMENT_39_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_010",
		["sex"] = 3,
		["shopId"] = 1237,
		["type"] = 1,
	}
	,
	[46] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_40_DESC",
		["icon"] = "icon_equipment_040",
		["id"] = 46,
		["name"] = "TXT_EQUIPMENT_40_NAME",
		["part"] = 2,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/backpackPos",
		["prefab"] = "Backpack_010",
		["sex"] = 3,
		["shopId"] = 1238,
		["type"] = 1,
	}
	,
	[47] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_41_DESC",
		["icon"] = "icon_equipment_041",
		["id"] = 47,
		["name"] = "TXT_EQUIPMENT_41_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_011",
		["sex"] = 3,
		["shopId"] = 1262,
		["type"] = 1,
	}
	,
	[48] = {
		["default"] = 1,
		["desc"] = "TXT_EQUIPMENT_42_DESC",
		["icon"] = "icon_equipment_042",
		["id"] = 48,
		["name"] = "TXT_EQUIPMENT_42_NAME",
		["part"] = 1,
		["path"] = "Assets/Res/Prefabs/Equipment/",
		["pos"] = "mixamorig:Spine/mixamorig:Spine1/mixamorig:Spine2/mixamorig:Neck/mixamorig:Head/mixamorig:HeadTop_End/hatPos",
		["prefab"] = "Hat_012",
		["sex"] = 3,
		["shopId"] = 1263,
		["type"] = 1,
	}
	,
}
return config_equipment