local config_pass_task = {
	["tuibiji"] = {
		["DayTasks"] = {
			[1] = {
				["group"] = 1,
				["id"] = 1,
				["is_goto"] = 0,
				["passType_id"] = "tuibiji",
				["reward"] = 20,
				["sequence"] = 0,
				["task_content"] = "观看广告1次",
				["task_desc"] = "TXT_PASS_TASK_1",
				["task_icon"] = "icon_pass_task_cnYear_advertisement",
				["threhold"] = 1,
				["type"] = 0,
			}
			,
			[2] = {
				["group"] = 2,
				["id"] = 2,
				["is_goto"] = 0,
				["passType_id"] = "tuibiji",
				["reward"] = 20,
				["sequence"] = 0,
				["task_content"] = "每日登录游戏",
				["task_desc"] = "TXT_PASS_TASK_2",
				["task_icon"] = "icon_pass_task_cnYear_signIn",
				["threhold"] = 1,
				["type"] = 0,
			}
			,
			[3] = {
				["group"] = 3,
				["id"] = 3,
				["is_goto"] = 1,
				["passType_id"] = "tuibiji",
				["reward"] = 20,
				["sequence"] = 0,
				["task_content"] = "参与1次转盘抽奖",
				["task_desc"] = "TXT_PASS_TASK_3",
				["task_icon"] = "icon_pass_task_cnYear_turntable",
				["threhold"] = 1,
				["type"] = 0,
			}
			,
			[4] = {
				["group"] = 4,
				["id"] = 4,
				["is_goto"] = 0,
				["passType_id"] = "tuibiji",
				["reward"] = 20,
				["sequence"] = 0,
				["task_content"] = "升级1次公司",
				["task_desc"] = "TXT_PASS_TASK_4",
				["task_icon"] = "icon_pass_task_cnYear_upgrades",
				["threhold"] = 1,
				["type"] = 0,
			}
			,
			[5] = {
				["group"] = 5,
				["id"] = 5,
				["is_goto"] = 1,
				["passType_id"] = "tuibiji",
				["reward"] = 20,
				["sequence"] = 0,
				["task_content"] = "升级/购买1次房间设施",
				["task_desc"] = "TXT_PASS_TASK_5",
				["task_icon"] = "icon_pass_task_cnYear_build",
				["threhold"] = 1,
				["type"] = 0,
			}
			,
		}
		,
		["WeekTasks"] = {
			[1] = {
				[1] = {
					["group"] = 1,
					["id"] = 6,
					["is_goto"] = 0,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 1,
					["task_content"] = "花费50个钻石",
					["task_desc"] = "TXT_PASS_TASK_6",
					["task_icon"] = "icon_pass_task_cnYear_diamond",
					["threhold"] = 50,
					["type"] = 1,
				}
				,
				[2] = {
					["group"] = 1,
					["id"] = 7,
					["is_goto"] = 0,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 2,
					["task_content"] = "花费100个钻石",
					["task_desc"] = "TXT_PASS_TASK_6",
					["task_icon"] = "icon_pass_task_cnYear_diamond",
					["threhold"] = 100,
					["type"] = 1,
				}
				,
				[3] = {
					["group"] = 1,
					["id"] = 8,
					["is_goto"] = 0,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 3,
					["task_content"] = "花费500个钻石",
					["task_desc"] = "TXT_PASS_TASK_6",
					["task_icon"] = "icon_pass_task_cnYear_diamond",
					["threhold"] = 500,
					["type"] = 1,
				}
				,
				[4] = {
					["group"] = 1,
					["id"] = 9,
					["is_goto"] = 0,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 4,
					["task_content"] = "花费1000个钻石",
					["task_desc"] = "TXT_PASS_TASK_6",
					["task_icon"] = "icon_pass_task_cnYear_diamond",
					["threhold"] = 1000,
					["type"] = 1,
				}
				,
				[5] = {
					["group"] = 1,
					["id"] = 10,
					["is_goto"] = 0,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 5,
					["task_content"] = "花费2000个钻石",
					["task_desc"] = "TXT_PASS_TASK_6",
					["task_icon"] = "icon_pass_task_cnYear_diamond",
					["threhold"] = 2000,
					["type"] = 1,
				}
				,
				[6] = {
					["group"] = 1,
					["id"] = 11,
					["is_goto"] = 0,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 6,
					["task_content"] = "花费5000个钻石",
					["task_desc"] = "TXT_PASS_TASK_6",
					["task_icon"] = "icon_pass_task_cnYear_diamond",
					["threhold"] = 5000,
					["type"] = 1,
				}
				,
			}
			,
			[2] = {
				[1] = {
					["group"] = 2,
					["id"] = 12,
					["is_goto"] = 1,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 1,
					["task_content"] = "使用1张玩法门票",
					["task_desc"] = "TXT_PASS_TASK_7",
					["task_icon"] = "icon_pass_task_cnYear_game",
					["threhold"] = 1,
					["type"] = 1,
				}
				,
				[2] = {
					["group"] = 2,
					["id"] = 13,
					["is_goto"] = 1,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 2,
					["task_content"] = "使用10张玩法门票",
					["task_desc"] = "TXT_PASS_TASK_7",
					["task_icon"] = "icon_pass_task_cnYear_game",
					["threhold"] = 10,
					["type"] = 1,
				}
				,
				[3] = {
					["group"] = 2,
					["id"] = 14,
					["is_goto"] = 1,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 3,
					["task_content"] = "使用20张玩法门票",
					["task_desc"] = "TXT_PASS_TASK_7",
					["task_icon"] = "icon_pass_task_cnYear_game",
					["threhold"] = 20,
					["type"] = 1,
				}
				,
				[4] = {
					["group"] = 2,
					["id"] = 15,
					["is_goto"] = 1,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 4,
					["task_content"] = "使用30张玩法门票",
					["task_desc"] = "TXT_PASS_TASK_7",
					["task_icon"] = "icon_pass_task_cnYear_game",
					["threhold"] = 30,
					["type"] = 1,
				}
				,
				[5] = {
					["group"] = 2,
					["id"] = 16,
					["is_goto"] = 1,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 5,
					["task_content"] = "使用40张玩法门票",
					["task_desc"] = "TXT_PASS_TASK_7",
					["task_icon"] = "icon_pass_task_cnYear_game",
					["threhold"] = 40,
					["type"] = 1,
				}
				,
				[6] = {
					["group"] = 2,
					["id"] = 17,
					["is_goto"] = 1,
					["passType_id"] = "tuibiji",
					["reward"] = 100,
					["sequence"] = 6,
					["task_content"] = "使用50张玩法门票",
					["task_desc"] = "TXT_PASS_TASK_7",
					["task_icon"] = "icon_pass_task_cnYear_game",
					["threhold"] = 50,
					["type"] = 1,
				}
				,
			}
			,
		}
		,
	}
	,
}
return config_pass_task