local config_cy_instance_blueprint = {
	[6] = {
		[25] = {
			[0] = {
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "icon_toy_blazeShooter_1",
				["icon_head"] = "icon_Toyhalf_gun_1",
				["id"] = 1,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gunLow_01",
				["mile_buff"] = 1,
				["model"] = "SF_Prop_gun_01",
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY3_Product_1",
				["res_id"] = 25,
				["room_id"] = 1034,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["cost"] = 1,
				["cost_type"] = 2,
				["icon"] = "icon_toy_blazeShooter_2",
				["icon_head"] = "icon_Toyhalf_gun_2",
				["id"] = 2,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gunLow_02",
				["mile_buff"] = 5,
				["model"] = "SF_Prop_gun_02",
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY3_Product_1",
				["res_id"] = 25,
				["room_id"] = 1034,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["cost"] = 1,
				["cost_type"] = 3,
				["icon"] = "icon_toy_blazeShooter_3",
				["icon_head"] = "icon_Toyhalf_gun_3",
				["id"] = 3,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gunLow_03",
				["mile_buff"] = 25,
				["model"] = "SF_Prop_gun_03",
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY3_Product_1",
				["res_id"] = 25,
				["room_id"] = 1034,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["cost"] = 1,
				["cost_type"] = 4,
				["icon"] = "icon_toy_blazeShooter_4",
				["icon_head"] = "icon_Toyhalf_gun_4",
				["id"] = 4,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gunLow_04",
				["mile_buff"] = 125,
				["model"] = "SF_Prop_gun_04",
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY3_Product_1",
				["res_id"] = 25,
				["room_id"] = 1034,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["cost"] = 2,
				["cost_type"] = 4,
				["icon"] = "icon_toy_blazeShooter_5",
				["icon_head"] = "icon_Toyhalf_gun_5",
				["id"] = 5,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gunLow_05",
				["mile_buff"] = 625,
				["model"] = "SF_Prop_gun_05",
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY3_Product_1",
				["res_id"] = 25,
				["room_id"] = 1034,
				["starLevel"] = 4,
			}
			,
		}
		,
		[26] = {
			[0] = {
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "icon_toy_cuddleBear_1",
				["icon_head"] = "icon_Toyhalf_bear_1",
				["id"] = 6,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_bearLow_01",
				["mile_buff"] = 1,
				["model"] = "SF_Prop_bear_01",
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY3_Product_2",
				["res_id"] = 26,
				["room_id"] = 1035,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["cost"] = 1,
				["cost_type"] = 2,
				["icon"] = "icon_toy_cuddleBear_2",
				["icon_head"] = "icon_Toyhalf_bear_2",
				["id"] = 7,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_bearLow_02",
				["mile_buff"] = 5,
				["model"] = "SF_Prop_bear_02",
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY3_Product_2",
				["res_id"] = 26,
				["room_id"] = 1035,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["cost"] = 1,
				["cost_type"] = 3,
				["icon"] = "icon_toy_cuddleBear_3",
				["icon_head"] = "icon_Toyhalf_bear_3",
				["id"] = 8,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_bearLow_03",
				["mile_buff"] = 25,
				["model"] = "SF_Prop_bear_03",
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY3_Product_2",
				["res_id"] = 26,
				["room_id"] = 1035,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["cost"] = 1,
				["cost_type"] = 4,
				["icon"] = "icon_toy_cuddleBear_4",
				["icon_head"] = "icon_Toyhalf_bear_4",
				["id"] = 9,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_bearLow_04",
				["mile_buff"] = 125,
				["model"] = "SF_Prop_bear_04",
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY3_Product_2",
				["res_id"] = 26,
				["room_id"] = 1035,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["cost"] = 2,
				["cost_type"] = 4,
				["icon"] = "icon_toy_cuddleBear_5",
				["icon_head"] = "icon_Toyhalf_bear_5",
				["id"] = 10,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_bearLow_05",
				["mile_buff"] = 625,
				["model"] = "SF_Prop_bear_05",
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY3_Product_2",
				["res_id"] = 26,
				["room_id"] = 1035,
				["starLevel"] = 4,
			}
			,
		}
		,
		[27] = {
			[0] = {
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "icon_toy_speedster_1",
				["icon_head"] = "icon_Toyhalf_car_1",
				["id"] = 11,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_carLow_01",
				["mile_buff"] = 1,
				["model"] = "SF_Prop_car_01",
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY3_Product_3",
				["res_id"] = 27,
				["room_id"] = 1036,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["cost"] = 1,
				["cost_type"] = 2,
				["icon"] = "icon_toy_speedster_2",
				["icon_head"] = "icon_Toyhalf_car_2",
				["id"] = 12,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_carLow_02",
				["mile_buff"] = 5,
				["model"] = "SF_Prop_car_02",
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY3_Product_3",
				["res_id"] = 27,
				["room_id"] = 1036,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["cost"] = 1,
				["cost_type"] = 3,
				["icon"] = "icon_toy_speedster_3",
				["icon_head"] = "icon_Toyhalf_car_3",
				["id"] = 13,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_carLow_03",
				["mile_buff"] = 25,
				["model"] = "SF_Prop_car_03",
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY3_Product_3",
				["res_id"] = 27,
				["room_id"] = 1036,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["cost"] = 1,
				["cost_type"] = 4,
				["icon"] = "icon_toy_speedster_4",
				["icon_head"] = "icon_Toyhalf_car_4",
				["id"] = 14,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_carLow_04",
				["mile_buff"] = 125,
				["model"] = "SF_Prop_car_04",
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY3_Product_3",
				["res_id"] = 27,
				["room_id"] = 1036,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["cost"] = 2,
				["cost_type"] = 4,
				["icon"] = "icon_toy_speedster_5",
				["icon_head"] = "icon_Toyhalf_car_5",
				["id"] = 15,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_carLow_05",
				["mile_buff"] = 625,
				["model"] = "SF_Prop_car_05",
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY3_Product_3",
				["res_id"] = 27,
				["room_id"] = 1036,
				["starLevel"] = 4,
			}
			,
		}
		,
		[28] = {
			[0] = {
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "icon_toy_spaceChaser_1",
				["icon_head"] = "icon_Toyhalf_aircraft_1",
				["id"] = 16,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_planeLow_01",
				["mile_buff"] = 1,
				["model"] = "SF_Prop_plane_01",
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY3_Product_4",
				["res_id"] = 28,
				["room_id"] = 1037,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["cost"] = 1,
				["cost_type"] = 2,
				["icon"] = "icon_toy_spaceChaser_2",
				["icon_head"] = "icon_Toyhalf_aircraft_2",
				["id"] = 17,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_planeLow_02",
				["mile_buff"] = 5,
				["model"] = "SF_Prop_plane_02",
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY3_Product_4",
				["res_id"] = 28,
				["room_id"] = 1037,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["cost"] = 1,
				["cost_type"] = 3,
				["icon"] = "icon_toy_spaceChaser_3",
				["icon_head"] = "icon_Toyhalf_aircraft_3",
				["id"] = 18,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_planeLow_03",
				["mile_buff"] = 25,
				["model"] = "SF_Prop_plane_03",
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY3_Product_4",
				["res_id"] = 28,
				["room_id"] = 1037,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["cost"] = 1,
				["cost_type"] = 4,
				["icon"] = "icon_toy_spaceChaser_4",
				["icon_head"] = "icon_Toyhalf_aircraft_4",
				["id"] = 19,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_planeLow_04",
				["mile_buff"] = 125,
				["model"] = "SF_Prop_plane_04",
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY3_Product_4",
				["res_id"] = 28,
				["room_id"] = 1037,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["cost"] = 2,
				["cost_type"] = 4,
				["icon"] = "icon_toy_spaceChaser_5",
				["icon_head"] = "icon_Toyhalf_aircraft_5",
				["id"] = 20,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_planeLow_05",
				["mile_buff"] = 625,
				["model"] = "SF_Prop_plane_05",
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY3_Product_4",
				["res_id"] = 28,
				["room_id"] = 1037,
				["starLevel"] = 4,
			}
			,
		}
		,
		[29] = {
			[0] = {
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "icon_toy_starletDoll_1",
				["icon_head"] = "icon_Toyhalf_barbie_1",
				["id"] = 21,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_BarbieLow_01",
				["mile_buff"] = 1,
				["model"] = "SF_Prop_Barbie_01",
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY3_Product_5",
				["res_id"] = 29,
				["room_id"] = 1038,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["cost"] = 1,
				["cost_type"] = 2,
				["icon"] = "icon_toy_starletDoll_2",
				["icon_head"] = "icon_Toyhalf_barbie_2",
				["id"] = 22,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_BarbieLow_02",
				["mile_buff"] = 5,
				["model"] = "SF_Prop_Barbie_02",
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY3_Product_5",
				["res_id"] = 29,
				["room_id"] = 1038,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["cost"] = 1,
				["cost_type"] = 3,
				["icon"] = "icon_toy_starletDoll_3",
				["icon_head"] = "icon_Toyhalf_barbie_3",
				["id"] = 23,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_BarbieLow_03",
				["mile_buff"] = 25,
				["model"] = "SF_Prop_Barbie_03",
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY3_Product_5",
				["res_id"] = 29,
				["room_id"] = 1038,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["cost"] = 1,
				["cost_type"] = 4,
				["icon"] = "icon_toy_starletDoll_4",
				["icon_head"] = "icon_Toyhalf_barbie_4",
				["id"] = 24,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_BarbieLow_04",
				["mile_buff"] = 125,
				["model"] = "SF_Prop_Barbie_04",
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY3_Product_5",
				["res_id"] = 29,
				["room_id"] = 1038,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["cost"] = 2,
				["cost_type"] = 4,
				["icon"] = "icon_toy_starletDoll_5",
				["icon_head"] = "icon_Toyhalf_barbie_5",
				["id"] = 25,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_BarbieLow_05",
				["mile_buff"] = 625,
				["model"] = "SF_Prop_Barbie_05",
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY3_Product_5",
				["res_id"] = 29,
				["room_id"] = 1038,
				["starLevel"] = 4,
			}
			,
		}
		,
		[30] = {
			[0] = {
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "icon_toy_empireTroop_1",
				["icon_head"] = "icon_Toyhalf_soldier_1",
				["id"] = 26,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_starWarLow_01",
				["mile_buff"] = 1,
				["model"] = "SF_Prop_starWar_01",
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY3_Product_6",
				["res_id"] = 30,
				["room_id"] = 1039,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["cost"] = 1,
				["cost_type"] = 2,
				["icon"] = "icon_toy_empireTroop_2",
				["icon_head"] = "icon_Toyhalf_soldier_2",
				["id"] = 27,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_starWarLow_02",
				["mile_buff"] = 5,
				["model"] = "SF_Prop_starWar_02",
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY3_Product_6",
				["res_id"] = 30,
				["room_id"] = 1039,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["cost"] = 1,
				["cost_type"] = 3,
				["icon"] = "icon_toy_empireTroop_3",
				["icon_head"] = "icon_Toyhalf_soldier_3",
				["id"] = 28,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_starWarLow_03",
				["mile_buff"] = 25,
				["model"] = "SF_Prop_starWar_03",
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY3_Product_6",
				["res_id"] = 30,
				["room_id"] = 1039,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["cost"] = 1,
				["cost_type"] = 4,
				["icon"] = "icon_toy_empireTroop_4",
				["icon_head"] = "icon_Toyhalf_soldier_4",
				["id"] = 29,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_starWarLow_04",
				["mile_buff"] = 125,
				["model"] = "SF_Prop_starWar_04",
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY3_Product_6",
				["res_id"] = 30,
				["room_id"] = 1039,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["cost"] = 2,
				["cost_type"] = 4,
				["icon"] = "icon_toy_empireTroop_5",
				["icon_head"] = "icon_Toyhalf_soldier_5",
				["id"] = 30,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_starWarLow_05",
				["mile_buff"] = 625,
				["model"] = "SF_Prop_starWar_05",
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY3_Product_6",
				["res_id"] = 30,
				["room_id"] = 1039,
				["starLevel"] = 4,
			}
			,
		}
		,
		[31] = {
			[0] = {
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "icon_toy_trackMaster_1",
				["icon_head"] = "icon_Toyhalf_train_1",
				["id"] = 31,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_trainLow_01",
				["mile_buff"] = 1,
				["model"] = "SF_Prop_train_01",
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY3_Product_7",
				["res_id"] = 31,
				["room_id"] = 1040,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["cost"] = 1,
				["cost_type"] = 2,
				["icon"] = "icon_toy_trackMaster_2",
				["icon_head"] = "icon_Toyhalf_train_2",
				["id"] = 32,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_trainLow_02",
				["mile_buff"] = 5,
				["model"] = "SF_Prop_train_02",
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY3_Product_7",
				["res_id"] = 31,
				["room_id"] = 1040,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["cost"] = 1,
				["cost_type"] = 3,
				["icon"] = "icon_toy_trackMaster_3",
				["icon_head"] = "icon_Toyhalf_train_3",
				["id"] = 33,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_trainLow_03",
				["mile_buff"] = 25,
				["model"] = "SF_Prop_train_03",
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY3_Product_7",
				["res_id"] = 31,
				["room_id"] = 1040,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["cost"] = 1,
				["cost_type"] = 4,
				["icon"] = "icon_toy_trackMaster_4",
				["icon_head"] = "icon_Toyhalf_train_4",
				["id"] = 34,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_trainLow_04",
				["mile_buff"] = 125,
				["model"] = "SF_Prop_train_04",
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY3_Product_7",
				["res_id"] = 31,
				["room_id"] = 1040,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["cost"] = 2,
				["cost_type"] = 4,
				["icon"] = "icon_toy_trackMaster_5",
				["icon_head"] = "icon_Toyhalf_train_5",
				["id"] = 35,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_trainLow_05",
				["mile_buff"] = 625,
				["model"] = "SF_Prop_train_05",
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY3_Product_7",
				["res_id"] = 31,
				["room_id"] = 1040,
				["starLevel"] = 4,
			}
			,
		}
		,
		[32] = {
			[0] = {
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "icon_toy_godzilla_1",
				["icon_head"] = "icon_Toyhalf_monster_1",
				["id"] = 36,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_GodzillaLow_01",
				["mile_buff"] = 1,
				["model"] = "SF_Prop_Godzilla_01",
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY3_Product_8",
				["res_id"] = 32,
				["room_id"] = 1041,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["cost"] = 1,
				["cost_type"] = 2,
				["icon"] = "icon_toy_godzilla_2",
				["icon_head"] = "icon_Toyhalf_monster_2",
				["id"] = 37,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_GodzillaLow_02",
				["mile_buff"] = 5,
				["model"] = "SF_Prop_Godzilla_02",
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY3_Product_8",
				["res_id"] = 32,
				["room_id"] = 1041,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["cost"] = 1,
				["cost_type"] = 3,
				["icon"] = "icon_toy_godzilla_3",
				["icon_head"] = "icon_Toyhalf_monster_3",
				["id"] = 38,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_GodzillaLow_03",
				["mile_buff"] = 25,
				["model"] = "SF_Prop_Godzilla_03",
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY3_Product_8",
				["res_id"] = 32,
				["room_id"] = 1041,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["cost"] = 1,
				["cost_type"] = 4,
				["icon"] = "icon_toy_godzilla_4",
				["icon_head"] = "icon_Toyhalf_monster_4",
				["id"] = 39,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_GodzillaLow_04",
				["mile_buff"] = 125,
				["model"] = "SF_Prop_Godzilla_04",
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY3_Product_8",
				["res_id"] = 32,
				["room_id"] = 1041,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["cost"] = 2,
				["cost_type"] = 4,
				["icon"] = "icon_toy_godzilla_5",
				["icon_head"] = "icon_Toyhalf_monster_5",
				["id"] = 40,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_GodzillaLow_05",
				["mile_buff"] = 625,
				["model"] = "SF_Prop_Godzilla_05",
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY3_Product_8",
				["res_id"] = 32,
				["room_id"] = 1041,
				["starLevel"] = 4,
			}
			,
		}
		,
		[33] = {
			[0] = {
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "icon_toy_playX_1",
				["icon_head"] = "icon_Toyhalf_game_1",
				["id"] = 41,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gamesConsoleLow_01",
				["mile_buff"] = 1,
				["model"] = "SF_Prop_gamesConsole_01",
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY3_Product_9",
				["res_id"] = 33,
				["room_id"] = 1042,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["cost"] = 1,
				["cost_type"] = 2,
				["icon"] = "icon_toy_playX_2",
				["icon_head"] = "icon_Toyhalf_game_2",
				["id"] = 42,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gamesConsoleLow_02",
				["mile_buff"] = 5,
				["model"] = "SF_Prop_gamesConsole_02",
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY3_Product_9",
				["res_id"] = 33,
				["room_id"] = 1042,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["cost"] = 1,
				["cost_type"] = 3,
				["icon"] = "icon_toy_playX_3",
				["icon_head"] = "icon_Toyhalf_game_3",
				["id"] = 43,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gamesConsoleLow_03",
				["mile_buff"] = 25,
				["model"] = "SF_Prop_gamesConsole_03",
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY3_Product_9",
				["res_id"] = 33,
				["room_id"] = 1042,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["cost"] = 1,
				["cost_type"] = 4,
				["icon"] = "icon_toy_playX_4",
				["icon_head"] = "icon_Toyhalf_game_4",
				["id"] = 44,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gamesConsoleLow_04",
				["mile_buff"] = 125,
				["model"] = "SF_Prop_gamesConsole_04",
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY3_Product_9",
				["res_id"] = 33,
				["room_id"] = 1042,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["cost"] = 2,
				["cost_type"] = 4,
				["icon"] = "icon_toy_playX_5",
				["icon_head"] = "icon_Toyhalf_game_5",
				["id"] = 45,
				["instance_id"] = 6,
				["lowModel"] = "SF_Prop_gamesConsoleLow_05",
				["mile_buff"] = 625,
				["model"] = "SF_Prop_gamesConsole_05",
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY3_Product_9",
				["res_id"] = 33,
				["room_id"] = 1042,
				["starLevel"] = 4,
			}
			,
		}
		,
	}
	,
	[7] = {
		[34] = {
			[0] = {
				["banner"] = "ui_NtClub_blueprint_banner_bartender",
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "banner_NtClub_card_bartender",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 46,
				["instance_id"] = 7,
				["mile_buff"] = 1,
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY4_Product_1",
				["res_id"] = 34,
				["room_id"] = 1044,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["banner"] = "ui_NtClub_blueprint_banner_bartender",
				["cost"] = 1,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_bartender",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 47,
				["instance_id"] = 7,
				["mile_buff"] = 5,
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY4_Product_1",
				["res_id"] = 34,
				["room_id"] = 1044,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["banner"] = "ui_NtClub_blueprint_banner_bartender",
				["cost"] = 2,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_bartender",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 48,
				["instance_id"] = 7,
				["mile_buff"] = 25,
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY4_Product_1",
				["res_id"] = 34,
				["room_id"] = 1044,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["banner"] = "ui_NtClub_blueprint_banner_bartender",
				["cost"] = 1,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_bartender",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 49,
				["instance_id"] = 7,
				["mile_buff"] = 125,
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY4_Product_1",
				["res_id"] = 34,
				["room_id"] = 1044,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["banner"] = "ui_NtClub_blueprint_banner_bartender",
				["cost"] = 2,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_bartender",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 50,
				["instance_id"] = 7,
				["mile_buff"] = 625,
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY4_Product_1",
				["res_id"] = 34,
				["room_id"] = 1044,
				["starLevel"] = 4,
			}
			,
			[5] = {
				["banner"] = "ui_NtClub_blueprint_banner_bartender",
				["cost"] = 1,
				["cost_type"] = 8,
				["icon"] = "banner_NtClub_card_bartender",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 51,
				["instance_id"] = 7,
				["mile_buff"] = 2500,
				["money_buff"] = 2500,
				["name"] = "TXT_INSTANCE_CY4_Product_1",
				["res_id"] = 34,
				["room_id"] = 1044,
				["starLevel"] = 5,
			}
			,
		}
		,
		[35] = {
			[0] = {
				["banner"] = "ui_NtClub_blueprint_banner_LeadDancer",
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "banner_NtClub_card_LeadDancer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 52,
				["instance_id"] = 7,
				["mile_buff"] = 1,
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY4_Product_2",
				["res_id"] = 35,
				["room_id"] = 1045,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["banner"] = "ui_NtClub_blueprint_banner_LeadDancer",
				["cost"] = 1,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_LeadDancer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 53,
				["instance_id"] = 7,
				["mile_buff"] = 5,
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY4_Product_2",
				["res_id"] = 35,
				["room_id"] = 1045,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["banner"] = "ui_NtClub_blueprint_banner_LeadDancer",
				["cost"] = 2,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_LeadDancer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 54,
				["instance_id"] = 7,
				["mile_buff"] = 25,
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY4_Product_2",
				["res_id"] = 35,
				["room_id"] = 1045,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["banner"] = "ui_NtClub_blueprint_banner_LeadDancer",
				["cost"] = 1,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_LeadDancer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 55,
				["instance_id"] = 7,
				["mile_buff"] = 125,
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY4_Product_2",
				["res_id"] = 35,
				["room_id"] = 1045,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["banner"] = "ui_NtClub_blueprint_banner_LeadDancer",
				["cost"] = 2,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_LeadDancer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 56,
				["instance_id"] = 7,
				["mile_buff"] = 625,
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY4_Product_2",
				["res_id"] = 35,
				["room_id"] = 1045,
				["starLevel"] = 4,
			}
			,
			[5] = {
				["banner"] = "ui_NtClub_blueprint_banner_LeadDancer",
				["cost"] = 1,
				["cost_type"] = 8,
				["icon"] = "banner_NtClub_card_LeadDancer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 57,
				["instance_id"] = 7,
				["mile_buff"] = 2500,
				["money_buff"] = 2500,
				["name"] = "TXT_INSTANCE_CY4_Product_2",
				["res_id"] = 35,
				["room_id"] = 1045,
				["starLevel"] = 5,
			}
			,
		}
		,
		[36] = {
			[0] = {
				["banner"] = "ui_NtClub_blueprint_banner_DJ",
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "banner_NtClub_card_DJ",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 58,
				["instance_id"] = 7,
				["mile_buff"] = 1,
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY4_Product_3",
				["res_id"] = 36,
				["room_id"] = 1046,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["banner"] = "ui_NtClub_blueprint_banner_DJ",
				["cost"] = 1,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_DJ",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 59,
				["instance_id"] = 7,
				["mile_buff"] = 5,
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY4_Product_3",
				["res_id"] = 36,
				["room_id"] = 1046,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["banner"] = "ui_NtClub_blueprint_banner_DJ",
				["cost"] = 2,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_DJ",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 60,
				["instance_id"] = 7,
				["mile_buff"] = 25,
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY4_Product_3",
				["res_id"] = 36,
				["room_id"] = 1046,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["banner"] = "ui_NtClub_blueprint_banner_DJ",
				["cost"] = 1,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_DJ",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 61,
				["instance_id"] = 7,
				["mile_buff"] = 125,
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY4_Product_3",
				["res_id"] = 36,
				["room_id"] = 1046,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["banner"] = "ui_NtClub_blueprint_banner_DJ",
				["cost"] = 2,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_DJ",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 62,
				["instance_id"] = 7,
				["mile_buff"] = 625,
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY4_Product_3",
				["res_id"] = 36,
				["room_id"] = 1046,
				["starLevel"] = 4,
			}
			,
			[5] = {
				["banner"] = "ui_NtClub_blueprint_banner_DJ",
				["cost"] = 1,
				["cost_type"] = 8,
				["icon"] = "banner_NtClub_card_DJ",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 63,
				["instance_id"] = 7,
				["mile_buff"] = 2500,
				["money_buff"] = 2500,
				["name"] = "TXT_INSTANCE_CY4_Product_3",
				["res_id"] = 36,
				["room_id"] = 1046,
				["starLevel"] = 5,
			}
			,
		}
		,
		[37] = {
			[0] = {
				["banner"] = "ui_NtClub_blueprint_banner_MarijuanaMaid",
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "banner_NtClub_card_waitress",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 64,
				["instance_id"] = 7,
				["mile_buff"] = 1,
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY4_Product_4",
				["res_id"] = 37,
				["room_id"] = 1047,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["banner"] = "ui_NtClub_blueprint_banner_MarijuanaMaid",
				["cost"] = 1,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_waitress",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 65,
				["instance_id"] = 7,
				["mile_buff"] = 5,
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY4_Product_4",
				["res_id"] = 37,
				["room_id"] = 1047,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["banner"] = "ui_NtClub_blueprint_banner_MarijuanaMaid",
				["cost"] = 2,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_waitress",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 66,
				["instance_id"] = 7,
				["mile_buff"] = 25,
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY4_Product_4",
				["res_id"] = 37,
				["room_id"] = 1047,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["banner"] = "ui_NtClub_blueprint_banner_MarijuanaMaid",
				["cost"] = 1,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_waitress",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 67,
				["instance_id"] = 7,
				["mile_buff"] = 125,
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY4_Product_4",
				["res_id"] = 37,
				["room_id"] = 1047,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["banner"] = "ui_NtClub_blueprint_banner_MarijuanaMaid",
				["cost"] = 2,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_waitress",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 68,
				["instance_id"] = 7,
				["mile_buff"] = 625,
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY4_Product_4",
				["res_id"] = 37,
				["room_id"] = 1047,
				["starLevel"] = 4,
			}
			,
			[5] = {
				["banner"] = "ui_NtClub_blueprint_banner_MarijuanaMaid",
				["cost"] = 1,
				["cost_type"] = 8,
				["icon"] = "banner_NtClub_card_waitress",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 69,
				["instance_id"] = 7,
				["mile_buff"] = 2500,
				["money_buff"] = 2500,
				["name"] = "TXT_INSTANCE_CY4_Product_4",
				["res_id"] = 37,
				["room_id"] = 1047,
				["starLevel"] = 5,
			}
			,
		}
		,
		[38] = {
			[0] = {
				["banner"] = "ui_NtClub_blueprint_banner_HookahBunny",
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "banner_NtClub_card_barmaid",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 70,
				["instance_id"] = 7,
				["mile_buff"] = 1,
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY4_Product_5",
				["res_id"] = 38,
				["room_id"] = 1048,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["banner"] = "ui_NtClub_blueprint_banner_HookahBunny",
				["cost"] = 1,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_barmaid",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 71,
				["instance_id"] = 7,
				["mile_buff"] = 5,
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY4_Product_5",
				["res_id"] = 38,
				["room_id"] = 1048,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["banner"] = "ui_NtClub_blueprint_banner_HookahBunny",
				["cost"] = 2,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_barmaid",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 72,
				["instance_id"] = 7,
				["mile_buff"] = 25,
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY4_Product_5",
				["res_id"] = 38,
				["room_id"] = 1048,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["banner"] = "ui_NtClub_blueprint_banner_HookahBunny",
				["cost"] = 1,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_barmaid",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 73,
				["instance_id"] = 7,
				["mile_buff"] = 125,
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY4_Product_5",
				["res_id"] = 38,
				["room_id"] = 1048,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["banner"] = "ui_NtClub_blueprint_banner_HookahBunny",
				["cost"] = 2,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_barmaid",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 74,
				["instance_id"] = 7,
				["mile_buff"] = 625,
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY4_Product_5",
				["res_id"] = 38,
				["room_id"] = 1048,
				["starLevel"] = 4,
			}
			,
			[5] = {
				["banner"] = "ui_NtClub_blueprint_banner_HookahBunny",
				["cost"] = 1,
				["cost_type"] = 8,
				["icon"] = "banner_NtClub_card_barmaid",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 75,
				["instance_id"] = 7,
				["mile_buff"] = 2500,
				["money_buff"] = 2500,
				["name"] = "TXT_INSTANCE_CY4_Product_5",
				["res_id"] = 38,
				["room_id"] = 1048,
				["starLevel"] = 5,
			}
			,
		}
		,
		[39] = {
			[0] = {
				["banner"] = "ui_NtClub_blueprint_banner_DiceCroupier",
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "banner_NtClub_card_diceDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 76,
				["instance_id"] = 7,
				["mile_buff"] = 1,
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY4_Product_6",
				["res_id"] = 39,
				["room_id"] = 1049,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["banner"] = "ui_NtClub_blueprint_banner_DiceCroupier",
				["cost"] = 1,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_diceDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 77,
				["instance_id"] = 7,
				["mile_buff"] = 5,
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY4_Product_6",
				["res_id"] = 39,
				["room_id"] = 1049,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["banner"] = "ui_NtClub_blueprint_banner_DiceCroupier",
				["cost"] = 2,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_diceDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 78,
				["instance_id"] = 7,
				["mile_buff"] = 25,
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY4_Product_6",
				["res_id"] = 39,
				["room_id"] = 1049,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["banner"] = "ui_NtClub_blueprint_banner_DiceCroupier",
				["cost"] = 1,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_diceDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 79,
				["instance_id"] = 7,
				["mile_buff"] = 125,
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY4_Product_6",
				["res_id"] = 39,
				["room_id"] = 1049,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["banner"] = "ui_NtClub_blueprint_banner_DiceCroupier",
				["cost"] = 2,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_diceDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 80,
				["instance_id"] = 7,
				["mile_buff"] = 625,
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY4_Product_6",
				["res_id"] = 39,
				["room_id"] = 1049,
				["starLevel"] = 4,
			}
			,
			[5] = {
				["banner"] = "ui_NtClub_blueprint_banner_DiceCroupier",
				["cost"] = 1,
				["cost_type"] = 8,
				["icon"] = "banner_NtClub_card_diceDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 81,
				["instance_id"] = 7,
				["mile_buff"] = 2500,
				["money_buff"] = 2500,
				["name"] = "TXT_INSTANCE_CY4_Product_6",
				["res_id"] = 39,
				["room_id"] = 1049,
				["starLevel"] = 5,
			}
			,
		}
		,
		[40] = {
			[0] = {
				["banner"] = "ui_NtClub_blueprint_banner_TexasCroupier",
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "banner_NtClub_card_pokerDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 82,
				["instance_id"] = 7,
				["mile_buff"] = 1,
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY4_Product_7",
				["res_id"] = 40,
				["room_id"] = 1050,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["banner"] = "ui_NtClub_blueprint_banner_TexasCroupier",
				["cost"] = 1,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_pokerDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 83,
				["instance_id"] = 7,
				["mile_buff"] = 5,
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY4_Product_7",
				["res_id"] = 40,
				["room_id"] = 1050,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["banner"] = "ui_NtClub_blueprint_banner_TexasCroupier",
				["cost"] = 2,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_pokerDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 84,
				["instance_id"] = 7,
				["mile_buff"] = 25,
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY4_Product_7",
				["res_id"] = 40,
				["room_id"] = 1050,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["banner"] = "ui_NtClub_blueprint_banner_TexasCroupier",
				["cost"] = 1,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_pokerDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 85,
				["instance_id"] = 7,
				["mile_buff"] = 125,
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY4_Product_7",
				["res_id"] = 40,
				["room_id"] = 1050,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["banner"] = "ui_NtClub_blueprint_banner_TexasCroupier",
				["cost"] = 2,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_pokerDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 86,
				["instance_id"] = 7,
				["mile_buff"] = 625,
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY4_Product_7",
				["res_id"] = 40,
				["room_id"] = 1050,
				["starLevel"] = 4,
			}
			,
			[5] = {
				["banner"] = "ui_NtClub_blueprint_banner_TexasCroupier",
				["cost"] = 1,
				["cost_type"] = 8,
				["icon"] = "banner_NtClub_card_pokerDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 87,
				["instance_id"] = 7,
				["mile_buff"] = 2500,
				["money_buff"] = 2500,
				["name"] = "TXT_INSTANCE_CY4_Product_7",
				["res_id"] = 40,
				["room_id"] = 1050,
				["starLevel"] = 5,
			}
			,
		}
		,
		[41] = {
			[0] = {
				["banner"] = "ui_NtClub_blueprint_banner_RouletteCroupier",
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "banner_NtClub_card_rouletteDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 88,
				["instance_id"] = 7,
				["mile_buff"] = 1,
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY4_Product_8",
				["res_id"] = 41,
				["room_id"] = 1051,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["banner"] = "ui_NtClub_blueprint_banner_RouletteCroupier",
				["cost"] = 1,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_rouletteDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 89,
				["instance_id"] = 7,
				["mile_buff"] = 5,
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY4_Product_8",
				["res_id"] = 41,
				["room_id"] = 1051,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["banner"] = "ui_NtClub_blueprint_banner_RouletteCroupier",
				["cost"] = 2,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_rouletteDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 90,
				["instance_id"] = 7,
				["mile_buff"] = 25,
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY4_Product_8",
				["res_id"] = 41,
				["room_id"] = 1051,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["banner"] = "ui_NtClub_blueprint_banner_RouletteCroupier",
				["cost"] = 1,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_rouletteDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 91,
				["instance_id"] = 7,
				["mile_buff"] = 125,
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY4_Product_8",
				["res_id"] = 41,
				["room_id"] = 1051,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["banner"] = "ui_NtClub_blueprint_banner_RouletteCroupier",
				["cost"] = 2,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_rouletteDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 92,
				["instance_id"] = 7,
				["mile_buff"] = 625,
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY4_Product_8",
				["res_id"] = 41,
				["room_id"] = 1051,
				["starLevel"] = 4,
			}
			,
			[5] = {
				["banner"] = "ui_NtClub_blueprint_banner_RouletteCroupier",
				["cost"] = 1,
				["cost_type"] = 8,
				["icon"] = "banner_NtClub_card_rouletteDealer",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 93,
				["instance_id"] = 7,
				["mile_buff"] = 2500,
				["money_buff"] = 2500,
				["name"] = "TXT_INSTANCE_CY4_Product_8",
				["res_id"] = 41,
				["room_id"] = 1051,
				["starLevel"] = 5,
			}
			,
		}
		,
		[42] = {
			[0] = {
				["banner"] = "ui_NtClub_blueprint_banner_Strippers",
				["cost"] = 0,
				["cost_type"] = 0,
				["icon"] = "banner_NtClub_card_Stripper",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 94,
				["instance_id"] = 7,
				["mile_buff"] = 1,
				["money_buff"] = 1,
				["name"] = "TXT_INSTANCE_CY4_Product_9",
				["res_id"] = 42,
				["room_id"] = 1052,
				["starLevel"] = 0,
			}
			,
			[1] = {
				["banner"] = "ui_NtClub_blueprint_banner_Strippers",
				["cost"] = 1,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_Stripper",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 95,
				["instance_id"] = 7,
				["mile_buff"] = 5,
				["money_buff"] = 5,
				["name"] = "TXT_INSTANCE_CY4_Product_9",
				["res_id"] = 42,
				["room_id"] = 1052,
				["starLevel"] = 1,
			}
			,
			[2] = {
				["banner"] = "ui_NtClub_blueprint_banner_Strippers",
				["cost"] = 2,
				["cost_type"] = 6,
				["icon"] = "banner_NtClub_card_Stripper",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 96,
				["instance_id"] = 7,
				["mile_buff"] = 25,
				["money_buff"] = 25,
				["name"] = "TXT_INSTANCE_CY4_Product_9",
				["res_id"] = 42,
				["room_id"] = 1052,
				["starLevel"] = 2,
			}
			,
			[3] = {
				["banner"] = "ui_NtClub_blueprint_banner_Strippers",
				["cost"] = 1,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_Stripper",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 97,
				["instance_id"] = 7,
				["mile_buff"] = 125,
				["money_buff"] = 125,
				["name"] = "TXT_INSTANCE_CY4_Product_9",
				["res_id"] = 42,
				["room_id"] = 1052,
				["starLevel"] = 3,
			}
			,
			[4] = {
				["banner"] = "ui_NtClub_blueprint_banner_Strippers",
				["cost"] = 2,
				["cost_type"] = 7,
				["icon"] = "banner_NtClub_card_Stripper",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 98,
				["instance_id"] = 7,
				["mile_buff"] = 625,
				["money_buff"] = 625,
				["name"] = "TXT_INSTANCE_CY4_Product_9",
				["res_id"] = 42,
				["room_id"] = 1052,
				["starLevel"] = 4,
			}
			,
			[5] = {
				["banner"] = "ui_NtClub_blueprint_banner_Strippers",
				["cost"] = 1,
				["cost_type"] = 8,
				["icon"] = "banner_NtClub_card_Stripper",
				["icon_head"] = "icon_NtClub_cash2",
				["id"] = 99,
				["instance_id"] = 7,
				["mile_buff"] = 2500,
				["money_buff"] = 2500,
				["name"] = "TXT_INSTANCE_CY4_Product_9",
				["res_id"] = 42,
				["room_id"] = 1052,
				["starLevel"] = 5,
			}
			,
		}
		,
	}
	,
}
return config_cy_instance_blueprint