---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Microsoft-GXY.
--- DateTime: 2024/8/16 12:28
---
local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")
local UIView = require("Framework.UI.View") -- 当工具类使用
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper
local Random = CS.UnityEngine.Random
local CycleToyAIBlackBoard = GameTableDefine.CycleToyAIBlackBoard ---@type CycleToyAIBlackBoard
local AnimationUtil = CS.Common.Utils.AnimationUtil

local WALK_SPEED = 5.5
local RUN_SPEED = 10


---@class CycleToyClientPay:AIStateBase
---@field m_owner CycleToyWorker
local CycleToyClientPay = Class("CycleToyClientPay",AIStateBase)

function CycleToyClientPay:ctor()

end

function CycleToyClientPay:OnEnter(...)
    local actor = self.m_owner
    local actorData = actor.data
    local stateMachine = actor.m_stateMachine
    
    local payData = select(1, ...)   ---@type toyPayPosStruct
    local income = CycleInstanceDataManager:GetCurrentModel():SellAllProduct()
    
    -- 播放动 画
    actor:SetAnimator(PERSON_ACTION.TROLLEY_IDLE)
    -- 播放收银员动画
    AnimationUtil.AddKeyFrameEventOnObj(payData.character, "ANIM_END", function()
        actor.m_stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleToyClientLeave)
        CycleToyAIBlackBoard:DeoccupyCounter(actor)
        payData.animator:SetInteger("Action", PERSON_ACTION.IDLE)
    end)
    payData.animator:SetInteger("Action", PERSON_ACTION.WORK)
    -- 收银员显示气泡
    CycleInstanceDataManager:GetCurrentModel():GetScene():ShowCashierBubble(payData.character, 1, income)

end

function CycleToyClientPay:OnExit()
    
end

function CycleToyClientPay:OnDestroy()
    self:OnExit()
end

return CycleToyClientPay