---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Microsoft-GXY.
--- DateTime: 2024/8/16 12:28
---
local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")
local UIView = require("Framework.UI.View") -- 当工具类使用
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper
local Random = CS.UnityEngine.Random
local ActorManager = GameTableDefine.ActorManager ---@type ActorManager
local CycleToyAIBlackBoard = GameTableDefine.CycleToyAIBlackBoard ---@type CycleToyAIBlackBoard

local WALK_SPEED = 5.5
local RUN_SPEED = 10


---@class CycleToyClientGoToPay:AIStateBase
---@field m_owner CycleToyWorker
local CycleToyClientGoToPay = Class("CycleToyClientGoToPay",AIStateBase)

function CycleToyClientGoToPay:ctor()
    self.timer = nil
end

function CycleToyClientGoToPay:OnEnter(...)
    local actor = self.m_owner
    local actorData = actor.data
    local stateMachine = actor.m_stateMachine
    local payData = CycleToyAIBlackBoard:OccupiedCheckoutCounter(actor)

    -- 播放动画
    actor:SetAnimator(PERSON_ACTION.TROLLEY_RUN_BUY)
    
    -- 寻路
    local speed = WALK_SPEED + Random.Range(-1.1, 1.1)
    actor:CalculatePath(
        payData.pos.transform,
        true,
        speed,
        Random.Range(1.1, 4.1),
        function()
            stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleToyClientPay, payData)
        end
    )

end

function CycleToyClientGoToPay:OnExit()
    if self.timer then
        GameTimer:StopTimer(self.timer)
        self.timer = nil
    end
end


function CycleToyClientGoToPay:OnDestroy()
    self:OnExit()
end


return CycleToyClientGoToPay