---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Microsoft-GXY.
--- DateTime: 2024/8/16 12:28
---
local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")
local UIView = require("Framework.UI.View") -- 当工具类使用
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper
local Random = CS.UnityEngine.Random
local CycleNightClubAIBlackBoard = GameTableDefine.CycleNightClubAIBlackBoard ---@type CycleNightClubAIBlackBoard
local AnimationUtil = CS.Common.Utils.AnimationUtil
local ConfigMgr = GameTableDefine.ConfigMgr

local WALK_SPEED = 5.5
local RUN_SPEED = 10


---@class CycleNightClubClientPay:AIStateBase
---@field m_owner CycleNightClubClient
local CycleNightClubClientPay = Class("CycleNightClubClientPay",AIStateBase)

function CycleNightClubClientPay:ctor()
    self.timer = nil
    self.m_currentModel = nil---@type CycleNightClubModel
end

function CycleNightClubClientPay:OnEnter(...)

    self.m_currentModel = CycleInstanceDataManager:GetCurrentModel()

    local actor = self.m_owner
    local playData = select(1, ...)
    -- CycleNightClubAIBlackBoard:SetPlayPosActor(actorData, actor)

    CycleNightClubAIBlackBoard.inPaymentState = true
    CycleNightClubAIBlackBoard:ModifyOutClubClientNum(-1)
    local income = self.m_currentModel:SellAllProduct()
    local payPos = CycleNightClubAIBlackBoard.gateData.payPos
    -- 播放动画
    actor.m_animator:Play(ActorDefine.AnimationNames.Walk)
    
    local speed = ConfigMgr.config_global.character_walk_v + Random.Range(-1.1, 1.1)
    actor:CalculatePath(
        payPos.transform,
        true,
        speed,
        Random.Range(1.1, 4.1),
        function()
            actor.m_animator:Play(ActorDefine.AnimationNames.Idle)
            
            if self.timer then
                GameTimer:StopTimer(self.timer)
                self.timer = nil
            else
                local duration = self.m_currentModel.config_global.cycle_instance_queue_PayTime
                self.timer = GameTimer:CreateNewTimer(duration, function()
                    local scene = self.m_currentModel:GetScene()
                    -- 付款气泡
                    scene:ShowGetMoneyBubble(income)
                    --付钱时间结束后进入房间, 开始寻路
                    actor.m_stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleNightClubClientGotoPlay, playData)
                    GameTimer:StopTimer(self.timer)
                    self.timer = nil
                end, false, false)
            end

        end
    )

end

function CycleNightClubClientPay:OnExit()
    if self.timer then
        GameTimer:StopTimer(self.timer)
        self.timer = nil
    end
    CycleNightClubAIBlackBoard.inPaymentState = false
end

function CycleNightClubClientPay:OnDestroy()
    if self.timer then
        GameTimer:StopTimer(self.timer)
        self.timer = nil
    end
    CycleNightClubAIBlackBoard.inPaymentState = false
end

return CycleNightClubClientPay