---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Microsoft-GXY.
--- DateTime: 2024/8/16 12:28
---
local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")
local UIView = require("Framework.UI.View") -- 当工具类使用
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper
local Random = CS.UnityEngine.Random
local AnimationUtil = CS.Common.Utils.AnimationUtil
local ConfigMgr = GameTableDefine.ConfigMgr

local CycleNightClubAIBlackBoard = GameTableDefine.CycleNightClubAIBlackBoard ---@type CycleNightClubAIBlackBoard

local WALK_SPEED = 5
local RUN_SPEED = 10


---@class CycleNightClubClientGotoPlay:AIStateBase
---@field m_owner CycleNightClubClient
local CycleNightClubClientGotoPlay = Class("CycleNightClubClientGotoPlay", AIStateBase)

function CycleNightClubClientGotoPlay:ctor()

end

function CycleNightClubClientGotoPlay:OnEnter(...)
    local actor = self.m_owner
    local actorData = actor.data
    local stateMachine = actor.m_stateMachine
    -- 记录进入时间
    actorData.enterTime = GameTimeManager:GetCurLocalTime(true)
    CycleNightClubAIBlackBoard:ModifyInClubClientNum(1)
    
    local durationOfStay = CycleInstanceDataManager:GetCurrentModel():GetDurationOfStayLimit()
    local playData = select(1, ...)
    self:GoToPlay(actor, actorData, durationOfStay, playData)
end

function CycleNightClubClientGotoPlay:GoToPlay(actor, actorData, durationOfStay, playData)
    self.m_owner:ShowBubble(nil)
    -- 播放动画
    actor.m_animator:Play(ActorDefine.AnimationNames.Walk)
    local endPos = playData.positionGO
    local speed = ConfigMgr.config_global.character_walk_v + Random.Range(-1.1, 1.1)

    local PlayFunc = function()
        actor.gameObject.transform.position = playData.positionGO.transform.position
        UnityHelper.RotateTowards(actor.gameObject.transform, Vector3(playData.rotationGO.transform.position.x, playData.positionGO.transform.position.y, playData.rotationGO.transform.position.z))

        AnimationUtil.AddKeyFrameEventOnObj(actor.gameObject, "RANDOM_TIMES_ANIM_END", function()
            if self.m_owner.m_go then
                -- 检查是否达到最大停留时间, 如果是则离开, 否则继续找下个房间
                local now = GameTimeManager:GetCurLocalTime(true)
                if now - actorData.enterTime >= durationOfStay then
                    CycleNightClubAIBlackBoard:SetPlayPosActor(playData, nil)
                    actor.m_stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleNightClubClientLeave)
                else
                    CycleNightClubAIBlackBoard:SetPlayPosActor(playData, nil)
                    playData = CycleNightClubAIBlackBoard:GetSparePlayPos(actor) -- 因为刚把位置空出来一个, 所以一定有空位置
                    -- CycleNightClubAIBlackBoard:SetPlayPosActor(playData, actor)

                    self:GoToPlay(actor, actorData, durationOfStay, playData)
                end
            end
        end)
        local animator = UIView:GetComp(actor.gameObject, "", "Animator")
        animator:Play(endPos.name)
        -- CycleNightClubAIBlackBoard:SetPlayPosActor(playData, actor)
        self.m_owner:ShowBubble(endPos.name)
    end

    if actorData.isPreload then
        actorData.isPreload = nil
        PlayFunc()
    else
        actor:CalculatePath(
            endPos.transform,
            true,
            speed,
            Random.Range(1.1, 4.1),
            function()
                PlayFunc()
            end
        )
    end

end

function CycleNightClubClientGotoPlay:OnExit()
    self.m_owner:ShowBubble(nil)
end

function CycleNightClubClientGotoPlay:OnDestroy()
    self:OnExit()
end

return CycleNightClubClientGotoPlay