---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Microsoft-GXY.
--- DateTime: 2024/8/16 12:28
---
local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")
local UIView = require("Framework.UI.View") -- 当工具类使用
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper
local Random = CS.UnityEngine.Random
local CycleNightClubAIBlackBoard = GameTableDefine.CycleNightClubAIBlackBoard ---@type CycleNightClubAIBlackBoard
local ConfigMgr = GameTableDefine.ConfigMgr

local WALK_SPEED = 5.5
local RUN_SPEED = 10


---@class CycleNightClubClientQueue:AIStateBase
---@field m_owner CycleNightClubClient
local CycleNightClubClientQueue = Class("CycleNightClubClientQueue", AIStateBase)

function CycleNightClubClientQueue:ctor()
end

function CycleNightClubClientQueue:OnEnter(...)
    local actor = self.m_owner

    CycleNightClubAIBlackBoard:AddInstanceQueue(actor)
    self:MoveToQueuePos()
end

---移动到自己该到的位置
function CycleNightClubClientQueue:MoveToQueuePos()


    local actor = self.m_owner
    -- 播放动画
    actor.m_animator:Play(ActorDefine.AnimationNames.Walk)
    -- 寻路到排队点
    local speed = ConfigMgr.config_global.character_walk_v
    local pathTarget = CycleNightClubAIBlackBoard:GetActorQueuePos(self.m_owner)
    actor:CalculatePath(pathTarget, true, speed, Random.Range(1, 4.1), function()
        -- 播放动画
        actor.m_animator:Play(ActorDefine.AnimationNames.Idle)
        -- 设置位置和旋转
        actor.gameObject.transform.position = pathTarget
        --UnityHelper.RotateTowards(actor.gameObject.transform, Vector3(facPostion.x, self.parent.m_go.transform.position.y, facPostion.z))
    end)
    return
end

function CycleNightClubClientQueue:OnExit()
end

function CycleNightClubClientQueue:OnDestroy()
    self:OnExit()
end

return CycleNightClubClientQueue
