---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/6/27 15:11
---

local Class = require("Framework.Lua.Class")
local UIView = require("Framework.UI.View")

local GameTimer = GameTimer

local CycleToyTaskManager = GameTableDefine.CycleToyTaskManager
local FlyIconsUI = GameTableDefine.FlyIconsUI
local UnityHelper = CS.Common.Utils.UnityHelper
local CycleToyUnlockUI = GameTableDefine.CycleToyUnlockUI
local CycleToyBuildingUI = GameTableDefine.CycleToyBuildingUI
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local GameUIManager = GameTableDefine.GameUIManager

local TASK_ITEM_COUNT = 3

---@class CycleToyTaskUIView:UIBaseView
local CycleToyTaskUIView = Class("CycleToyTaskUIView", UIView)

---@type TaskUIItem
---@field rootGO UnityEngine.GameObject
---@field taskIconImage UnityEngine.UI.Image
---@field typeIconImage UnityEngine.UI.Image
---@field rewardIconImage UnityEngine.UI.Image
---@field rewardNumText UnityEngine.UI.TMPLocalization
---@field descText UnityEngine.UI.TMPLocalization
---@field rewardBtn UnityEngine.UI.Button
---@field isCompleteMark UnityEngine.GameObject
---@field jumpBtn UnityEngine.UI.Button
---@field allDone UnityEngine.GameObject
---@field taskConfig CycleIslandTaskConfig
---@field taskData CycleIslandTaskInfo
local TaskUIItem = {}

function CycleToyTaskUIView:ctor()

    self.m_taskData = nil ---@type CycleIslandTaskData

    self.m_exitBtn = nil ---@type UnityEngine.UI.Button
    self.m_bg_ExitBtn = nil ---@type UnityEngine.UI.Button
    self.m_taskUIItems = nil ---@type TaskUIItem[]
    self.m_currentModel = nil ---@type CycleToyModel

    self.super:ctor()
end

function CycleToyTaskUIView:OnEnter()
    self.m_currentModel = CycleInstanceDataManager:GetCurrentModel()
    self.m_taskUIItems = {}
    for i = 1, TASK_ITEM_COUNT do
        local taskUIItem = {} ---@type TaskUIItem
        self.m_taskUIItems[i] = taskUIItem
        local rootGO = self:GetGo("RootPanel/Task/temp_"..i)
        taskUIItem.rootGO = rootGO
        taskUIItem.taskIconImage = self:GetComp(rootGO,"main/bg/firstTaskIcon/icon","Image")
        taskUIItem.typeIconImage = self:GetComp(rootGO,"main/bg/firstTaskIcon/typeIcon","Image")
        --taskUIItem.rewardIconImage = self:GetComp(rootGO,"main/bg/info/reward/icon","Image")
        taskUIItem.haveNumText = self:GetComp(rootGO,"main/bg/haveAndNeed/have","TMPLocalization")
        taskUIItem.needNumText = self:GetComp(rootGO,"main/bg/haveAndNeed/need","TMPLocalization")
        taskUIItem.rewardNumText = self:GetComp(rootGO,"main/bg/info/reward/num","TMPLocalization")
        taskUIItem.descText = self:GetComp(rootGO,"main/bg/info/desc","TMPLocalization")
        taskUIItem.rewardBtn = self:GetComp(rootGO,"main/BTN/RewardBtn","Button")
        taskUIItem.isCompleteMark = self:GetGo(rootGO,"main/bg/bg_finish")
        taskUIItem.jumpBtn = self:GetComp(rootGO,"main/BTN/GotoBtn","Button")
        taskUIItem.allDone = self:GetGo(rootGO,"main/allDone")
        self:SetButtonClickHandler(taskUIItem.jumpBtn,function()
            if CycleInstanceDataManager:GetInstanceState(CycleInstanceDataManager.instance_id) ~= CycleInstanceDataManager.instanceState.isActive then
                GameTableDefine.CycleToySlotMachineUI:CloseView()
                self:DestroyModeUIObject()
                return
            end
            self:JumpBtnDown(taskUIItem)
        end)
        self:SetButtonClickHandler(taskUIItem.rewardBtn,function()
            self:RewardBtnDown(taskUIItem)
        end)
    end
    self.m_exitBtn = self:GetComp(self.m_uiObj,"RootPanel/quitBtn","Button")
    self.m_bg_ExitBtn = self:GetComp(self.m_uiObj,"BgCover","Button")
    self:SetButtonClickHandler(self.m_exitBtn,handler(self,self.OnExitBtnDown))
    self:SetButtonClickHandler(self.m_bg_ExitBtn,handler(self,self.OnExitBtnDown))
end

function CycleToyTaskUIView:OnExitBtnDown()
    self:DestroyModeUIObject()
end

function CycleToyTaskUIView:OnExit()
    if self.m_refreshTimer then
        GameTimer:StopTimer(self.m_refreshTimer)
        self.m_refreshTimer = nil
    end
    self.super:OnExit(self)
end

---@param taskUIItem TaskUIItem
function CycleToyTaskUIView:RewardBtnDown(taskUIItem)
    local taskConfig = taskUIItem.taskConfig
    local getReward = false
    if taskConfig.taskShowType == 1 then
        getReward = CycleToyTaskManager:CompleteType1Task(taskConfig.id)
    else
        getReward = CycleToyTaskManager:CompleteTask(taskConfig.id)
    end
    GameSDKs:TrackForeign("cy_task", { id = taskConfig.id})
    
    if getReward then
        --获取奖励
        local rewardValue = taskConfig.value
        self.m_currentModel:ChangeSlotCoin(rewardValue)
        GameSDKs:TrackForeign("cy_get_coin", { source = "任务完成", num = tonumber(rewardValue), taskID = tonumber(taskConfig.id) })

        local res = {} ---@type CycleFlyIconResInfo[]

        --拉霸机代币是30
        local resInfo = {itemType = 30,str = rewardValue} ---@type CycleFlyIconResInfo
        table.insert(res,resInfo)

        FlyIconsUI:SetCycleInstanceNum(res)

        if taskConfig.taskShowType == 1 then
            self:RefreshTaskInfo(taskUIItem,CycleToyTaskManager:GetType1TaskData())
        else
            self:RefreshTaskInfo(taskUIItem)
        end
    end
end

-----@param taskUIItem TaskUIItem
function CycleToyTaskUIView:JumpBtnDown(taskUIItem)
    self:JumpToTaskTarget(taskUIItem)
end

---刷新任务状态
---@param taskUIItem TaskUIItem
---@param taskData CycleIslandTaskInfo
function CycleToyTaskUIView:RefreshTaskInfo(taskUIItem,taskData)
    taskData = taskData or taskUIItem.taskData
    local taskID = taskData.taskID or 0
    local taskConfig = CycleToyTaskManager:GetTaskConfigByTaskID(taskID)
    taskUIItem.taskConfig = taskConfig
    taskUIItem.taskData = taskData
    if taskConfig then
        if taskConfig.icon then
            self:SetSprite(taskUIItem.taskIconImage,"UI_Common",taskConfig.icon)
        end
        if taskConfig.typeicon then
            self:SetSprite(taskUIItem.typeIconImage,"UI_Common",taskConfig.typeicon)
        end
        local descStr,haveStr,needStr,isComplete = CycleToyTaskManager:GetTaskShowValues(taskID)
        taskUIItem.descText.text = descStr
        taskUIItem.haveNumText.text = haveStr
        taskUIItem.needNumText.text = needStr

        taskUIItem.haveNumText.color = UnityHelper.GetColor(isComplete and "#24b256" or "#717895")

        taskUIItem.isCompleteMark:SetActive(isComplete)
        if isComplete then
            taskUIItem.rewardBtn.gameObject:SetActive(true)
            taskUIItem.rewardBtn.interactable = true

            taskUIItem.jumpBtn.gameObject:SetActive(false)
        else
            if taskUIItem.taskConfig.task_type == 1 or taskUIItem.taskConfig.task_type == 2 or taskUIItem.taskConfig.task_type == 5 then
                taskUIItem.rewardBtn.gameObject:SetActive(false)
                taskUIItem.rewardBtn.interactable = false

                taskUIItem.jumpBtn.gameObject:SetActive(true)
            else

                taskUIItem.rewardBtn.gameObject:SetActive(true)
                taskUIItem.rewardBtn.interactable = false

                taskUIItem.jumpBtn.gameObject:SetActive(false)
            end
        end

        taskUIItem.allDone:SetActive(false)
    else
        taskUIItem.allDone:SetActive(true)
    end
end

function CycleToyTaskUIView:Init()
    local taskData = CycleToyTaskManager:GetTaskData()
    self.m_taskData = taskData

    self:RefreshAllTaskInfo()

    if not self.m_refreshTimer then
        --定时刷新界面显示的值和是否能完成
        self.m_refreshTimer = GameTimer:CreateNewTimer(1,function()
            self:RefreshAllTaskInfo()
        end,true)
    end
end

function CycleToyTaskUIView:RefreshAllTaskInfo()
    --1特殊处理,如果1完成了就显示1，没完成就找个完成的显示
    self:RefreshTaskInfo(self.m_taskUIItems[1],CycleToyTaskManager:GetType1TaskData())

    for i = 2, TASK_ITEM_COUNT do
        self:RefreshTaskInfo(self.m_taskUIItems[i],self.m_taskData.currentTasks[i])
    end
end

---跳转到对应需要解锁的
function CycleToyTaskUIView:LocateRoom(roomID,furIndex)
    local curRoomData = self.m_currentModel.roomsData[roomID]
    if curRoomData then
        if curRoomData.state == 0 then
            --未解锁,显示解锁界面
            GameUIManager:SetEnableTouch(false)
            self.m_currentModel:LookAtSceneGO(roomID,nil,nil,nil,function()
                local unlock_room = self.m_currentModel.roomsConfig[roomID].unlock_room
                if self.m_currentModel:RoomIsUnlock(unlock_room) then
                    CycleToyUnlockUI:ShowUI(roomID)
                end
                GameUIManager:SetEnableTouch(true)
            end)
        elseif curRoomData.state == 1 then
            --在解锁中,显示悬浮进度，跳转到对应建筑
            self.m_currentModel:LookAtSceneGO(roomID)
        elseif curRoomData.state == 2 then
            GameUIManager:SetEnableTouch(false)
            self.m_currentModel:LookAtSceneGO(roomID,furIndex,nil,nil,function()
                GameUIManager:SetEnableTouch(true)
                --已解锁,显示RoomUI
                local curRoomCfg = self.m_currentModel.roomsConfig[roomID]
                if curRoomCfg then
                    if curRoomCfg.room_category == 1 then
                        CycleToyBuildingUI:ShowFactoryUI(roomID,furIndex)
                    elseif curRoomCfg.room_category == 2 or curRoomCfg.room_category == 3 then
                        CycleToyBuildingUI:ShowSupplyBuildingUI(roomID,furIndex)
                    else
                        --CycleIslandSellUI:ShowWharfUI(roomID,furIndex)
                    end
                end
            end)
        end
    end
end

---跳转到对应需要购买的家具
---@param taskConfig CycleIslandTaskConfig
function CycleToyTaskUIView:LocateFurniture(taskConfig)
    local furID,roomID = taskConfig.type2_fur_id,taskConfig.type2_fur_room
    self:LocateRoom(roomID,1)
end

---跳转到任务目标
---@param taskUIItem TaskUIItem
function CycleToyTaskUIView:JumpToTaskTarget(taskUIItem)
    local taskConfig = taskUIItem.taskConfig
    if taskConfig then
        --CycleToyTaskManager:FakeSetTaskAsComplete(taskConfig.id)
        --self:RefreshTaskInfo(taskUIItem,taskUIItem.taskData)
        if taskConfig.task_type == 1 then
            --房间修建
            self:LocateRoom(taskConfig.type1_roomID)
        elseif taskConfig.task_type == 2 then
            --购买设施
            self:LocateFurniture(taskConfig)
        elseif taskConfig.task_type == 5 then
            self:DestroyModeUIObject(false,function()
                if not GameTableDefine.CycleToySlotMachineUI.m_view then
                    GameTableDefine.CycleToySlotMachineUI:OpenView()
                    -- GameSDKs:TrackForeign("button_event", { slot_task = 1})
                end
            end)
            return
        end
        if taskConfig.task_type ~= 5 then
            if GameTableDefine.CycleToySlotMachineUI.m_view then
                GameTableDefine.CycleToySlotMachineUI:CloseView()
            end
        end
        self:DestroyModeUIObject()
    end
end



return CycleToyTaskUIView