---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/6/27 15:11
---

---@class CycleToyTaskUI
local CycleToyTaskUI = GameTableDefine.CycleToyTaskUI

local GameUIManager = GameTableDefine.GameUIManager
local ConfigMgr = GameTableDefine.ConfigMgr
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager

function CycleToyTaskUI:GetView()
    self.m_view = GameUIManager:SafeOpenUI(ENUM_GAME_UITYPE.CYCLE_TOY_TASK_UI, self.m_view, require("GamePlay.CycleInstance.Toy.UI.CycleToyTaskUIView"), self, self.CloseView)
    return self.m_view
end

function CycleToyTaskUI:CloseView()
    GameUIManager:CloseUI(ENUM_GAME_UITYPE.CYCLE_TOY_TASK_UI)
    self.m_view = nil
    collectgarbage("collect")
end

function CycleToyTaskUI:OpenView()
    self:GetView()
    self.m_view:Invoke("Init")
end

---外界可调用关闭界面
function CycleToyTaskUI:Exit()
    if self.m_view then
        self.m_view:Invoke("DestroyModeUIObject")
    end
end