---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/7/1 14:13
---

local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local CfgMgr = GameTableDefine.ConfigMgr
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local CycleInstanceAIBlackBoard = GameTableDefine.CycleInstanceAIBlackBoard
local UIView = require("Framework.UI.View") -- 当工具类使用
local Random = CS.UnityEngine.Random
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")

local WALK_SPEED = 5.5
local RUN_SPEED = 15


---@class CycleInstanceWorkerRunToSleepQueue:AIStateBase
---@field m_owner CycleInstanceWorkerClass
local CycleInstanceWorkerRunToSleepQueue = Class("CycleInstanceWorkerRunToSleepQueue",AIStateBase)

function CycleInstanceWorkerRunToSleepQueue:ctor()
    self.m_timerID = nil
    self.m_speed = nil
end

function CycleInstanceWorkerRunToSleepQueue:OnEnter(...)
    local actor = select(1, ...)
    --local roomID = select(2, ...)
    --local sleep = roomID ~= nil
    local stateMachine = actor.m_stateMachine
    local speed = RUN_SPEED + Random.Range(-1.1, 1.1)

    --播放动画
    actor:SetAnimator(PERSON_ACTION.RUN)
    -- 显示气泡
    actor:SetTheDisplayOfBubbles()

    local currentModel = CycleInstanceDataManager:GetCurrentModel()
    local isReserved = self:IsReservedSeat(actor) --是否预约了座位，如果预约上了,那有座位到座位上去,没座位应该是有问题的
    if isReserved then
        local actorSeatBind = currentModel.actorSeatBind[currentModel.TimeTypeEnum.sleep]
        local actorData = actor.data
        local reserveRoomID = actorSeatBind[actorData.roomID][actorData.furnitureIndex]
        local roomGO = currentModel:GetRoomGameObjectByID(reserveRoomID)
        local queuePos = UIView:GetTrans(roomGO, "QueuePoint")
        actor:CalculatePath(
                queuePos,
                true,
                speed,
                Random.Range(1.1, 4.1),
                function()
                    local roomId, furIndex, index = CycleInstanceAIBlackBoard:GetActorBindSeat(reserveRoomID,actor)
                    if not index then --有其他工人在这个工人来的路上把这个床位抢了
                        actor:TryTransState(
                                function()
                                    stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleInstanceWorkerRunToSleepQueue, actor )
                                end
                        )
                    else
                        actor:TryTransState(
                                function()
                                    stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleInstanceWorkerWalkToSleep, actor, roomId, furIndex, index)
                                end
                        )
                    end
                end)
    else--没预约的人先找个最近的房间走过去
        local targetRoomID,TargetRoomGO = actor:GetNearestHouse(2)
        local queuePos = UIView:GetTrans(TargetRoomGO, "QueuePoint")
        actor:CalculatePath(
                queuePos,
                true,
                speed,
                Random.Range(1.1, 4.1),
                function ()
                    --到排队位置后再判断是否有位置可以进入
                    if currentModel.timeType == currentModel.TimeTypeEnum.sleep then
                        if currentModel:FindSleepSeat(actor) then
                            local actorSeatBind = currentModel.actorSeatBind[currentModel.TimeTypeEnum.sleep]
                            local actorData = actor.data
                            if actorSeatBind[actorData.roomID] and actorSeatBind[actorData.roomID][actorData.furnitureIndex] then
                                stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleInstanceWorkerRunToSleepQueue, actor ,actorSeatBind[actorData.roomID][actorData.furnitureIndex])
                            else
                                error("不应该找不到座位")
                                --stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleInstanceWorkerQueueUp, actor, targetRoomID, TargetRoomGO )
                            end
                        else
                            error("不应该找不到座位")
                            --stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleInstanceWorkerQueueUp, actor, targetRoomID, TargetRoomGO )
                        end
                    end
                end)
    end
end

function CycleInstanceWorkerRunToSleepQueue:IsReservedSeat(actor)

    local currentModel = CycleInstanceDataManager:GetCurrentModel()
    local actorSeatBind = currentModel.actorSeatBind[currentModel.TimeTypeEnum.sleep]
    local actorData = actor.data
    if not actorSeatBind then
        currentModel:WorkerAttrRevert(currentModel.TimeTypeEnum.sleep, true)
    end
    if actorSeatBind[actorData.roomID] and actorSeatBind[actorData.roomID][actorData.furnitureIndex] then
        return true
    else
        return false
    end
end

function CycleInstanceWorkerRunToSleepQueue:OnExit()

end

return CycleInstanceWorkerRunToSleepQueue