---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/7/1 14:13
---
local Class = require("Framework.Lua.Class")
local AIStateBase = require("CodeRefactoring.AI.StateMachines.AIStateBase")
local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local CfgMgr = GameTableDefine.ConfigMgr
local CycleInstanceDataManager = GameTableDefine.CycleInstanceDataManager
local CycleInstanceAIBlackBoard = GameTableDefine.CycleInstanceAIBlackBoard
local UIView = require("Framework.UI.View") -- 当工具类使用
local Random = CS.UnityEngine.Random
local Vector3 = CS.UnityEngine.Vector3
local UnityHelper = CS.Common.Utils.UnityHelper
local PERSON_ACTION = require("CodeRefactoring.Actor.PersonActionDefine")

local WALK_SPEED = 5.5
local RUN_SPEED = 15


---@class CycleInstanceWorkerWalkToSleep:AIStateBase
---@field m_owner CycleInstanceWorkerClass
local CycleInstanceWorkerWalkToSleep = Class("CycleInstanceWorkerWalkToSleep",AIStateBase)


function CycleInstanceWorkerWalkToSleep:ctor()
    self.m_timerID = nil
    self.m_speed = nil
end

function CycleInstanceWorkerWalkToSleep:OnEnter(...)
    local actor = select(1, ...)
    local roomID = select(2, ...)
    local furIndex = select(3, ...)
    local Index = select(4, ...)
    local stateMachine = actor.m_stateMachine
    local furGO = CycleInstanceDataManager:GetCurrentModel():GetFurGameObject(roomID, furIndex)
    local workPosName = "workPos_"..Index
    local pathTarget = UIView:GetTrans(furGO, workPosName)
    local speed = WALK_SPEED + Random.Range(-1.1, 1.1)

    --设置寻路
    actor:CalculatePath(pathTarget, true, speed, Random.Range(1.1, 4.1), function()
        actor:TryTransState(function()
            stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleInstanceWorkerSleep, actor, roomID, pathTarget)
        end)
    end)
    --播放动画
    actor:SetAnimator(PERSON_ACTION.WALK)
    -- 显示气泡
    actor:SetTheDisplayOfBubbles("sleep", roomID)
end

function CycleInstanceWorkerWalkToSleep:OnExit()

end

return CycleInstanceWorkerWalkToSleep