---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2024/8/5 16:07
---

local Class = require("Framework.Lua.Class")
local ActorBase = require("CodeRefactoring.Actor.ActorBase")
---@class CycleInstanceBaseActor:ActorBase
---@field super ActorBase
local CycleInstanceBaseActor = Class("CycleInstanceBaseActor",ActorBase)

local ActorDefine = require("CodeRefactoring.Actor.ActorDefine")
local Animator = CS.UnityEngine.Animator
local PersonStateMachine = require("CodeRefactoring.AI.StateMachines.PersonStateMachine")

function CycleInstanceBaseActor:ctor()
    self.super.ctor(self)
    self.initialized = false
    self.m_type = ActorDefine.ActorType.CycleInstanceBaseActor
    self.m_go = nil
    self.m_animator = nil ---@type UnityEngine.Animator
end

function CycleInstanceBaseActor:Init(id, go, actorData, pos, rot,isBuy)
    self.m_animator = go:GetComponent(typeof(Animator))
    self.data = actorData
    --优化Animator性能
    if not self.m_animator:IsNull() and not self.m_animator.applyRootMotion then
        self.m_animator.cullingMode = CS.UnityEngine.AnimatorCullingMode.CullUpdateTransforms
    end

    if not self.m_stateMachine then
        self.m_stateMachine = PersonStateMachine.create()   ---@type PersonStateMachine
        self.m_stateMachine:SetOwner(self)
        self:TryTransState(function ()
            self.m_stateMachine:ChangeState(ActorDefine.CycleInstanceState.CycleInstanceBaseActorWorkState, self,isBuy)
        end)
    end
    self.super.Init(self, id, go, actorData, self.m_stateMachine, pos, rot)
    self.data.type = "CycleInstanceBaseActor"
    self.m_go = go
    self.initialized = true
    --self:SetDoorTrigger()
end

--设置气泡的显示
function CycleInstanceBaseActor:SetTheDisplayOfBubbles(typeB, interactiveRoomId)

end

--设置与门交互的Trigger
--function CycleInstanceBaseActor:SetDoorTrigger()
--    local animName = {"DoorOpenAnim", "ToiletDoor_open"}
--    local animIndex = 1
--    local enterFunc = function(responseGo, activatorGo, outRoom)
--        local coll = responseGo:GetComponent("ColliderResponse")
--        local anim = coll:GetDoorAnim()
--        if not anim or coll:GetTriggerCount() > 1 then
--            return
--        end
--
--        local lastAni = 1
--        local currAni = AnimationUtil.GetAnimationState(anim, animName[lastAni])
--        if not currAni then
--            lastAni = 2
--            currAni = AnimationUtil.GetAnimationState(anim, animName[lastAni])
--        end
--        local needAni = outRoom == true and "_revert" or ""
--
--        if anim.isPlaying then
--            return
--        end
--
--        AnimationUtil.Play(anim, animName[lastAni] .. needAni, function()
--            AnimationUtil.GotoAndStop(anim, animName[lastAni] .. needAni, "KEY_FRAME_CLOSE_POINT")--放完停在末尾,让isPlay为true
--        end)
--
--        GameTableDefine.CycleInstanceDataManager:GetCurrentModel():MakeDoorTimer(responseGo, function()--几秒后没人自动关闭
--            if coll and not CS.UnityEngine.Object.ReferenceEquals( coll, nil ) and coll:GetTriggerCount() == 0 and anim then
--                AnimationUtil.Play(anim, animName[lastAni] .. needAni, nil, -1, "KEY_FRAME_SECOND")
--                return true
--            elseif not anim then
--                return 1--切换场景的时候没了...或者其他原因导致的错误
--            end
--
--            return false
--        end)
--    end
--    ColliderResponse:SetActivatorTriggerEventOnEnter(ColliderResponse.TYPE_OPEN_DOOR, self.m_go, enterFunc)
--end

return CycleInstanceBaseActor