local config_activity = {
	[1001] = {
		["addition"] = 0,
		["chance"] = 10,
		["count"] = 1,
		["id"] = 1001,
		["is_goto"] = 0,
		["reward"] = 5,
		["reward_activity"] = 4,
		["task_desc"] = "TXT_ACTIVITY_TASK_1",
		["threhold"] = 30,
		["threhold_activity"] = 40,
	}
	,
	[1002] = {
		["addition"] = 0,
		["chance"] = 25,
		["count"] = 1,
		["id"] = 1002,
		["is_goto"] = 0,
		["reward"] = 5,
		["reward_activity"] = 6,
		["task_desc"] = "TXT_ACTIVITY_TASK_2",
		["threhold"] = 3,
		["threhold_activity"] = 3,
	}
	,
	[1003] = {
		["addition"] = 0,
		["chance"] = 100,
		["count"] = 3,
		["id"] = 1003,
		["is_goto"] = 1,
		["reward"] = 10,
		["reward_activity"] = 4,
		["task_desc"] = "TXT_ACTIVITY_TASK_3",
		["threhold"] = 1,
		["threhold_activity"] = 1,
	}
	,
	[1004] = {
		["addition"] = 0,
		["chance"] = 0,
		["count"] = 1,
		["id"] = 1004,
		["is_goto"] = 0,
		["reward"] = 10,
		["reward_activity"] = 4,
		["task_desc"] = "TXT_ACTIVITY_TASK_4",
		["threhold"] = 3,
		["threhold_activity"] = 4,
	}
	,
	[1005] = {
		["addition"] = 0,
		["chance"] = 0,
		["count"] = 1,
		["id"] = 1005,
		["is_goto"] = 0,
		["reward"] = 10,
		["reward_activity"] = 2,
		["task_desc"] = "TXT_ACTIVITY_TASK_5",
		["threhold"] = 1,
		["threhold_activity"] = 1,
	}
	,
	[1006] = {
		["addition"] = 0,
		["chance"] = 0,
		["count"] = 1,
		["id"] = 1006,
		["is_goto"] = 0,
		["reward"] = 20,
		["reward_activity"] = 10,
		["task_desc"] = "TXT_ACTIVITY_TASK_6",
		["threhold"] = 10,
		["threhold_activity"] = 10,
	}
	,
	[1007] = {
		["addition"] = 0,
		["chance"] = 100,
		["count"] = 3,
		["id"] = 1007,
		["is_goto"] = 1,
		["reward"] = 20,
		["reward_activity"] = 8,
		["task_desc"] = "TXT_ACTIVITY_TASK_7",
		["threhold"] = 2,
		["threhold_activity"] = 2,
	}
	,
	[1008] = {
		["addition"] = 0,
		["chance"] = 100,
		["count"] = 7,
		["id"] = 1008,
		["is_goto"] = 1,
		["reward"] = 20,
		["reward_activity"] = 10,
		["task_desc"] = "TXT_ACTIVITY_TASK_8",
		["threhold"] = 1,
		["threhold_activity"] = 2,
	}
	,
}
return config_activity