local config_popup = {
	[1009] = {
		["bg_title"] = "banner_growthkit_bottom_spirit3",
		["duration"] = 0,
		["id"] = 1010,
		["light_title"] = "banner_growthkit_light3",
		["note"] = "免广告",
		["offvalue"] = 0,
		["shopId"] = 1009,
		["timegroup"] = 0,
		["timelimit"] = 0,
		["title"] = "TXT_POPUP_NOAD",
	}
	,
	[1016] = {
		["bg_title"] = "banner_growthkit_bottom_spirit",
		["duration"] = 0,
		["id"] = 1021,
		["light_title"] = "banner_growthkit_light",
		["note"] = "钻石月卡",
		["offvalue"] = 0.77,
		["shopId"] = 1016,
		["timegroup"] = 0,
		["timelimit"] = 0,
		["title"] = "TXT_POPUP_MONTHDIAMOND",
	}
	,
	[1037] = {
		["bg_title"] = "banner_growthkit_bottom_spirit",
		["duration"] = 259200,
		["id"] = 1007,
		["light_title"] = "banner_growthkit_light",
		["note"] = "新手礼包1",
		["offvalue"] = 0.86,
		["shopId"] = 1037,
		["timeLimit"] = true,
		["timegroup"] = 1,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_STARTERPACK1",
	}
	,
	[1038] = {
		["bg_title"] = "banner_growthkit_bottom_spirit6",
		["duration"] = 172800,
		["id"] = 1011,
		["light_title"] = "banner_growthkit_light6",
		["note"] = "成长礼包1",
		["offvalue"] = 0.8,
		["shopId"] = 1038,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK1",
	}
	,
	[1039] = {
		["bg_title"] = "banner_growthkit_bottom_spirit5",
		["duration"] = 172800,
		["id"] = 1012,
		["light_title"] = "banner_growthkit_light5",
		["note"] = "成长礼包2",
		["offvalue"] = 0.8,
		["shopId"] = 1039,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK2",
	}
	,
	[1040] = {
		["bg_title"] = "banner_growthkit_bottom_spirit5",
		["duration"] = 172800,
		["id"] = 1013,
		["light_title"] = "banner_growthkit_light5",
		["note"] = "成长礼包3",
		["offvalue"] = 0.8,
		["shopId"] = 1040,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK3",
	}
	,
	[1041] = {
		["bg_title"] = "banner_growthkit_bottom_spirit6",
		["duration"] = 172800,
		["id"] = 1014,
		["light_title"] = "banner_growthkit_light6",
		["note"] = "成长礼包4",
		["offvalue"] = 0.8,
		["shopId"] = 1041,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK4",
	}
	,
	[1042] = {
		["bg_title"] = "banner_growthkit_bottom_spirit9",
		["duration"] = 172800,
		["id"] = 1015,
		["light_title"] = "banner_growthkit_light9",
		["note"] = "成长礼包5",
		["offvalue"] = 0.8,
		["shopId"] = 1042,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK5",
	}
	,
	[1043] = {
		["bg_title"] = "banner_growthkit_bottom_spirit7",
		["duration"] = 172800,
		["id"] = 1016,
		["light_title"] = "banner_growthkit_light7",
		["note"] = "成长礼包6",
		["offvalue"] = 0.8,
		["shopId"] = 1043,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK6",
	}
	,
	[1044] = {
		["bg_title"] = "banner_growthkit_bottom_spirit8",
		["duration"] = 172800,
		["id"] = 1017,
		["light_title"] = "banner_growthkit_light8",
		["note"] = "成长礼包7",
		["offvalue"] = 0.8,
		["shopId"] = 1044,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK7",
	}
	,
	[1045] = {
		["bg_title"] = "banner_growthkit_bottom_spirit6",
		["duration"] = 172800,
		["id"] = 1018,
		["light_title"] = "banner_growthkit_light6",
		["note"] = "成长礼包8",
		["offvalue"] = 0.8,
		["shopId"] = 1045,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK8",
	}
	,
	[1046] = {
		["bg_title"] = "banner_growthkit_bottom_spirit10",
		["duration"] = 172800,
		["id"] = 1019,
		["light_title"] = "banner_growthkit_light10",
		["note"] = "成长礼包9",
		["offvalue"] = 0.8,
		["shopId"] = 1046,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK9",
	}
	,
	[1053] = {
		["bg_title"] = "banner_growthkit_bottom_spirit5",
		["duration"] = 0,
		["id"] = 1020,
		["light_title"] = "banner_growthkit_light5",
		["note"] = "经理大礼包",
		["offvalue"] = 0.5,
		["shopId"] = 1053,
		["timegroup"] = 0,
		["timelimit"] = 0,
		["title"] = "TXT_POPUP_MANAGERPACK",
	}
	,
	[1066] = {
		["bg_title"] = "banner_growthkit_bottom_spirit5",
		["duration"] = 0,
		["id"] = 1022,
		["light_title"] = "banner_growthkit_light5",
		["note"] = "宠物大礼包",
		["offvalue"] = 0.5,
		["shopId"] = 1066,
		["timegroup"] = 0,
		["timelimit"] = 0,
		["title"] = "TXT_POPUP_PETPACK",
	}
	,
	[1068] = {
		["bg_title"] = "banner_growthkit_bottom_spirit3",
		["duration"] = 0,
		["id"] = 1009,
		["light_title"] = "banner_growthkit_light3",
		["note"] = "免广告大礼包",
		["offvalue"] = 0.5,
		["shopId"] = 1068,
		["timegroup"] = 0,
		["timelimit"] = 0,
		["title"] = "TXT_POPUP_ADFREEPACK",
	}
	,
	[1094] = {
		["bg_title"] = "banner_growthkit_bottom_spirit6",
		["duration"] = 172800,
		["id"] = 1006,
		["light_title"] = "banner_growthkit_light6",
		["note"] = "成长礼包10",
		["offvalue"] = 0.8,
		["shopId"] = 1094,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK10",
	}
	,
	[1189] = {
		["bg_title"] = "banner_growthkit_bottom_spirit",
		["duration"] = 259200,
		["id"] = 1008,
		["light_title"] = "banner_growthkit_light",
		["note"] = "新手礼包2",
		["offvalue"] = 0.86,
		["shopId"] = 1189,
		["timeLimit"] = true,
		["timegroup"] = 1,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_STARTERPACK2",
	}
	,
	[1190] = {
		["bg_title"] = "banner_growthkit_bottom_spirit2",
		["duration"] = 172800,
		["id"] = 1005,
		["light_title"] = "banner_growthkit_light2",
		["note"] = "成长礼包11",
		["offvalue"] = 0.5,
		["shopId"] = 1190,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK11",
	}
	,
	[1191] = {
		["bg_title"] = "banner_growthkit_bottom_spirit1",
		["duration"] = 172800,
		["id"] = 1004,
		["light_title"] = "banner_growthkit_light1",
		["note"] = "成长礼包12",
		["offvalue"] = 0.5,
		["shopId"] = 1191,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK12",
	}
	,
	[1192] = {
		["bg_title"] = "banner_growthkit_bottom_spirit4",
		["duration"] = 172800,
		["id"] = 1003,
		["light_title"] = "banner_growthkit_light4",
		["note"] = "成长礼包13",
		["offvalue"] = 0.5,
		["shopId"] = 1192,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK13",
	}
	,
	[1193] = {
		["bg_title"] = "banner_growthkit_bottom_spirit",
		["duration"] = 172800,
		["id"] = 1002,
		["light_title"] = "banner_growthkit_light",
		["note"] = "成长礼包14",
		["offvalue"] = 0.5,
		["shopId"] = 1193,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK14",
	}
	,
	[1194] = {
		["bg_title"] = "banner_growthkit_bottom_spirit3",
		["duration"] = 172800,
		["id"] = 1001,
		["light_title"] = "banner_growthkit_light3",
		["note"] = "成长礼包15",
		["offvalue"] = 0.5,
		["shopId"] = 1194,
		["timeLimit"] = true,
		["timegroup"] = 0,
		["timelimit"] = 1,
		["title"] = "TXT_POPUP_PREMIUMPACK15",
	}
	,
}
return config_popup