local config_chat_condition = {
	[1] = {
		["chatId"] = 1,
		["condition"] = 100,
		["id"] = 1,
		["name"] = "moveScene",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[2] = {
		["chatId"] = 2,
		["condition"] = 200,
		["id"] = 2,
		["name"] = "moveScene",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[3] = {
		["chatId"] = 3,
		["condition"] = 300,
		["id"] = 3,
		["name"] = "moveScene",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[4] = {
		["chatId"] = 4,
		["condition"] = 400,
		["id"] = 4,
		["name"] = "moveScene",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[5] = {
		["chatId"] = 5,
		["condition"] = 500,
		["id"] = 5,
		["name"] = "moveScene",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[6] = {
		["chatId"] = 6,
		["condition"] = 6,
		["id"] = 6,
		["name"] = "idle",
		["place"] = 1,
		["timeLimit"] = 0,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[7] = {
		["chatId"] = 7,
		["condition"] = 7,
		["id"] = 7,
		["name"] = "idle",
		["place"] = 1,
		["timeLimit"] = 0,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[8] = {
		["chatId"] = 8,
		["condition"] = 8,
		["id"] = 8,
		["name"] = "idle",
		["place"] = 1,
		["timeLimit"] = 0,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[9] = {
		["chatId"] = 9,
		["condition"] = 1,
		["id"] = 9,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[10] = {
		["chatId"] = 10,
		["condition"] = 2,
		["id"] = 10,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[11] = {
		["chatId"] = 11,
		["condition"] = 3,
		["id"] = 11,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[12] = {
		["chatId"] = 12,
		["condition"] = 4,
		["id"] = 12,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[13] = {
		["chatId"] = 13,
		["condition"] = 5,
		["id"] = 13,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[14] = {
		["chatId"] = 14,
		["condition"] = 6,
		["id"] = 14,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[15] = {
		["chatId"] = 15,
		["condition"] = 7,
		["id"] = 15,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[16] = {
		["chatId"] = 16,
		["condition"] = 8,
		["id"] = 16,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[17] = {
		["chatId"] = 17,
		["condition"] = 9,
		["id"] = 17,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[18] = {
		["chatId"] = 18,
		["condition"] = 10,
		["id"] = 18,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[19] = {
		["chatId"] = 19,
		["condition"] = 11,
		["id"] = 19,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[20] = {
		["chatId"] = 20,
		["condition"] = 12,
		["id"] = 20,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[21] = {
		["chatId"] = 21,
		["condition"] = 13,
		["id"] = 21,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[22] = {
		["chatId"] = 22,
		["condition"] = 14,
		["id"] = 22,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[23] = {
		["chatId"] = 23,
		["condition"] = 15,
		["id"] = 23,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[24] = {
		["chatId"] = 24,
		["condition"] = 16,
		["id"] = 24,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[25] = {
		["chatId"] = 25,
		["condition"] = 17,
		["id"] = 25,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[26] = {
		["chatId"] = 26,
		["condition"] = 18,
		["id"] = 26,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[27] = {
		["chatId"] = 27,
		["condition"] = 19,
		["id"] = 27,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[28] = {
		["chatId"] = 28,
		["condition"] = 20,
		["id"] = 28,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[29] = {
		["chatId"] = 29,
		["condition"] = 21,
		["id"] = 29,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[30] = {
		["chatId"] = 30,
		["condition"] = 22,
		["id"] = 30,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[31] = {
		["chatId"] = 31,
		["condition"] = 23,
		["id"] = 31,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[32] = {
		["chatId"] = 32,
		["condition"] = 24,
		["id"] = 32,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[33] = {
		["chatId"] = 33,
		["condition"] = 25,
		["id"] = 33,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[34] = {
		["chatId"] = 34,
		["condition"] = 26,
		["id"] = 34,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[35] = {
		["chatId"] = 35,
		["condition"] = 27,
		["id"] = 35,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[36] = {
		["chatId"] = 36,
		["condition"] = 28,
		["id"] = 36,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[37] = {
		["chatId"] = 37,
		["condition"] = 29,
		["id"] = 37,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[38] = {
		["chatId"] = 38,
		["condition"] = 30,
		["id"] = 38,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[39] = {
		["chatId"] = 39,
		["condition"] = 31,
		["id"] = 39,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[40] = {
		["chatId"] = 40,
		["condition"] = 32,
		["id"] = 40,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[41] = {
		["chatId"] = 41,
		["condition"] = 33,
		["id"] = 41,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[42] = {
		["chatId"] = 42,
		["condition"] = 34,
		["id"] = 42,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[43] = {
		["chatId"] = 43,
		["condition"] = 35,
		["id"] = 43,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[44] = {
		["chatId"] = 44,
		["condition"] = 36,
		["id"] = 44,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[45] = {
		["chatId"] = 45,
		["condition"] = 37,
		["id"] = 45,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[46] = {
		["chatId"] = 46,
		["condition"] = 38,
		["id"] = 46,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[47] = {
		["chatId"] = 47,
		["condition"] = 39,
		["id"] = 47,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[48] = {
		["chatId"] = 48,
		["condition"] = 40,
		["id"] = 48,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[49] = {
		["chatId"] = 49,
		["condition"] = 41,
		["id"] = 49,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[50] = {
		["chatId"] = 50,
		["condition"] = 42,
		["id"] = 50,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[51] = {
		["chatId"] = 51,
		["condition"] = 43,
		["id"] = 51,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[52] = {
		["chatId"] = 52,
		["condition"] = 44,
		["id"] = 52,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[53] = {
		["chatId"] = 53,
		["condition"] = 45,
		["id"] = 53,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[54] = {
		["chatId"] = 54,
		["condition"] = 46,
		["id"] = 54,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[55] = {
		["chatId"] = 55,
		["condition"] = 47,
		["id"] = 55,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[56] = {
		["chatId"] = 56,
		["condition"] = 48,
		["id"] = 56,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[57] = {
		["chatId"] = 57,
		["condition"] = 49,
		["id"] = 57,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[58] = {
		["chatId"] = 58,
		["condition"] = 50,
		["id"] = 58,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[59] = {
		["chatId"] = 59,
		["condition"] = 51,
		["id"] = 59,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[60] = {
		["chatId"] = 60,
		["condition"] = 52,
		["id"] = 60,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[61] = {
		["chatId"] = 61,
		["condition"] = 53,
		["id"] = 61,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[62] = {
		["chatId"] = 62,
		["condition"] = 54,
		["id"] = 62,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[63] = {
		["chatId"] = 63,
		["condition"] = 55,
		["id"] = 63,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[64] = {
		["chatId"] = 64,
		["condition"] = 56,
		["id"] = 64,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[65] = {
		["chatId"] = 65,
		["condition"] = 57,
		["id"] = 65,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[66] = {
		["chatId"] = 66,
		["condition"] = 58,
		["id"] = 66,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[67] = {
		["chatId"] = 67,
		["condition"] = 59,
		["id"] = 67,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[68] = {
		["chatId"] = 68,
		["condition"] = 60,
		["id"] = 68,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[69] = {
		["chatId"] = 69,
		["condition"] = 61,
		["id"] = 69,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[70] = {
		["chatId"] = 70,
		["condition"] = 62,
		["id"] = 70,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[71] = {
		["chatId"] = 71,
		["condition"] = 63,
		["id"] = 71,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[72] = {
		["chatId"] = 72,
		["condition"] = 64,
		["id"] = 72,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[73] = {
		["chatId"] = 73,
		["condition"] = 65,
		["id"] = 73,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[74] = {
		["chatId"] = 74,
		["condition"] = 66,
		["id"] = 74,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[75] = {
		["chatId"] = 75,
		["condition"] = 67,
		["id"] = 75,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[76] = {
		["chatId"] = 76,
		["condition"] = 68,
		["id"] = 76,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[77] = {
		["chatId"] = 77,
		["condition"] = 69,
		["id"] = 77,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[78] = {
		["chatId"] = 78,
		["condition"] = 1,
		["id"] = 78,
		["name"] = "company",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[79] = {
		["chatId"] = 79,
		["condition"] = 2,
		["id"] = 79,
		["name"] = "company",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[80] = {
		["chatId"] = 80,
		["condition"] = 3,
		["id"] = 80,
		["name"] = "company",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[81] = {
		["chatId"] = 81,
		["condition"] = 10001,
		["id"] = 81,
		["name"] = "buyHouse",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[82] = {
		["chatId"] = 82,
		["condition"] = 1,
		["id"] = 82,
		["name"] = "other",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[83] = {
		["chatId"] = 83,
		["condition"] = 70,
		["id"] = 83,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[96] = {
		["chatId"] = 96,
		["condition"] = 75,
		["id"] = 96,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[97] = {
		["chatId"] = 97,
		["condition"] = 76,
		["id"] = 97,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[98] = {
		["chatId"] = 98,
		["condition"] = 77,
		["id"] = 98,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[99] = {
		["chatId"] = 99,
		["condition"] = 78,
		["id"] = 99,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[100] = {
		["chatId"] = 100,
		["condition"] = 79,
		["id"] = 100,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[101] = {
		["chatId"] = 101,
		["condition"] = 80,
		["id"] = 101,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[102] = {
		["chatId"] = 102,
		["condition"] = 81,
		["id"] = 102,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[103] = {
		["chatId"] = 103,
		["condition"] = 82,
		["id"] = 103,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[104] = {
		["chatId"] = 104,
		["condition"] = 83,
		["id"] = 104,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[105] = {
		["chatId"] = 105,
		["condition"] = 84,
		["id"] = 105,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[106] = {
		["chatId"] = 106,
		["condition"] = 85,
		["id"] = 106,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[107] = {
		["chatId"] = 107,
		["condition"] = 86,
		["id"] = 107,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[108] = {
		["chatId"] = 108,
		["condition"] = 87,
		["id"] = 108,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[109] = {
		["chatId"] = 109,
		["condition"] = 88,
		["id"] = 109,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[110] = {
		["chatId"] = 110,
		["condition"] = 89,
		["id"] = 110,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[111] = {
		["chatId"] = 111,
		["condition"] = 36,
		["id"] = 111,
		["name"] = "buyCar",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[112] = {
		["chatId"] = 112,
		["condition"] = 38,
		["id"] = 112,
		["name"] = "buyCar",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[113] = {
		["chatId"] = 113,
		["condition"] = 40,
		["id"] = 113,
		["name"] = "buyCar",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[114] = {
		["chatId"] = 114,
		["condition"] = 35,
		["id"] = 114,
		["name"] = "buyCar",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[115] = {
		["chatId"] = 115,
		["condition"] = 37,
		["id"] = 115,
		["name"] = "buyCar",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[116] = {
		["chatId"] = 116,
		["condition"] = 39,
		["id"] = 116,
		["name"] = "buyCar",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[117] = {
		["chatId"] = 117,
		["condition"] = 100,
		["id"] = 117,
		["name"] = "moveScene",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[118] = {
		["cd"] = 86400,
		["chatId"] = 118,
		["condition"] = 3,
		["id"] = 118,
		["name"] = "companyUpgrade",
		["place"] = 1,
		["timeLimit"] = 0,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[119] = {
		["chatId"] = 119,
		["condition"] = 42,
		["id"] = 119,
		["name"] = "buyCar",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[120] = {
		["chatId"] = 120,
		["condition"] = 44,
		["id"] = 120,
		["name"] = "buyCar",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[121] = {
		["chatId"] = 121,
		["condition"] = 46,
		["id"] = 121,
		["name"] = "buyCar",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[122] = {
		["chatId"] = 122,
		["condition"] = 90,
		["id"] = 122,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[123] = {
		["chatId"] = 123,
		["condition"] = 91,
		["id"] = 123,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
	[124] = {
		["chatId"] = 124,
		["condition"] = 92,
		["id"] = 124,
		["name"] = "companyMax",
		["place"] = 1,
		["timeLimit"] = 1,
		["timeSetting"] = 0,
		["triggerType"] = 3,
	}
	,
}
return config_chat_condition