local config_cy_instance_skill = {
	[4] = {
		[1] = {
			[0] = {
				["buff"] = 1,
				["id"] = 1,
				["instance_id"] = 4,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 2,
				["instance_id"] = 4,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[2] = {
				["buff"] = "1.5805",
				["id"] = 3,
				["instance_id"] = 4,
				["res"] = 5,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[3] = {
				["buff"] = "2.325275",
				["id"] = 4,
				["instance_id"] = 4,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[4] = {
				["buff"] = "3.47967625",
				["id"] = 5,
				["instance_id"] = 4,
				["res"] = 11,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[5] = {
				["buff"] = "5.268998188",
				["id"] = 6,
				["instance_id"] = 4,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[6] = {
				["buff"] = "8.042447191",
				["id"] = 7,
				["instance_id"] = 4,
				["res"] = 13,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[7] = {
				["buff"] = "12.34129315",
				["id"] = 8,
				["instance_id"] = 4,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[8] = {
				["buff"] = "19.00450438",
				["id"] = 9,
				["instance_id"] = 4,
				["res"] = 15,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[9] = {
				["buff"] = "29.33248178",
				["id"] = 10,
				["instance_id"] = 4,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[10] = {
				["buff"] = "45.34084676",
				["id"] = 11,
				["instance_id"] = 4,
				["res"] = 17,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[11] = {
				["buff"] = "70.15381248",
				["id"] = 12,
				["instance_id"] = 4,
				["res"] = 18,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[12] = {
				["buff"] = "108.6139093",
				["id"] = 13,
				["instance_id"] = 4,
				["res"] = 19,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[13] = {
				["buff"] = "168.2270595",
				["id"] = 14,
				["instance_id"] = 4,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[14] = {
				["buff"] = "260.6274422",
				["id"] = 15,
				["instance_id"] = 4,
				["res"] = 21,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[15] = {
				["buff"] = "403.8480354",
				["id"] = 16,
				["instance_id"] = 4,
				["res"] = 22,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[16] = {
				["buff"] = "625.8399549",
				["id"] = 17,
				["instance_id"] = 4,
				["res"] = 23,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[17] = {
				["buff"] = "969.9274301",
				["id"] = 18,
				["instance_id"] = 4,
				["res"] = 24,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[18] = {
				["buff"] = "1503.263017",
				["id"] = 19,
				["instance_id"] = 4,
				["res"] = 25,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[19] = {
				["buff"] = "2329.933176",
				["id"] = 20,
				["instance_id"] = 4,
				["res"] = 26,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[20] = {
				["buff"] = "3611.271922",
				["id"] = 21,
				["instance_id"] = 4,
				["res"] = 27,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[21] = {
				["buff"] = "5597.34698",
				["id"] = 22,
				["instance_id"] = 4,
				["res"] = 28,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[22] = {
				["buff"] = "8675.763319",
				["id"] = 23,
				["instance_id"] = 4,
				["res"] = 29,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[23] = {
				["buff"] = "13447.30864",
				["id"] = 24,
				["instance_id"] = 4,
				["res"] = 30,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[24] = {
				["buff"] = "20843.2039",
				["id"] = 25,
				["instance_id"] = 4,
				["res"] = 31,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[25] = {
				["buff"] = "32306.84154",
				["id"] = 26,
				["instance_id"] = 4,
				["res"] = 32,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_1",
				["skill_icon"] = "icon_cy1_skill_1",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
		}
		,
		[2] = {
			[0] = {
				["buff"] = 1,
				["id"] = 27,
				["instance_id"] = 4,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 28,
				["instance_id"] = 4,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[2] = {
				["buff"] = "2.225",
				["id"] = 29,
				["instance_id"] = 4,
				["res"] = 5,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[3] = {
				["buff"] = "3.9125",
				["id"] = 30,
				["instance_id"] = 4,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[4] = {
				["buff"] = "6.44375",
				["id"] = 31,
				["instance_id"] = 4,
				["res"] = 11,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[5] = {
				["buff"] = "10.240625",
				["id"] = 32,
				["instance_id"] = 4,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[6] = {
				["buff"] = "15.9359375",
				["id"] = 33,
				["instance_id"] = 4,
				["res"] = 13,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[7] = {
				["buff"] = "24.47890625",
				["id"] = 34,
				["instance_id"] = 4,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[8] = {
				["buff"] = "37.29335938",
				["id"] = 35,
				["instance_id"] = 4,
				["res"] = 15,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[9] = {
				["buff"] = "56.51503906",
				["id"] = 36,
				["instance_id"] = 4,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[10] = {
				["buff"] = "85.34755859",
				["id"] = 37,
				["instance_id"] = 4,
				["res"] = 17,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[11] = {
				["buff"] = "128.5963379",
				["id"] = 38,
				["instance_id"] = 4,
				["res"] = 18,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[12] = {
				["buff"] = "193.4695068",
				["id"] = 39,
				["instance_id"] = 4,
				["res"] = 19,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[13] = {
				["buff"] = "290.7792603",
				["id"] = 40,
				["instance_id"] = 4,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[14] = {
				["buff"] = "436.7438904",
				["id"] = 41,
				["instance_id"] = 4,
				["res"] = 21,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[15] = {
				["buff"] = "655.6908356",
				["id"] = 42,
				["instance_id"] = 4,
				["res"] = 22,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[16] = {
				["buff"] = "984.1112534",
				["id"] = 43,
				["instance_id"] = 4,
				["res"] = 23,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[17] = {
				["buff"] = "1476.74188",
				["id"] = 44,
				["instance_id"] = 4,
				["res"] = 24,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[18] = {
				["buff"] = "2215.68782",
				["id"] = 45,
				["instance_id"] = 4,
				["res"] = 25,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[19] = {
				["buff"] = "3324.10673",
				["id"] = 46,
				["instance_id"] = 4,
				["res"] = 26,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[20] = {
				["buff"] = "4986.735095",
				["id"] = 47,
				["instance_id"] = 4,
				["res"] = 27,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[21] = {
				["buff"] = "7480.677643",
				["id"] = 48,
				["instance_id"] = 4,
				["res"] = 28,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[22] = {
				["buff"] = "11221.59146",
				["id"] = 49,
				["instance_id"] = 4,
				["res"] = 29,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[23] = {
				["buff"] = "16832.9622",
				["id"] = 50,
				["instance_id"] = 4,
				["res"] = 30,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[24] = {
				["buff"] = "25250.01829",
				["id"] = 51,
				["instance_id"] = 4,
				["res"] = 31,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[25] = {
				["buff"] = "37875.60244",
				["id"] = 52,
				["instance_id"] = 4,
				["res"] = 32,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_2",
				["skill_icon"] = "icon_cy1_skill_2",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
		}
		,
		[3] = {
			[0] = {
				["buff"] = 1,
				["id"] = 53,
				["instance_id"] = 4,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 54,
				["instance_id"] = 4,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[2] = {
				["buff"] = "1.7272",
				["id"] = 55,
				["instance_id"] = 4,
				["res"] = 5,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[3] = {
				["buff"] = "2.60528",
				["id"] = 56,
				["instance_id"] = 4,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[4] = {
				["buff"] = "3.834592",
				["id"] = 57,
				["instance_id"] = 4,
				["res"] = 11,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[5] = {
				["buff"] = "5.5556288",
				["id"] = 58,
				["instance_id"] = 4,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[6] = {
				["buff"] = "7.96508032",
				["id"] = 59,
				["instance_id"] = 4,
				["res"] = 13,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[7] = {
				["buff"] = "11.33831245",
				["id"] = 60,
				["instance_id"] = 4,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[8] = {
				["buff"] = "16.06083743",
				["id"] = 61,
				["instance_id"] = 4,
				["res"] = 15,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[9] = {
				["buff"] = "22.6723724",
				["id"] = 62,
				["instance_id"] = 4,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[10] = {
				["buff"] = "31.92852136",
				["id"] = 63,
				["instance_id"] = 4,
				["res"] = 17,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[11] = {
				["buff"] = "44.8871299",
				["id"] = 64,
				["instance_id"] = 4,
				["res"] = 18,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[12] = {
				["buff"] = "63.02918186",
				["id"] = 65,
				["instance_id"] = 4,
				["res"] = 19,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[13] = {
				["buff"] = "88.4280546",
				["id"] = 66,
				["instance_id"] = 4,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[14] = {
				["buff"] = "123.9864764",
				["id"] = 67,
				["instance_id"] = 4,
				["res"] = 21,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[15] = {
				["buff"] = "173.768267",
				["id"] = 68,
				["instance_id"] = 4,
				["res"] = 22,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[16] = {
				["buff"] = "243.4627738",
				["id"] = 69,
				["instance_id"] = 4,
				["res"] = 23,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[17] = {
				["buff"] = "341.0350834",
				["id"] = 70,
				["instance_id"] = 4,
				["res"] = 24,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[18] = {
				["buff"] = "477.6363167",
				["id"] = 71,
				["instance_id"] = 4,
				["res"] = 25,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[19] = {
				["buff"] = "668.8780434",
				["id"] = 72,
				["instance_id"] = 4,
				["res"] = 26,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[20] = {
				["buff"] = "936.6164608",
				["id"] = 73,
				["instance_id"] = 4,
				["res"] = 27,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[21] = {
				["buff"] = "1311.450245",
				["id"] = 74,
				["instance_id"] = 4,
				["res"] = 28,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[22] = {
				["buff"] = "1836.217543",
				["id"] = 75,
				["instance_id"] = 4,
				["res"] = 29,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[23] = {
				["buff"] = "2570.89176",
				["id"] = 76,
				["instance_id"] = 4,
				["res"] = 30,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[24] = {
				["buff"] = "3599.435664",
				["id"] = 77,
				["instance_id"] = 4,
				["res"] = 31,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[25] = {
				["buff"] = "5039.39713",
				["id"] = 78,
				["instance_id"] = 4,
				["res"] = 32,
				["skill_desc"] = "TXT_INSTANCE_SKILL_DESC_3",
				["skill_icon"] = "icon_cy1_skill_3",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
		}
		,
	}
	,
	[5] = {
		[1] = {
			[0] = {
				["buff"] = 1,
				["id"] = 79,
				["instance_id"] = 5,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 80,
				["instance_id"] = 5,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[2] = {
				["buff"] = "1.5805",
				["id"] = 81,
				["instance_id"] = 5,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[3] = {
				["buff"] = "2.325275",
				["id"] = 82,
				["instance_id"] = 5,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[4] = {
				["buff"] = "3.47967625",
				["id"] = 83,
				["instance_id"] = 5,
				["res"] = 7,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[5] = {
				["buff"] = "5.268998188",
				["id"] = 84,
				["instance_id"] = 5,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[6] = {
				["buff"] = "8.042447191",
				["id"] = 85,
				["instance_id"] = 5,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[7] = {
				["buff"] = "12.34129315",
				["id"] = 86,
				["instance_id"] = 5,
				["res"] = 9,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[8] = {
				["buff"] = "19.00450438",
				["id"] = 87,
				["instance_id"] = 5,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[9] = {
				["buff"] = "29.33248178",
				["id"] = 88,
				["instance_id"] = 5,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[10] = {
				["buff"] = "45.34084676",
				["id"] = 89,
				["instance_id"] = 5,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[11] = {
				["buff"] = "70.15381248",
				["id"] = 90,
				["instance_id"] = 5,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[12] = {
				["buff"] = "108.6139093",
				["id"] = 91,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[13] = {
				["buff"] = "168.2270595",
				["id"] = 92,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[14] = {
				["buff"] = "260.6274422",
				["id"] = 93,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[15] = {
				["buff"] = "403.8480354",
				["id"] = 94,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[16] = {
				["buff"] = "625.8399549",
				["id"] = 95,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[17] = {
				["buff"] = "969.9274301",
				["id"] = 96,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[18] = {
				["buff"] = "1503.263017",
				["id"] = 97,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[19] = {
				["buff"] = "2329.933176",
				["id"] = 98,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[20] = {
				["buff"] = "3611.271922",
				["id"] = 99,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[21] = {
				["buff"] = "5597.34698",
				["id"] = 100,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[22] = {
				["buff"] = "8675.763319",
				["id"] = 101,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[23] = {
				["buff"] = "13447.30864",
				["id"] = 102,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[24] = {
				["buff"] = "20843.2039",
				["id"] = 103,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[25] = {
				["buff"] = "32306.84154",
				["id"] = 104,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_1",
				["skill_icon"] = "icon_cy2_skill_2",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
		}
		,
		[2] = {
			[0] = {
				["buff"] = 1,
				["id"] = 105,
				["instance_id"] = 5,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 106,
				["instance_id"] = 5,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[2] = {
				["buff"] = "2.225",
				["id"] = 107,
				["instance_id"] = 5,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[3] = {
				["buff"] = "3.9125",
				["id"] = 108,
				["instance_id"] = 5,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[4] = {
				["buff"] = "6.44375",
				["id"] = 109,
				["instance_id"] = 5,
				["res"] = 7,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[5] = {
				["buff"] = "10.240625",
				["id"] = 110,
				["instance_id"] = 5,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[6] = {
				["buff"] = "15.9359375",
				["id"] = 111,
				["instance_id"] = 5,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[7] = {
				["buff"] = "24.47890625",
				["id"] = 112,
				["instance_id"] = 5,
				["res"] = 9,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[8] = {
				["buff"] = "37.29335938",
				["id"] = 113,
				["instance_id"] = 5,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[9] = {
				["buff"] = "56.51503906",
				["id"] = 114,
				["instance_id"] = 5,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[10] = {
				["buff"] = "85.34755859",
				["id"] = 115,
				["instance_id"] = 5,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[11] = {
				["buff"] = "128.5963379",
				["id"] = 116,
				["instance_id"] = 5,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[12] = {
				["buff"] = "193.4695068",
				["id"] = 117,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[13] = {
				["buff"] = "290.7792603",
				["id"] = 118,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[14] = {
				["buff"] = "436.7438904",
				["id"] = 119,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[15] = {
				["buff"] = "655.6908356",
				["id"] = 120,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[16] = {
				["buff"] = "984.1112534",
				["id"] = 121,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[17] = {
				["buff"] = "1476.74188",
				["id"] = 122,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[18] = {
				["buff"] = "2215.68782",
				["id"] = 123,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[19] = {
				["buff"] = "3324.10673",
				["id"] = 124,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[20] = {
				["buff"] = "4986.735095",
				["id"] = 125,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[21] = {
				["buff"] = "7480.677643",
				["id"] = 126,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[22] = {
				["buff"] = "11221.59146",
				["id"] = 127,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[23] = {
				["buff"] = "16832.9622",
				["id"] = 128,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[24] = {
				["buff"] = "25250.01829",
				["id"] = 129,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[25] = {
				["buff"] = "37875.60244",
				["id"] = 130,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_2",
				["skill_icon"] = "icon_cy2_skill_1",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
		}
		,
		[3] = {
			[0] = {
				["buff"] = 1,
				["id"] = 131,
				["instance_id"] = 5,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 132,
				["instance_id"] = 5,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[2] = {
				["buff"] = "1.7272",
				["id"] = 133,
				["instance_id"] = 5,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[3] = {
				["buff"] = "2.60528",
				["id"] = 134,
				["instance_id"] = 5,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[4] = {
				["buff"] = "3.834592",
				["id"] = 135,
				["instance_id"] = 5,
				["res"] = 7,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[5] = {
				["buff"] = "5.5556288",
				["id"] = 136,
				["instance_id"] = 5,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[6] = {
				["buff"] = "7.96508032",
				["id"] = 137,
				["instance_id"] = 5,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[7] = {
				["buff"] = "11.33831245",
				["id"] = 138,
				["instance_id"] = 5,
				["res"] = 9,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[8] = {
				["buff"] = "16.06083743",
				["id"] = 139,
				["instance_id"] = 5,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[9] = {
				["buff"] = "22.6723724",
				["id"] = 140,
				["instance_id"] = 5,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[10] = {
				["buff"] = "31.92852136",
				["id"] = 141,
				["instance_id"] = 5,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[11] = {
				["buff"] = "44.8871299",
				["id"] = 142,
				["instance_id"] = 5,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[12] = {
				["buff"] = "63.02918186",
				["id"] = 143,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[13] = {
				["buff"] = "88.4280546",
				["id"] = 144,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[14] = {
				["buff"] = "123.9864764",
				["id"] = 145,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[15] = {
				["buff"] = "173.768267",
				["id"] = 146,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[16] = {
				["buff"] = "243.4627738",
				["id"] = 147,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[17] = {
				["buff"] = "341.0350834",
				["id"] = 148,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[18] = {
				["buff"] = "477.6363167",
				["id"] = 149,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[19] = {
				["buff"] = "668.8780434",
				["id"] = 150,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[20] = {
				["buff"] = "936.6164608",
				["id"] = 151,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[21] = {
				["buff"] = "1311.450245",
				["id"] = 152,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[22] = {
				["buff"] = "1836.217543",
				["id"] = 153,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[23] = {
				["buff"] = "2570.89176",
				["id"] = 154,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[24] = {
				["buff"] = "3599.435664",
				["id"] = 155,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[25] = {
				["buff"] = "5039.39713",
				["id"] = 156,
				["instance_id"] = 5,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY2_SKILL_DESC_3",
				["skill_icon"] = "icon_cy2_skill_3",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_CY2_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
		}
		,
	}
	,
	[6] = {
		[1] = {
			[0] = {
				["buff"] = 1,
				["id"] = 157,
				["instance_id"] = 6,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 158,
				["instance_id"] = 6,
				["res"] = 1,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[2] = {
				["buff"] = "1.5805",
				["id"] = 159,
				["instance_id"] = 6,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[3] = {
				["buff"] = "2.325275",
				["id"] = 160,
				["instance_id"] = 6,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[4] = {
				["buff"] = "3.47967625",
				["id"] = 161,
				["instance_id"] = 6,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[5] = {
				["buff"] = "5.268998188",
				["id"] = 162,
				["instance_id"] = 6,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[6] = {
				["buff"] = "8.042447191",
				["id"] = 163,
				["instance_id"] = 6,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[7] = {
				["buff"] = "12.34129315",
				["id"] = 164,
				["instance_id"] = 6,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[8] = {
				["buff"] = "19.00450438",
				["id"] = 165,
				["instance_id"] = 6,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[9] = {
				["buff"] = "29.33248178",
				["id"] = 166,
				["instance_id"] = 6,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[10] = {
				["buff"] = "45.34084676",
				["id"] = 167,
				["instance_id"] = 6,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[11] = {
				["buff"] = "70.15381248",
				["id"] = 168,
				["instance_id"] = 6,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[12] = {
				["buff"] = "108.6139093",
				["id"] = 169,
				["instance_id"] = 6,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[13] = {
				["buff"] = "168.2270595",
				["id"] = 170,
				["instance_id"] = 6,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[14] = {
				["buff"] = "260.6274422",
				["id"] = 171,
				["instance_id"] = 6,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[15] = {
				["buff"] = "403.8480354",
				["id"] = 172,
				["instance_id"] = 6,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[16] = {
				["buff"] = "625.8399549",
				["id"] = 173,
				["instance_id"] = 6,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[17] = {
				["buff"] = "969.9274301",
				["id"] = 174,
				["instance_id"] = 6,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[18] = {
				["buff"] = "1503.263017",
				["id"] = 175,
				["instance_id"] = 6,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[19] = {
				["buff"] = "2329.933176",
				["id"] = 176,
				["instance_id"] = 6,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[20] = {
				["buff"] = "3611.271922",
				["id"] = 177,
				["instance_id"] = 6,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[21] = {
				["buff"] = "5597.34698",
				["id"] = 178,
				["instance_id"] = 6,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[22] = {
				["buff"] = "8675.763319",
				["id"] = 179,
				["instance_id"] = 6,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[23] = {
				["buff"] = "13447.30864",
				["id"] = 180,
				["instance_id"] = 6,
				["res"] = 18,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[24] = {
				["buff"] = "20843.2039",
				["id"] = 181,
				["instance_id"] = 6,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[25] = {
				["buff"] = "32306.84154",
				["id"] = 182,
				["instance_id"] = 6,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_1",
				["skill_icon"] = "icon_toy_skill_1",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
		}
		,
		[2] = {
			[0] = {
				["buff"] = 1,
				["id"] = 183,
				["instance_id"] = 6,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 184,
				["instance_id"] = 6,
				["res"] = 1,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[2] = {
				["buff"] = "2.225",
				["id"] = 185,
				["instance_id"] = 6,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[3] = {
				["buff"] = "3.9125",
				["id"] = 186,
				["instance_id"] = 6,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[4] = {
				["buff"] = "6.44375",
				["id"] = 187,
				["instance_id"] = 6,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[5] = {
				["buff"] = "10.240625",
				["id"] = 188,
				["instance_id"] = 6,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[6] = {
				["buff"] = "15.9359375",
				["id"] = 189,
				["instance_id"] = 6,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[7] = {
				["buff"] = "24.47890625",
				["id"] = 190,
				["instance_id"] = 6,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[8] = {
				["buff"] = "37.29335938",
				["id"] = 191,
				["instance_id"] = 6,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[9] = {
				["buff"] = "56.51503906",
				["id"] = 192,
				["instance_id"] = 6,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[10] = {
				["buff"] = "85.34755859",
				["id"] = 193,
				["instance_id"] = 6,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[11] = {
				["buff"] = "128.5963379",
				["id"] = 194,
				["instance_id"] = 6,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[12] = {
				["buff"] = "193.4695068",
				["id"] = 195,
				["instance_id"] = 6,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[13] = {
				["buff"] = "290.7792603",
				["id"] = 196,
				["instance_id"] = 6,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[14] = {
				["buff"] = "436.7438904",
				["id"] = 197,
				["instance_id"] = 6,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[15] = {
				["buff"] = "655.6908356",
				["id"] = 198,
				["instance_id"] = 6,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[16] = {
				["buff"] = "984.1112534",
				["id"] = 199,
				["instance_id"] = 6,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[17] = {
				["buff"] = "1476.74188",
				["id"] = 200,
				["instance_id"] = 6,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[18] = {
				["buff"] = "2215.68782",
				["id"] = 201,
				["instance_id"] = 6,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[19] = {
				["buff"] = "3324.10673",
				["id"] = 202,
				["instance_id"] = 6,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[20] = {
				["buff"] = "4986.735095",
				["id"] = 203,
				["instance_id"] = 6,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[21] = {
				["buff"] = "7480.677643",
				["id"] = 204,
				["instance_id"] = 6,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[22] = {
				["buff"] = "11221.59146",
				["id"] = 205,
				["instance_id"] = 6,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[23] = {
				["buff"] = "16832.9622",
				["id"] = 206,
				["instance_id"] = 6,
				["res"] = 18,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[24] = {
				["buff"] = "25250.01829",
				["id"] = 207,
				["instance_id"] = 6,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[25] = {
				["buff"] = "37875.60244",
				["id"] = 208,
				["instance_id"] = 6,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
		}
		,
		[3] = {
			[0] = {
				["buff"] = 1,
				["id"] = 209,
				["instance_id"] = 6,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 210,
				["instance_id"] = 6,
				["res"] = 1,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[2] = {
				["buff"] = "1.7272",
				["id"] = 211,
				["instance_id"] = 6,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[3] = {
				["buff"] = "2.60528",
				["id"] = 212,
				["instance_id"] = 6,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[4] = {
				["buff"] = "3.834592",
				["id"] = 213,
				["instance_id"] = 6,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[5] = {
				["buff"] = "5.5556288",
				["id"] = 214,
				["instance_id"] = 6,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[6] = {
				["buff"] = "7.96508032",
				["id"] = 215,
				["instance_id"] = 6,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[7] = {
				["buff"] = "11.33831245",
				["id"] = 216,
				["instance_id"] = 6,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[8] = {
				["buff"] = "16.06083743",
				["id"] = 217,
				["instance_id"] = 6,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[9] = {
				["buff"] = "22.6723724",
				["id"] = 218,
				["instance_id"] = 6,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[10] = {
				["buff"] = "31.92852136",
				["id"] = 219,
				["instance_id"] = 6,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[11] = {
				["buff"] = "44.8871299",
				["id"] = 220,
				["instance_id"] = 6,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[12] = {
				["buff"] = "63.02918186",
				["id"] = 221,
				["instance_id"] = 6,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[13] = {
				["buff"] = "88.4280546",
				["id"] = 222,
				["instance_id"] = 6,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[14] = {
				["buff"] = "123.9864764",
				["id"] = 223,
				["instance_id"] = 6,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[15] = {
				["buff"] = "173.768267",
				["id"] = 224,
				["instance_id"] = 6,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[16] = {
				["buff"] = "243.4627738",
				["id"] = 225,
				["instance_id"] = 6,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[17] = {
				["buff"] = "341.0350834",
				["id"] = 226,
				["instance_id"] = 6,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[18] = {
				["buff"] = "477.6363167",
				["id"] = 227,
				["instance_id"] = 6,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[19] = {
				["buff"] = "668.8780434",
				["id"] = 228,
				["instance_id"] = 6,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[20] = {
				["buff"] = "936.6164608",
				["id"] = 229,
				["instance_id"] = 6,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[21] = {
				["buff"] = "1311.450245",
				["id"] = 230,
				["instance_id"] = 6,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[22] = {
				["buff"] = "1836.217543",
				["id"] = 231,
				["instance_id"] = 6,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[23] = {
				["buff"] = "2570.89176",
				["id"] = 232,
				["instance_id"] = 6,
				["res"] = 18,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[24] = {
				["buff"] = "3599.435664",
				["id"] = 233,
				["instance_id"] = 6,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[25] = {
				["buff"] = "5039.39713",
				["id"] = 234,
				["instance_id"] = 6,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY3_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_CY3_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
		}
		,
	}
	,
	[7] = {
		[1] = {
			[0] = {
				["buff"] = 1,
				["id"] = 235,
				["instance_id"] = 7,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 236,
				["instance_id"] = 7,
				["res"] = 1,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[2] = {
				["buff"] = "1.5805",
				["id"] = 237,
				["instance_id"] = 7,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[3] = {
				["buff"] = "2.325275",
				["id"] = 238,
				["instance_id"] = 7,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[4] = {
				["buff"] = "3.47967625",
				["id"] = 239,
				["instance_id"] = 7,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[5] = {
				["buff"] = "5.268998188",
				["id"] = 240,
				["instance_id"] = 7,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[6] = {
				["buff"] = "8.042447191",
				["id"] = 241,
				["instance_id"] = 7,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[7] = {
				["buff"] = "12.34129315",
				["id"] = 242,
				["instance_id"] = 7,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[8] = {
				["buff"] = "19.00450438",
				["id"] = 243,
				["instance_id"] = 7,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[9] = {
				["buff"] = "29.33248178",
				["id"] = 244,
				["instance_id"] = 7,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[10] = {
				["buff"] = "45.34084676",
				["id"] = 245,
				["instance_id"] = 7,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[11] = {
				["buff"] = "70.15381248",
				["id"] = 246,
				["instance_id"] = 7,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[12] = {
				["buff"] = "108.6139093",
				["id"] = 247,
				["instance_id"] = 7,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[13] = {
				["buff"] = "168.2270595",
				["id"] = 248,
				["instance_id"] = 7,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[14] = {
				["buff"] = "260.6274422",
				["id"] = 249,
				["instance_id"] = 7,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[15] = {
				["buff"] = "403.8480354",
				["id"] = 250,
				["instance_id"] = 7,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[16] = {
				["buff"] = "625.8399549",
				["id"] = 251,
				["instance_id"] = 7,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[17] = {
				["buff"] = "969.9274301",
				["id"] = 252,
				["instance_id"] = 7,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[18] = {
				["buff"] = "1503.263017",
				["id"] = 253,
				["instance_id"] = 7,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[19] = {
				["buff"] = "2329.933176",
				["id"] = 254,
				["instance_id"] = 7,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[20] = {
				["buff"] = "3611.271922",
				["id"] = 255,
				["instance_id"] = 7,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[21] = {
				["buff"] = "5597.34698",
				["id"] = 256,
				["instance_id"] = 7,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[22] = {
				["buff"] = "8675.763319",
				["id"] = 257,
				["instance_id"] = 7,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[23] = {
				["buff"] = "13447.30864",
				["id"] = 258,
				["instance_id"] = 7,
				["res"] = 18,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[24] = {
				["buff"] = "20843.2039",
				["id"] = 259,
				["instance_id"] = 7,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
			[25] = {
				["buff"] = "32306.84154",
				["id"] = 260,
				["instance_id"] = 7,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_1",
				["skill_icon"] = "icon_NtClub_skill_1",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_1",
				["skill_type"] = 1,
			}
			,
		}
		,
		[2] = {
			[0] = {
				["buff"] = 1,
				["id"] = 261,
				["instance_id"] = 7,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 262,
				["instance_id"] = 7,
				["res"] = 1,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[2] = {
				["buff"] = "2.225",
				["id"] = 263,
				["instance_id"] = 7,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[3] = {
				["buff"] = "3.9125",
				["id"] = 264,
				["instance_id"] = 7,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[4] = {
				["buff"] = "6.44375",
				["id"] = 265,
				["instance_id"] = 7,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[5] = {
				["buff"] = "10.240625",
				["id"] = 266,
				["instance_id"] = 7,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[6] = {
				["buff"] = "15.9359375",
				["id"] = 267,
				["instance_id"] = 7,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[7] = {
				["buff"] = "24.47890625",
				["id"] = 268,
				["instance_id"] = 7,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[8] = {
				["buff"] = "37.29335938",
				["id"] = 269,
				["instance_id"] = 7,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[9] = {
				["buff"] = "56.51503906",
				["id"] = 270,
				["instance_id"] = 7,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[10] = {
				["buff"] = "85.34755859",
				["id"] = 271,
				["instance_id"] = 7,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[11] = {
				["buff"] = "128.5963379",
				["id"] = 272,
				["instance_id"] = 7,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[12] = {
				["buff"] = "193.4695068",
				["id"] = 273,
				["instance_id"] = 7,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[13] = {
				["buff"] = "290.7792603",
				["id"] = 274,
				["instance_id"] = 7,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[14] = {
				["buff"] = "436.7438904",
				["id"] = 275,
				["instance_id"] = 7,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[15] = {
				["buff"] = "655.6908356",
				["id"] = 276,
				["instance_id"] = 7,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[16] = {
				["buff"] = "984.1112534",
				["id"] = 277,
				["instance_id"] = 7,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[17] = {
				["buff"] = "1476.74188",
				["id"] = 278,
				["instance_id"] = 7,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[18] = {
				["buff"] = "2215.68782",
				["id"] = 279,
				["instance_id"] = 7,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[19] = {
				["buff"] = "3324.10673",
				["id"] = 280,
				["instance_id"] = 7,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[20] = {
				["buff"] = "4986.735095",
				["id"] = 281,
				["instance_id"] = 7,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[21] = {
				["buff"] = "7480.677643",
				["id"] = 282,
				["instance_id"] = 7,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[22] = {
				["buff"] = "11221.59146",
				["id"] = 283,
				["instance_id"] = 7,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[23] = {
				["buff"] = "16832.9622",
				["id"] = 284,
				["instance_id"] = 7,
				["res"] = 18,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[24] = {
				["buff"] = "25250.01829",
				["id"] = 285,
				["instance_id"] = 7,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
			[25] = {
				["buff"] = "37875.60244",
				["id"] = 286,
				["instance_id"] = 7,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_2",
				["skill_icon"] = "icon_toy_skill_2",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_2",
				["skill_type"] = 2,
			}
			,
		}
		,
		[3] = {
			[0] = {
				["buff"] = 1,
				["id"] = 287,
				["instance_id"] = 7,
				["res"] = 0,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 0,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[1] = {
				["buff"] = "1.1",
				["id"] = 288,
				["instance_id"] = 7,
				["res"] = 1,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 1,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[2] = {
				["buff"] = "1.7272",
				["id"] = 289,
				["instance_id"] = 7,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 2,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[3] = {
				["buff"] = "2.60528",
				["id"] = 290,
				["instance_id"] = 7,
				["res"] = 2,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 3,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[4] = {
				["buff"] = "3.834592",
				["id"] = 291,
				["instance_id"] = 7,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 4,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[5] = {
				["buff"] = "5.5556288",
				["id"] = 292,
				["instance_id"] = 7,
				["res"] = 4,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 5,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[6] = {
				["buff"] = "7.96508032",
				["id"] = 293,
				["instance_id"] = 7,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 6,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[7] = {
				["buff"] = "11.33831245",
				["id"] = 294,
				["instance_id"] = 7,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 7,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[8] = {
				["buff"] = "16.06083743",
				["id"] = 295,
				["instance_id"] = 7,
				["res"] = 6,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 8,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[9] = {
				["buff"] = "22.6723724",
				["id"] = 296,
				["instance_id"] = 7,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 9,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[10] = {
				["buff"] = "31.92852136",
				["id"] = 297,
				["instance_id"] = 7,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 10,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[11] = {
				["buff"] = "44.8871299",
				["id"] = 298,
				["instance_id"] = 7,
				["res"] = 8,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 11,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[12] = {
				["buff"] = "63.02918186",
				["id"] = 299,
				["instance_id"] = 7,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 12,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[13] = {
				["buff"] = "88.4280546",
				["id"] = 300,
				["instance_id"] = 7,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 13,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[14] = {
				["buff"] = "123.9864764",
				["id"] = 301,
				["instance_id"] = 7,
				["res"] = 10,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 14,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[15] = {
				["buff"] = "173.768267",
				["id"] = 302,
				["instance_id"] = 7,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 15,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[16] = {
				["buff"] = "243.4627738",
				["id"] = 303,
				["instance_id"] = 7,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 16,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[17] = {
				["buff"] = "341.0350834",
				["id"] = 304,
				["instance_id"] = 7,
				["res"] = 12,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 17,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[18] = {
				["buff"] = "477.6363167",
				["id"] = 305,
				["instance_id"] = 7,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 18,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[19] = {
				["buff"] = "668.8780434",
				["id"] = 306,
				["instance_id"] = 7,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 19,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[20] = {
				["buff"] = "936.6164608",
				["id"] = 307,
				["instance_id"] = 7,
				["res"] = 14,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 20,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[21] = {
				["buff"] = "1311.450245",
				["id"] = 308,
				["instance_id"] = 7,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 21,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[22] = {
				["buff"] = "1836.217543",
				["id"] = 309,
				["instance_id"] = 7,
				["res"] = 16,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 22,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[23] = {
				["buff"] = "2570.89176",
				["id"] = 310,
				["instance_id"] = 7,
				["res"] = 18,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 23,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[24] = {
				["buff"] = "3599.435664",
				["id"] = 311,
				["instance_id"] = 7,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 24,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
			[25] = {
				["buff"] = "5039.39713",
				["id"] = 312,
				["instance_id"] = 7,
				["res"] = 20,
				["skill_desc"] = "TXT_INSTANCE_CY4_SKILL_DESC_3",
				["skill_icon"] = "icon_toy_skill_3",
				["skill_level"] = 25,
				["skill_name"] = "TXT_INSTANCE_CY4_SKILL_NAME_3",
				["skill_type"] = 3,
			}
			,
		}
		,
	}
	,
}
return config_cy_instance_skill