---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenlongfa.
--- DateTime: 2025/2/6 15:33
---

---@class CEOHiringUI CEO总览界面
local CEOHiringUI = GameTableDefine.CEOHiringUI

local GameUIManager = GameTableDefine.GameUIManager

function CEOHiringUI:GetView()
    self.m_view = GameUIManager:SafeOpenUI(ENUM_GAME_UITYPE.CEO_HIRING_UI, self.m_view, require("GamePlay.Common.UI.CEO.CEOHiringUIView"), self, self.CloseView)
    return self.m_view
end

function CEOHiringUI:CloseView()
    ---当前正在执行雇佣操作的房间
    self.m_operationRoomIndex = nil
    GameUIManager:CloseUI(ENUM_GAME_UITYPE.CEO_HIRING_UI)
    self.m_view = nil
    collectgarbage("collect")
end

function CEOHiringUI:Show(ceoID, closeCallback)
    self:GetView():Invoke("Init",ceoID, closeCallback)
end

function CEOHiringUI:Refresh(roomIndex1,roomIndex2)
    if self.m_view then
        self.m_view:Refresh(roomIndex1,roomIndex2)
    end
end

---设置当前正在执行雇佣操作的房间
function CEOHiringUI:SetHiringRoomIndex(roomIndex)
    self.m_operationRoomIndex = roomIndex
end

return CEOHiringUI